Creating an Index

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Indexing\Creating an Index\WorldContinents.csv',
                encoding = 'ISO-8859-1')

pd.set_option('display.max.rows', 1359)
pd.set_option('display.max.columns', 15)

In [3]:
df

,continent,sub_region,country,code_3,Unnamed: 4
0,Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
1,Europe,Northern Europe,Åland Islands,ALA,"5,500,000"
2,Europe,Southern Europe,Albania,ALB,"3,300,000"
3,Africa,Northern Africa,Algeria,DZA,"9,500,000"
4,Oceania,Polynesia,American Samoa,ASM,"55,000"
5,Europe,Southern Europe,Andorra,AND,"77,000"
6,Africa,Middle Africa,Angola,AGO,"54,000,000"
7,Americas,Caribbean,Anguilla,AIA,"2,100,000"
8,Americas,Caribbean,Antigua and Barbuda,ATG,"98,000"
9,Americas,South America,Argentina,ARG,"45,000,000"
10,Asia,Western Asia,Armenia,ARM,"45,700,000"
11,Americas,Caribbean,Aruba,ABW,"11,600,000"
12,Oceania,Australia and New Zealand,Australia,AUS,"36,000,000"
13,Europe,Western Europe,Austria,AUT,"9,000,000"
14,Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
15,Americas,Caribbean,Bahamas,BHS,"7,500,000"
16,Asia,Western Asia,Bahrain,BHR,"1,900,000"
17,Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
18,Americas,Caribbean,Barbados,BRB,"44,000,000"
19,Europe,Eastern Europe,Belarus,BLR,"9,400,000"
20,Europe,Western Europe,Belgium,BEL,"12,000,000"
21,Americas,Central America,Belize,BLZ,"9,000,000"
22,Africa,Western Africa,Benin,BEN,"17,400,000"
23,Americas,Northern America,Bermuda,BMU,"64,000"
24,Asia,Southern Asia,Bhutan,BTN,"771,000"
25,Americas,South America,Bolivia (Plurinational State of),BOL,"12,900,000"
26,Americas,Caribbean,"Bonaire, Sint Eustatius and Saba",BES,"4,300,000"
27,Europe,Southern Europe,Bosnia and Herzegovina,BIH,"5,000,000"
28,Africa,Southern Africa,Botswana,BWA,"29,000,000"
29,Americas,South America,Brazil,BRA,"32,700,000"
30,Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
31,Europe,Eastern Europe,Bulgaria,BGR,"6,900,000"
32,Africa,Western Africa,Burkina Faso,BFA,"31,000,000"
33,Africa,Eastern Africa,Burundi,BDI,"128,000,000"
34,Africa,Western Africa,Cabo Verde,CPV,"556,000"
35,Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
36,Africa,Middle Africa,Cameroon,CMR,"38,000,000"
37,Americas,Northern America,Canada,CAN,"60,000,000"
38,Americas,Caribbean,Cayman Islands,CYM,"66,000"
39,Africa,Middle Africa,Central African Republic,CAF,"84,000,000"
40,Africa,Middle Africa,Chad,TCD,"2,100,000"
41,Americas,South America,Chile,CHL,"25,000,000"
42,Asia,Eastern Asia,China,CHN,"1,412,000,000"
43,Americas,South America,Colombia,COL,"51,000,000"
44,Africa,Eastern Africa,Comoros,COM,"870,000"
45,Africa,Middle Africa,Congo,COG,"5,500,000"
46,Africa,Middle Africa,Congo (Democratic Republic of the),COD,"89,000,000"
47,Oceania,Polynesia,Cook Islands,COK,"206,000,000"
48,Americas,Central America,Costa Rica,CRI,"5,100,000"
49,Africa,Western Africa,Côte d'Ivoire,CIV,"38,000,000"
50,Europe,Southern Europe,Croatia,HRV,"7,900,000"
51,Americas,Caribbean,Cuba,CUB,"110,000,000"
52,Americas,Caribbean,Curaçao,CUW,"2,600,000"
53,Asia,Western Asia,Cyprus,CYP,"1,200,000"
54,Europe,Eastern Europe,Czech Republic,CZE,"102,000,000"
55,Europe,Northern Europe,Denmark,DNK,"5,800,000"
56,Africa,Eastern Africa,Djibouti,DJI,"988,000"
57,Americas,Caribbean,Dominica,DMA,"72,000"
58,Americas,Caribbean,Dominican Republic,DOM,"11,200,000"
59,Americas,South America,Ecuador,ECU,"2,900,000"
60,Africa,Northern Africa,Egypt,EGY,"11,300,000"
61,Americas,Central America,El Salvador,SLV,"6,500,000"
62,Africa,Middle Africa,Equatorial Guinea,GNQ,"1,700,000"
63,Africa,Eastern Africa,Eritrea,ERI,"5,100,000"
64,Europe,Northern Europe,Estonia,EST,"1,300,000"
65,Africa,Eastern Africa,Ethiopia,ETH,"16,700,000"
66,Americas,South America,Falkland Islands (Malvinas),FLK,"5,500,000"
67,Europe,Northern Europe,Faroe Islands,FRO,"49,000"
68,Oceania,Melanesia,Fiji,FJI,"896,000"
69,Europe,Northern Europe,Finland,FIN,"5,500,000"
70,Europe,Western Europe,France,FRA,"67,000,000"
71,Americas,South America,French Guiana,GUF,"45,000,000"
72,Oceania,Polynesia,French Polynesia,PYF,"40,000,000"
73,Africa,Middle Africa,Gabon,GAB,"28,000,000"
74,Africa,Western Africa,Gambia,GMB,"3,000,000"
75,Asia,Western Asia,Georgia,GEO,"5,400,000"
76,Europe,Western Europe,Germany,DEU,"83,200,000"
77,Africa,Western Africa,Ghana,GHA,"51,000,000"
78,Europe,Southern Europe,Gibraltar,GIB,"6,500,000"
79,Europe,Southern Europe,Greece,GRC,"10,800,000"
80,Americas,Northern America,Greenland,GRL,"56,000"
81,Americas,Caribbean,Grenada,GRD,"16,700,000"
82,Americas,Caribbean,Guadeloupe,GLP,"9,000,000"
83,Oceania,Micronesia,Guam,GUM,"2,800,000"
84,Americas,Central America,Guatemala,GTM,"21,000,000"
85,Europe,Northern Europe,Guernsey,GGY,"63,000"
86,Africa,Western Africa,Guinea,GIN,"18,700,000"
87,Africa,Western Africa,Guinea-Bissau,GNB,"10,000,000"
88,Americas,South America,Guyana,GUY,"787,000"
89,Americas,Caribbean,Haiti,HTI,"114,000,000"
90,Europe,Southern Europe,Holy See,VAT,800
91,Americas,Central America,Honduras,HND,"10,000,000"
92,Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
93,Europe,Eastern Europe,Hungary,HUN,"9,600,000"
94,Europe,Northern Europe,Iceland,ISL,"6,900,000"
95,Asia,Southern Asia,India,IND,"1,400,000,000"
96,Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
97,Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
98,Asia,Western Asia,Iraq,IRQ,"89,000,000"
99,Europe,Northern Europe,Ireland,IRL,"5,000,000"
100,Europe,Northern Europe,Isle of Man,IMN,"85,000"
101,Asia,Western Asia,Israel,ISR,"9,300,000"
102,Europe,Southern Europe,Italy,ITA,"60,000,000"
103,Americas,Caribbean,Jamaica,JAM,"3,700,000"
104,Asia,Eastern Asia,Japan,JPN,"18,000,000"
105,Europe,Northern Europe,Jersey,JEY,"11,800,000"
106,Asia,Western Asia,Jordan,JOR,"10,300,000"
107,Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
108,Africa,Eastern Africa,Kenya,KEN,"53,800,000"
109,Oceania,Micronesia,Kiribati,KIR,"17,600,000"
110,Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
111,Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
112,Asia,Western Asia,Kuwait,KWT,"8,300,000"
113,Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
114,Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
115,Europe,Northern Europe,Latvia,LVA,"10,000,000"
116,Asia,Western Asia,Lebanon,LBN,"6,800,000"
117,Africa,Southern Africa,Lesotho,LSO,"27,700,000"
118,Africa,Western Africa,Liberia,LBR,"5,000,000"
119,Africa,Northern Africa,Libya,LBY,"6,900,000"
120,Europe,Western Europe,Liechtenstein,LIE,"68,000,000"
121,Europe,Northern Europe,Lithuania,LTU,"3,500,000"
122,Europe,Western Europe,Luxembourg,LUX,"633,000"
123,Asia,Eastern Asia,Macao,MAC,"650,000"
124,Europe,Southern Europe,Macedonia (the former Yugoslav Republic of),MKD,"26,000,000"
125,Africa,Eastern Africa,Madagascar,MDG,"4,300,000"
126,Africa,Eastern Africa,Malawi,MWI,"25,800,000"
127,Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
128,Asia,Southern Asia,Maldives,MDV,"540,000"
129,Africa,Western Africa,Mali,MLI,"30,000,000"
130,Europe,Southern Europe,Malta,MLT,"97,000,000"
131,Oceania,Micronesia,Marshall Islands,MHL,"59,000"
132,Americas,Caribbean,Martinique,MTQ,"6,900,000"
133,Africa,Western Africa,Mauritania,MRT,"83,200,000"
134,Africa,Eastern Africa,Mauritius,MUS,"1,300,000"
135,Africa,Eastern Africa,Mayotte,MYT,"4,800,000"
136,Americas,Central America,Mexico,MEX,"18,400,000"
137,Oceania,Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
138,Europe,Eastern Europe,Moldova (Republic of),MDA,"3,300,000"
139,Europe,Western Europe,Monaco,MCO,"7,100,000"
140,Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
141,Europe,Southern Europe,Montenegro,MNE,"622,000"
142,Americas,Caribbean,Montserrat,MSR,"5,000"
143,Africa,Northern Africa,Morocco,MAR,"6,800,000"
144,Africa,Eastern Africa,Mozambique,MOZ,"51,600,000"
145,Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
146,Africa,Southern Africa,Namibia,NAM,"3,200,000"
147,Oceania,Micronesia,Nauru,NRU,"144,000,000"
148,Asia,Southern Asia,Nepal,NPL,"44,000,000"
149,Europe,Western Europe,Netherlands,NLD,"2,800,000"
150,Oceania,Melanesia,New Caledonia,NCL,"44,000,000"
151,Oceania,Australia and New Zealand,New Zealand,NZL,"84,000,000"
152,Americas,Central America,Nicaragua,NIC,"6,600,000"
153,Africa,Western Africa,Niger,NER,"35,000,000"
154,Africa,Western Africa,Nigeria,NGA,"31,000,000"
155,Oceania,Polynesia,Niue,NIU,"2,400,000"
156,Oceania,Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
157,Oceania,Micronesia,Northern Mariana Islands,MNP,"58,000"
158,Europe,Northern Europe,Norway,NOR,"5,400,000"
159,Asia,Western Asia,Oman,OMN,"5,000,000"
160,Asia,Southern Asia,Pakistan,PAK,"331,000,000"
161,Oceania,Micronesia,Palau,PLW,"220,000,000"
162,Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
163,Americas,Central America,Panama,PAN,"8,700,000"
164,Oceania,Melanesia,Papua New Guinea,PNG,"9,000,000"
165,Americas,South America,Paraguay,PRY,"7,100,000"
166,Americas,South America,Peru,PER,"59,000,000"
167,Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
168,Oceania,Polynesia,Pitcairn,PCN,"50,000,000"
169,Europe,Eastern Europe,Poland,POL,"67,000,000"
170,Europe,Southern Europe,Portugal,PRT,"10,400,000"
171,Americas,Caribbean,Puerto Rico,PRI,"47,000,000"
172,Asia,Western Asia,Qatar,QAT,"3,500,000"
173,Africa,Eastern Africa,Réunion,REU,"859,000"
174,Europe,Eastern Europe,Romania,ROU,"24,000,000"
175,Europe,Eastern Europe,Russian Federation,RUS,"19,000,000"
176,Africa,Eastern Africa,Rwanda,RWA,"17,500,000"
177,Americas,Caribbean,Saint Barthélemy,BLM,"9,900"
178,Africa,Western Africa,"Saint Helena, Ascension and Tristan da Cunha",SHN,"6,000"
179,Americas,Caribbean,Saint Kitts and Nevis,KNA,"53,000"
180,Americas,Caribbean,Saint Lucia,LCA,"23,800,000"
181,Americas,Caribbean,Saint Martin (French part),MAF,"7,300,000"
182,Americas,Northern America,Saint Pierre and Miquelon,SPM,"5,700"
183,Americas,Caribbean,Saint Vincent and the Grenadines,VCT,"16,400,000"
184,Oceania,Polynesia,Samoa,WSM,"26,000,000"
185,Europe,Southern Europe,San Marino,SMR,"6,600,000"
186,Africa,Middle Africa,Sao Tome and Principe,STP,"33,000,000"
187,Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
188,Africa,Western Africa,Senegal,SEN,"2,300,000"
189,Europe,Southern Europe,Serbia,SRB,"6,900,000"
190,Africa,Eastern Africa,Seychelles,SYC,"98,000"
191,Africa,Western Africa,Sierra Leone,SLE,"7,900,000"
192,Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
193,Americas,Caribbean,Sint Maarten (Dutch part),SXM,"9,300,000"
194,Europe,Eastern Europe,Slovakia,SVK,"5,500,000"
195,Europe,Southern Europe,Slovenia,SVN,"276,000,000"
196,Oceania,Melanesia,Solomon Islands,SLB,"686,000"
197,Africa,Eastern Africa,Somalia,SOM,"19,100,000"
198,Africa,Southern Africa,South Africa,ZAF,"59,000,000"
199,Africa,Eastern Africa,South Sudan,SSD,"11,900,000"
200,Europe,Southern Europe,Spain,ESP,"47,000,000"
201,Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
202,Africa,Northern Africa,Sudan,SDN,"9,600,000"
203,Americas,South America,Suriname,SUR,"591,000"
204,Europe,Northern Europe,Svalbard and Jan Mayen,SJM,"4,000,000"
205,Africa,Southern Africa,Swaziland,SWZ,"1,200,000"
206,Europe,Northern Europe,Sweden,SWE,"10,700,000"
207,Europe,Western Europe,Switzerland,CHE,"8,700,000"
208,Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
209,Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
210,Asia,Central Asia,Tajikistan,TJK,"9,500,000"
211,Africa,Eastern Africa,"Tanzania, United Republic of",TZA,"59,700,000"
212,Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
213,Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
214,Africa,Western Africa,Togo,TGO,"8,300,000"
215,Oceania,Polynesia,Tokelau,TKL,"2,000,000"
216,Oceania,Polynesia,Tonga,TON,"11,500,000"
217,Americas,Caribbean,Trinidad and Tobago,TTO,"1,900,000"
218,Africa,Northern Africa,Tunisia,TUN,"125,000,000"
219,Asia,Western Asia,Turkey,TUR,"84,000,000"
220,Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
221,Americas,Caribbean,Turks and Caicos Islands,TCA,"69,800,000"
222,Oceania,Polynesia,Tuvalu,TUV,"15,000,000"
223,Africa,Eastern Africa,Uganda,UGA,"45,700,000"
224,Europe,Eastern Europe,Ukraine,UKR,"9,900,000"
225,Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
226,Europe,Northern Europe,United Kingdom of Great Britain and Northern I...,GBR,"68,000,000"
227,Americas,Northern America,United States of America,USA,"59,700,000"
228,Americas,South America,Uruguay,URY,"5,100,000"
229,Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
230,Oceania,Melanesia,Vanuatu,VUT,"5,900,000"
231,Americas,South America,Venezuela (Bolivarian Republic of),VEN,"4,900,000"
232,Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
233,Americas,Caribbean,Virgin Islands (British),VGB,"5,800,000"
234,Americas,Caribbean,Virgin Islands (U.S.),VIR,"11,400,000"
235,Oceania,Polynesia,Wallis and Futuna,WLF,"15,900,000"
236,Africa,Northern Africa,Western Sahara,ESH,"597,000"
237,Asia,Western Asia,Yemen,YEM,"5,500,000"
238,Africa,Eastern Africa,Zambia,ZMB,"213,000,000"
239,Africa,Eastern Africa,Zimbabwe,ZWE,"19,100,000"

In [4]:
df_world = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Indexing\Creating an Index\WorldContinents.csv',
                encoding = 'ISO-8859-1', index_col = 'country')

df_world

,continent,sub_region,code_3,Unnamed: 4
country,,,,
Afghanistan,Asia,Southern Asia,AFG,"6,900,000"
Åland Islands,Europe,Northern Europe,ALA,"5,500,000"
Albania,Europe,Southern Europe,ALB,"3,300,000"
Algeria,Africa,Northern Africa,DZA,"9,500,000"
American Samoa,Oceania,Polynesia,ASM,"55,000"
Andorra,Europe,Southern Europe,AND,"77,000"
Angola,Africa,Middle Africa,AGO,"54,000,000"
Anguilla,Americas,Caribbean,AIA,"2,100,000"
Antigua and Barbuda,Americas,Caribbean,ATG,"98,000"
Argentina,Americas,South America,ARG,"45,000,000"
Armenia,Asia,Western Asia,ARM,"45,700,000"
Aruba,Americas,Caribbean,ABW,"11,600,000"
Australia,Oceania,Australia and New Zealand,AUS,"36,000,000"
Austria,Europe,Western Europe,AUT,"9,000,000"
Azerbaijan,Asia,Western Asia,AZE,"10,000,000"
Bahamas,Americas,Caribbean,BHS,"7,500,000"
Bahrain,Asia,Western Asia,BHR,"1,900,000"
Bangladesh,Asia,Southern Asia,BGD,"2,500,000"
Barbados,Americas,Caribbean,BRB,"44,000,000"
Belarus,Europe,Eastern Europe,BLR,"9,400,000"
Belgium,Europe,Western Europe,BEL,"12,000,000"
Belize,Americas,Central America,BLZ,"9,000,000"
Benin,Africa,Western Africa,BEN,"17,400,000"
Bermuda,Americas,Northern America,BMU,"64,000"
Bhutan,Asia,Southern Asia,BTN,"771,000"
Bolivia (Plurinational State of),Americas,South America,BOL,"12,900,000"
"Bonaire, Sint Eustatius and Saba",Americas,Caribbean,BES,"4,300,000"
Bosnia and Herzegovina,Europe,Southern Europe,BIH,"5,000,000"
Botswana,Africa,Southern Africa,BWA,"29,000,000"
Brazil,Americas,South America,BRA,"32,700,000"
Brunei Darussalam,Asia,South-Eastern Asia,BRN,"9,400,000"
Bulgaria,Europe,Eastern Europe,BGR,"6,900,000"
Burkina Faso,Africa,Western Africa,BFA,"31,000,000"
Burundi,Africa,Eastern Africa,BDI,"128,000,000"
Cabo Verde,Africa,Western Africa,CPV,"556,000"
Cambodia,Asia,South-Eastern Asia,KHM,"2,200,000"
Cameroon,Africa,Middle Africa,CMR,"38,000,000"
Canada,Americas,Northern America,CAN,"60,000,000"
Cayman Islands,Americas,Caribbean,CYM,"66,000"
Central African Republic,Africa,Middle Africa,CAF,"84,000,000"
Chad,Africa,Middle Africa,TCD,"2,100,000"
Chile,Americas,South America,CHL,"25,000,000"
China,Asia,Eastern Asia,CHN,"1,412,000,000"
Colombia,Americas,South America,COL,"51,000,000"
Comoros,Africa,Eastern Africa,COM,"870,000"
Congo,Africa,Middle Africa,COG,"5,500,000"
Congo (Democratic Republic of the),Africa,Middle Africa,COD,"89,000,000"
Cook Islands,Oceania,Polynesia,COK,"206,000,000"
Costa Rica,Americas,Central America,CRI,"5,100,000"
Côte d'Ivoire,Africa,Western Africa,CIV,"38,000,000"
Croatia,Europe,Southern Europe,HRV,"7,900,000"
Cuba,Americas,Caribbean,CUB,"110,000,000"
Curaçao,Americas,Caribbean,CUW,"2,600,000"
Cyprus,Asia,Western Asia,CYP,"1,200,000"
Czech Republic,Europe,Eastern Europe,CZE,"102,000,000"
Denmark,Europe,Northern Europe,DNK,"5,800,000"
Djibouti,Africa,Eastern Africa,DJI,"988,000"
Dominica,Americas,Caribbean,DMA,"72,000"
Dominican Republic,Americas,Caribbean,DOM,"11,200,000"
Ecuador,Americas,South America,ECU,"2,900,000"
Egypt,Africa,Northern Africa,EGY,"11,300,000"
El Salvador,Americas,Central America,SLV,"6,500,000"
Equatorial Guinea,Africa,Middle Africa,GNQ,"1,700,000"
Eritrea,Africa,Eastern Africa,ERI,"5,100,000"
Estonia,Europe,Northern Europe,EST,"1,300,000"
Ethiopia,Africa,Eastern Africa,ETH,"16,700,000"
Falkland Islands (Malvinas),Americas,South America,FLK,"5,500,000"
Faroe Islands,Europe,Northern Europe,FRO,"49,000"
Fiji,Oceania,Melanesia,FJI,"896,000"
Finland,Europe,Northern Europe,FIN,"5,500,000"
France,Europe,Western Europe,FRA,"67,000,000"
French Guiana,Americas,South America,GUF,"45,000,000"
French Polynesia,Oceania,Polynesia,PYF,"40,000,000"
Gabon,Africa,Middle Africa,GAB,"28,000,000"
Gambia,Africa,Western Africa,GMB,"3,000,000"
Georgia,Asia,Western Asia,GEO,"5,400,000"
Germany,Europe,Western Europe,DEU,"83,200,000"
Ghana,Africa,Western Africa,GHA,"51,000,000"
Gibraltar,Europe,Southern Europe,GIB,"6,500,000"
Greece,Europe,Southern Europe,GRC,"10,800,000"
Greenland,Americas,Northern America,GRL,"56,000"
Grenada,Americas,Caribbean,GRD,"16,700,000"
Guadeloupe,Americas,Caribbean,GLP,"9,000,000"
Guam,Oceania,Micronesia,GUM,"2,800,000"
Guatemala,Americas,Central America,GTM,"21,000,000"
Guernsey,Europe,Northern Europe,GGY,"63,000"
Guinea,Africa,Western Africa,GIN,"18,700,000"
Guinea-Bissau,Africa,Western Africa,GNB,"10,000,000"
Guyana,Americas,South America,GUY,"787,000"
Haiti,Americas,Caribbean,HTI,"114,000,000"
Holy See,Europe,Southern Europe,VAT,800
Honduras,Americas,Central America,HND,"10,000,000"
Hong Kong,Asia,Eastern Asia,HKG,"7,500,000"
Hungary,Europe,Eastern Europe,HUN,"9,600,000"
Iceland,Europe,Northern Europe,ISL,"6,900,000"
India,Asia,Southern Asia,IND,"1,400,000,000"
Indonesia,Asia,South-Eastern Asia,IDN,"4,600,000"
Iran (Islamic Republic of),Asia,Southern Asia,IRN,"84,000,000"
Iraq,Asia,Western Asia,IRQ,"89,000,000"
Ireland,Europe,Northern Europe,IRL,"5,000,000"
Isle of Man,Europe,Northern Europe,IMN,"85,000"
Israel,Asia,Western Asia,ISR,"9,300,000"
Italy,Europe,Southern Europe,ITA,"60,000,000"
Jamaica,Americas,Caribbean,JAM,"3,700,000"
Japan,Asia,Eastern Asia,JPN,"18,000,000"
Jersey,Europe,Northern Europe,JEY,"11,800,000"
Jordan,Asia,Western Asia,JOR,"10,300,000"
Kazakhstan,Asia,Central Asia,KAZ,"22,000,000"
Kenya,Africa,Eastern Africa,KEN,"53,800,000"
Kiribati,Oceania,Micronesia,KIR,"17,600,000"
Korea (Democratic People's Republic of),Asia,Eastern Asia,PRK,"38,000,000"
Korea (Republic of),Asia,Eastern Asia,KOR,"51,600,000"
Kuwait,Asia,Western Asia,KWT,"8,300,000"
Kyrgyzstan,Asia,Central Asia,KGZ,"6,600,000"
Lao People's Democratic Republic,Asia,South-Eastern Asia,LAO,"7,300,000"
Latvia,Europe,Northern Europe,LVA,"10,000,000"
Lebanon,Asia,Western Asia,LBN,"6,800,000"
Lesotho,Africa,Southern Africa,LSO,"27,700,000"
Liberia,Africa,Western Africa,LBR,"5,000,000"
Libya,Africa,Northern Africa,LBY,"6,900,000"
Liechtenstein,Europe,Western Europe,LIE,"68,000,000"
Lithuania,Europe,Northern Europe,LTU,"3,500,000"
Luxembourg,Europe,Western Europe,LUX,"633,000"
Macao,Asia,Eastern Asia,MAC,"650,000"
Macedonia (the former Yugoslav Republic of),Europe,Southern Europe,MKD,"26,000,000"
Madagascar,Africa,Eastern Africa,MDG,"4,300,000"
Malawi,Africa,Eastern Africa,MWI,"25,800,000"
Malaysia,Asia,South-Eastern Asia,MYS,"53,800,000"
Maldives,Asia,Southern Asia,MDV,"540,000"
Mali,Africa,Western Africa,MLI,"30,000,000"
Malta,Europe,Southern Europe,MLT,"97,000,000"
Marshall Islands,Oceania,Micronesia,MHL,"59,000"
Martinique,Americas,Caribbean,MTQ,"6,900,000"
Mauritania,Africa,Western Africa,MRT,"83,200,000"
Mauritius,Africa,Eastern Africa,MUS,"1,300,000"
Mayotte,Africa,Eastern Africa,MYT,"4,800,000"
Mexico,Americas,Central America,MEX,"18,400,000"
Micronesia (Federated States of),Oceania,Micronesia,FSM,"164,000,000"
Moldova (Republic of),Europe,Eastern Europe,MDA,"3,300,000"
Monaco,Europe,Western Europe,MCO,"7,100,000"
Mongolia,Asia,Eastern Asia,MNG,"5,000,000"
Montenegro,Europe,Southern Europe,MNE,"622,000"
Montserrat,Americas,Caribbean,MSR,"5,000"
Morocco,Africa,Northern Africa,MAR,"6,800,000"
Mozambique,Africa,Eastern Africa,MOZ,"51,600,000"
Myanmar,Asia,South-Eastern Asia,MMR,"54,000,000"
Namibia,Africa,Southern Africa,NAM,"3,200,000"
Nauru,Oceania,Micronesia,NRU,"144,000,000"
Nepal,Asia,Southern Asia,NPL,"44,000,000"
Netherlands,Europe,Western Europe,NLD,"2,800,000"
New Caledonia,Oceania,Melanesia,NCL,"44,000,000"
New Zealand,Oceania,Australia and New Zealand,NZL,"84,000,000"
Nicaragua,Americas,Central America,NIC,"6,600,000"
Niger,Africa,Western Africa,NER,"35,000,000"
Nigeria,Africa,Western Africa,NGA,"31,000,000"
Niue,Oceania,Polynesia,NIU,"2,400,000"
Norfolk Island,Oceania,Australia and New Zealand,NFK,"20,300,000"
Northern Mariana Islands,Oceania,Micronesia,MNP,"58,000"
Norway,Europe,Northern Europe,NOR,"5,400,000"
Oman,Asia,Western Asia,OMN,"5,000,000"
Pakistan,Asia,Southern Asia,PAK,"331,000,000"
Palau,Oceania,Micronesia,PLW,"220,000,000"
"Palestine, State of",Asia,Western Asia,PSE,"5,100,000"
Panama,Americas,Central America,PAN,"8,700,000"
Papua New Guinea,Oceania,Melanesia,PNG,"9,000,000"
Paraguay,Americas,South America,PRY,"7,100,000"
Peru,Americas,South America,PER,"59,000,000"
Philippines,Asia,South-Eastern Asia,PHL,"13,100,000"
Pitcairn,Oceania,Polynesia,PCN,"50,000,000"
Poland,Europe,Eastern Europe,POL,"67,000,000"
Portugal,Europe,Southern Europe,PRT,"10,400,000"
Puerto Rico,Americas,Caribbean,PRI,"47,000,000"
Qatar,Asia,Western Asia,QAT,"3,500,000"
Réunion,Africa,Eastern Africa,REU,"859,000"
Romania,Europe,Eastern Europe,ROU,"24,000,000"
Russian Federation,Europe,Eastern Europe,RUS,"19,000,000"
Rwanda,Africa,Eastern Africa,RWA,"17,500,000"
Saint Barthélemy,Americas,Caribbean,BLM,"9,900"
"Saint Helena, Ascension and Tristan da Cunha",Africa,Western Africa,SHN,"6,000"
Saint Kitts and Nevis,Americas,Caribbean,KNA,"53,000"
Saint Lucia,Americas,Caribbean,LCA,"23,800,000"
Saint Martin (French part),Americas,Caribbean,MAF,"7,300,000"
Saint Pierre and Miquelon,Americas,Northern America,SPM,"5,700"
Saint Vincent and the Grenadines,Americas,Caribbean,VCT,"16,400,000"
Samoa,Oceania,Polynesia,WSM,"26,000,000"
San Marino,Europe,Southern Europe,SMR,"6,600,000"
Sao Tome and Principe,Africa,Middle Africa,STP,"33,000,000"
Saudi Arabia,Asia,Western Asia,SAU,"6,600,000"
Senegal,Africa,Western Africa,SEN,"2,300,000"
Serbia,Europe,Southern Europe,SRB,"6,900,000"
Seychelles,Africa,Eastern Africa,SYC,"98,000"
Sierra Leone,Africa,Western Africa,SLE,"7,900,000"
Singapore,Asia,South-Eastern Asia,SGP,"5,900,000"
Sint Maarten (Dutch part),Americas,Caribbean,SXM,"9,300,000"
Slovakia,Europe,Eastern Europe,SVK,"5,500,000"
Slovenia,Europe,Southern Europe,SVN,"276,000,000"
Solomon Islands,Oceania,Melanesia,SLB,"686,000"
Somalia,Africa,Eastern Africa,SOM,"19,100,000"
South Africa,Africa,Southern Africa,ZAF,"59,000,000"
South Sudan,Africa,Eastern Africa,SSD,"11,900,000"
Spain,Europe,Southern Europe,ESP,"47,000,000"
Sri Lanka,Asia,Southern Asia,LKA,"33,000,000"
Sudan,Africa,Northern Africa,SDN,"9,600,000"
Suriname,Americas,South America,SUR,"591,000"
Svalbard and Jan Mayen,Europe,Northern Europe,SJM,"4,000,000"
Swaziland,Africa,Southern Africa,SWZ,"1,200,000"
Sweden,Europe,Northern Europe,SWE,"10,700,000"
Switzerland,Europe,Western Europe,CHE,"8,700,000"
Syrian Arab Republic,Asia,Western Asia,SYR,"2,800,000"
"Taiwan, Province of China",Asia,Eastern Asia,TWN,"34,000,000"
Tajikistan,Asia,Central Asia,TJK,"9,500,000"
"Tanzania, United Republic of",Africa,Eastern Africa,TZA,"59,700,000"
Thailand,Asia,South-Eastern Asia,THA,"69,800,000"
Timor-Leste,Asia,South-Eastern Asia,TLS,"1,300,000"
Togo,Africa,Western Africa,TGO,"8,300,000"
Tokelau,Oceania,Polynesia,TKL,"2,000,000"
Tonga,Oceania,Polynesia,TON,"11,500,000"
Trinidad and Tobago,Americas,Caribbean,TTO,"1,900,000"
Tunisia,Africa,Northern Africa,TUN,"125,000,000"
Turkey,Asia,Western Asia,TUR,"84,000,000"
Turkmenistan,Asia,Central Asia,TKM,"6,000,000"
Turks and Caicos Islands,Americas,Caribbean,TCA,"69,800,000"
Tuvalu,Oceania,Polynesia,TUV,"15,000,000"
Uganda,Africa,Eastern Africa,UGA,"45,700,000"
Ukraine,Europe,Eastern Europe,UKR,"9,900,000"
United Arab Emirates,Asia,Western Asia,ARE,"9,900,000"
United Kingdom of Great Britain and Northern Ireland,Europe,Northern Europe,GBR,"68,000,000"
United States of America,Americas,Northern America,USA,"59,700,000"
Uruguay,Americas,South America,URY,"5,100,000"
Uzbekistan,Asia,Central Asia,UZB,"6,000,000"
Vanuatu,Oceania,Melanesia,VUT,"5,900,000"
Venezuela (Bolivarian Republic of),Americas,South America,VEN,"4,900,000"
Viet Nam,Asia,South-Eastern Asia,VNM,"97,000,000"
Virgin Islands (British),Americas,Caribbean,VGB,"5,800,000"
Virgin Islands (U.S.),Americas,Caribbean,VIR,"11,400,000"
Wallis and Futuna,Oceania,Polynesia,WLF,"15,900,000"
Western Sahara,Africa,Northern Africa,ESH,"597,000"
Yemen,Asia,Western Asia,YEM,"5,500,000"
Zambia,Africa,Eastern Africa,ZMB,"213,000,000"
Zimbabwe,Africa,Eastern Africa,ZWE,"19,100,000"

In [5]:
df_Continent = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Indexing\Creating an Index\WorldContinents.csv',
                encoding = 'ISO-8859-1', index_col = 'continent')

df_Continent

,sub_region,country,code_3,Unnamed: 4
continent,,,,
Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
Europe,Northern Europe,Åland Islands,ALA,"5,500,000"
Europe,Southern Europe,Albania,ALB,"3,300,000"
Africa,Northern Africa,Algeria,DZA,"9,500,000"
Oceania,Polynesia,American Samoa,ASM,"55,000"
Europe,Southern Europe,Andorra,AND,"77,000"
Africa,Middle Africa,Angola,AGO,"54,000,000"
Americas,Caribbean,Anguilla,AIA,"2,100,000"
Americas,Caribbean,Antigua and Barbuda,ATG,"98,000"
Americas,South America,Argentina,ARG,"45,000,000"
Asia,Western Asia,Armenia,ARM,"45,700,000"
Americas,Caribbean,Aruba,ABW,"11,600,000"
Oceania,Australia and New Zealand,Australia,AUS,"36,000,000"
Europe,Western Europe,Austria,AUT,"9,000,000"
Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
Americas,Caribbean,Bahamas,BHS,"7,500,000"
Asia,Western Asia,Bahrain,BHR,"1,900,000"
Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
Americas,Caribbean,Barbados,BRB,"44,000,000"
Europe,Eastern Europe,Belarus,BLR,"9,400,000"
Europe,Western Europe,Belgium,BEL,"12,000,000"
Americas,Central America,Belize,BLZ,"9,000,000"
Africa,Western Africa,Benin,BEN,"17,400,000"
Americas,Northern America,Bermuda,BMU,"64,000"
Asia,Southern Asia,Bhutan,BTN,"771,000"
Americas,South America,Bolivia (Plurinational State of),BOL,"12,900,000"
Americas,Caribbean,"Bonaire, Sint Eustatius and Saba",BES,"4,300,000"
Europe,Southern Europe,Bosnia and Herzegovina,BIH,"5,000,000"
Africa,Southern Africa,Botswana,BWA,"29,000,000"
Americas,South America,Brazil,BRA,"32,700,000"
Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
Europe,Eastern Europe,Bulgaria,BGR,"6,900,000"
Africa,Western Africa,Burkina Faso,BFA,"31,000,000"
Africa,Eastern Africa,Burundi,BDI,"128,000,000"
Africa,Western Africa,Cabo Verde,CPV,"556,000"
Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
Africa,Middle Africa,Cameroon,CMR,"38,000,000"
Americas,Northern America,Canada,CAN,"60,000,000"
Americas,Caribbean,Cayman Islands,CYM,"66,000"
Africa,Middle Africa,Central African Republic,CAF,"84,000,000"
Africa,Middle Africa,Chad,TCD,"2,100,000"
Americas,South America,Chile,CHL,"25,000,000"
Asia,Eastern Asia,China,CHN,"1,412,000,000"
Americas,South America,Colombia,COL,"51,000,000"
Africa,Eastern Africa,Comoros,COM,"870,000"
Africa,Middle Africa,Congo,COG,"5,500,000"
Africa,Middle Africa,Congo (Democratic Republic of the),COD,"89,000,000"
Oceania,Polynesia,Cook Islands,COK,"206,000,000"
Americas,Central America,Costa Rica,CRI,"5,100,000"
Africa,Western Africa,Côte d'Ivoire,CIV,"38,000,000"
Europe,Southern Europe,Croatia,HRV,"7,900,000"
Americas,Caribbean,Cuba,CUB,"110,000,000"
Americas,Caribbean,Curaçao,CUW,"2,600,000"
Asia,Western Asia,Cyprus,CYP,"1,200,000"
Europe,Eastern Europe,Czech Republic,CZE,"102,000,000"
Europe,Northern Europe,Denmark,DNK,"5,800,000"
Africa,Eastern Africa,Djibouti,DJI,"988,000"
Americas,Caribbean,Dominica,DMA,"72,000"
Americas,Caribbean,Dominican Republic,DOM,"11,200,000"
Americas,South America,Ecuador,ECU,"2,900,000"
Africa,Northern Africa,Egypt,EGY,"11,300,000"
Americas,Central America,El Salvador,SLV,"6,500,000"
Africa,Middle Africa,Equatorial Guinea,GNQ,"1,700,000"
Africa,Eastern Africa,Eritrea,ERI,"5,100,000"
Europe,Northern Europe,Estonia,EST,"1,300,000"
Africa,Eastern Africa,Ethiopia,ETH,"16,700,000"
Americas,South America,Falkland Islands (Malvinas),FLK,"5,500,000"
Europe,Northern Europe,Faroe Islands,FRO,"49,000"
Oceania,Melanesia,Fiji,FJI,"896,000"
Europe,Northern Europe,Finland,FIN,"5,500,000"
Europe,Western Europe,France,FRA,"67,000,000"
Americas,South America,French Guiana,GUF,"45,000,000"
Oceania,Polynesia,French Polynesia,PYF,"40,000,000"
Africa,Middle Africa,Gabon,GAB,"28,000,000"
Africa,Western Africa,Gambia,GMB,"3,000,000"
Asia,Western Asia,Georgia,GEO,"5,400,000"
Europe,Western Europe,Germany,DEU,"83,200,000"
Africa,Western Africa,Ghana,GHA,"51,000,000"
Europe,Southern Europe,Gibraltar,GIB,"6,500,000"
Europe,Southern Europe,Greece,GRC,"10,800,000"
Americas,Northern America,Greenland,GRL,"56,000"
Americas,Caribbean,Grenada,GRD,"16,700,000"
Americas,Caribbean,Guadeloupe,GLP,"9,000,000"
Oceania,Micronesia,Guam,GUM,"2,800,000"
Americas,Central America,Guatemala,GTM,"21,000,000"
Europe,Northern Europe,Guernsey,GGY,"63,000"
Africa,Western Africa,Guinea,GIN,"18,700,000"
Africa,Western Africa,Guinea-Bissau,GNB,"10,000,000"
Americas,South America,Guyana,GUY,"787,000"
Americas,Caribbean,Haiti,HTI,"114,000,000"
Europe,Southern Europe,Holy See,VAT,800
Americas,Central America,Honduras,HND,"10,000,000"
Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
Europe,Eastern Europe,Hungary,HUN,"9,600,000"
Europe,Northern Europe,Iceland,ISL,"6,900,000"
Asia,Southern Asia,India,IND,"1,400,000,000"
Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
Asia,Western Asia,Iraq,IRQ,"89,000,000"
Europe,Northern Europe,Ireland,IRL,"5,000,000"
Europe,Northern Europe,Isle of Man,IMN,"85,000"
Asia,Western Asia,Israel,ISR,"9,300,000"
Europe,Southern Europe,Italy,ITA,"60,000,000"
Americas,Caribbean,Jamaica,JAM,"3,700,000"
Asia,Eastern Asia,Japan,JPN,"18,000,000"
Europe,Northern Europe,Jersey,JEY,"11,800,000"
Asia,Western Asia,Jordan,JOR,"10,300,000"
Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
Africa,Eastern Africa,Kenya,KEN,"53,800,000"
Oceania,Micronesia,Kiribati,KIR,"17,600,000"
Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
Asia,Western Asia,Kuwait,KWT,"8,300,000"
Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
Europe,Northern Europe,Latvia,LVA,"10,000,000"
Asia,Western Asia,Lebanon,LBN,"6,800,000"
Africa,Southern Africa,Lesotho,LSO,"27,700,000"
Africa,Western Africa,Liberia,LBR,"5,000,000"
Africa,Northern Africa,Libya,LBY,"6,900,000"
Europe,Western Europe,Liechtenstein,LIE,"68,000,000"
Europe,Northern Europe,Lithuania,LTU,"3,500,000"
Europe,Western Europe,Luxembourg,LUX,"633,000"
Asia,Eastern Asia,Macao,MAC,"650,000"
Europe,Southern Europe,Macedonia (the former Yugoslav Republic of),MKD,"26,000,000"
Africa,Eastern Africa,Madagascar,MDG,"4,300,000"
Africa,Eastern Africa,Malawi,MWI,"25,800,000"
Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
Asia,Southern Asia,Maldives,MDV,"540,000"
Africa,Western Africa,Mali,MLI,"30,000,000"
Europe,Southern Europe,Malta,MLT,"97,000,000"
Oceania,Micronesia,Marshall Islands,MHL,"59,000"
Americas,Caribbean,Martinique,MTQ,"6,900,000"
Africa,Western Africa,Mauritania,MRT,"83,200,000"
Africa,Eastern Africa,Mauritius,MUS,"1,300,000"
Africa,Eastern Africa,Mayotte,MYT,"4,800,000"
Americas,Central America,Mexico,MEX,"18,400,000"
Oceania,Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
Europe,Eastern Europe,Moldova (Republic of),MDA,"3,300,000"
Europe,Western Europe,Monaco,MCO,"7,100,000"
Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
Europe,Southern Europe,Montenegro,MNE,"622,000"
Americas,Caribbean,Montserrat,MSR,"5,000"
Africa,Northern Africa,Morocco,MAR,"6,800,000"
Africa,Eastern Africa,Mozambique,MOZ,"51,600,000"
Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
Africa,Southern Africa,Namibia,NAM,"3,200,000"
Oceania,Micronesia,Nauru,NRU,"144,000,000"
Asia,Southern Asia,Nepal,NPL,"44,000,000"
Europe,Western Europe,Netherlands,NLD,"2,800,000"
Oceania,Melanesia,New Caledonia,NCL,"44,000,000"
Oceania,Australia and New Zealand,New Zealand,NZL,"84,000,000"
Americas,Central America,Nicaragua,NIC,"6,600,000"
Africa,Western Africa,Niger,NER,"35,000,000"
Africa,Western Africa,Nigeria,NGA,"31,000,000"
Oceania,Polynesia,Niue,NIU,"2,400,000"
Oceania,Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
Oceania,Micronesia,Northern Mariana Islands,MNP,"58,000"
Europe,Northern Europe,Norway,NOR,"5,400,000"
Asia,Western Asia,Oman,OMN,"5,000,000"
Asia,Southern Asia,Pakistan,PAK,"331,000,000"
Oceania,Micronesia,Palau,PLW,"220,000,000"
Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
Americas,Central America,Panama,PAN,"8,700,000"
Oceania,Melanesia,Papua New Guinea,PNG,"9,000,000"
Americas,South America,Paraguay,PRY,"7,100,000"
Americas,South America,Peru,PER,"59,000,000"
Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
Oceania,Polynesia,Pitcairn,PCN,"50,000,000"
Europe,Eastern Europe,Poland,POL,"67,000,000"
Europe,Southern Europe,Portugal,PRT,"10,400,000"
Americas,Caribbean,Puerto Rico,PRI,"47,000,000"
Asia,Western Asia,Qatar,QAT,"3,500,000"
Africa,Eastern Africa,Réunion,REU,"859,000"
Europe,Eastern Europe,Romania,ROU,"24,000,000"
Europe,Eastern Europe,Russian Federation,RUS,"19,000,000"
Africa,Eastern Africa,Rwanda,RWA,"17,500,000"
Americas,Caribbean,Saint Barthélemy,BLM,"9,900"
Africa,Western Africa,"Saint Helena, Ascension and Tristan da Cunha",SHN,"6,000"
Americas,Caribbean,Saint Kitts and Nevis,KNA,"53,000"
Americas,Caribbean,Saint Lucia,LCA,"23,800,000"
Americas,Caribbean,Saint Martin (French part),MAF,"7,300,000"
Americas,Northern America,Saint Pierre and Miquelon,SPM,"5,700"
Americas,Caribbean,Saint Vincent and the Grenadines,VCT,"16,400,000"
Oceania,Polynesia,Samoa,WSM,"26,000,000"
Europe,Southern Europe,San Marino,SMR,"6,600,000"
Africa,Middle Africa,Sao Tome and Principe,STP,"33,000,000"
Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
Africa,Western Africa,Senegal,SEN,"2,300,000"
Europe,Southern Europe,Serbia,SRB,"6,900,000"
Africa,Eastern Africa,Seychelles,SYC,"98,000"
Africa,Western Africa,Sierra Leone,SLE,"7,900,000"
Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
Americas,Caribbean,Sint Maarten (Dutch part),SXM,"9,300,000"
Europe,Eastern Europe,Slovakia,SVK,"5,500,000"
Europe,Southern Europe,Slovenia,SVN,"276,000,000"
Oceania,Melanesia,Solomon Islands,SLB,"686,000"
Africa,Eastern Africa,Somalia,SOM,"19,100,000"
Africa,Southern Africa,South Africa,ZAF,"59,000,000"
Africa,Eastern Africa,South Sudan,SSD,"11,900,000"
Europe,Southern Europe,Spain,ESP,"47,000,000"
Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
Africa,Northern Africa,Sudan,SDN,"9,600,000"
Americas,South America,Suriname,SUR,"591,000"
Europe,Northern Europe,Svalbard and Jan Mayen,SJM,"4,000,000"
Africa,Southern Africa,Swaziland,SWZ,"1,200,000"
Europe,Northern Europe,Sweden,SWE,"10,700,000"
Europe,Western Europe,Switzerland,CHE,"8,700,000"
Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
Asia,Central Asia,Tajikistan,TJK,"9,500,000"
Africa,Eastern Africa,"Tanzania, United Republic of",TZA,"59,700,000"
Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
Africa,Western Africa,Togo,TGO,"8,300,000"
Oceania,Polynesia,Tokelau,TKL,"2,000,000"
Oceania,Polynesia,Tonga,TON,"11,500,000"
Americas,Caribbean,Trinidad and Tobago,TTO,"1,900,000"
Africa,Northern Africa,Tunisia,TUN,"125,000,000"
Asia,Western Asia,Turkey,TUR,"84,000,000"
Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
Americas,Caribbean,Turks and Caicos Islands,TCA,"69,800,000"
Oceania,Polynesia,Tuvalu,TUV,"15,000,000"
Africa,Eastern Africa,Uganda,UGA,"45,700,000"
Europe,Eastern Europe,Ukraine,UKR,"9,900,000"
Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
Europe,Northern Europe,United Kingdom of Great Britain and Northern I...,GBR,"68,000,000"
Americas,Northern America,United States of America,USA,"59,700,000"
Americas,South America,Uruguay,URY,"5,100,000"
Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
Oceania,Melanesia,Vanuatu,VUT,"5,900,000"
Americas,South America,Venezuela (Bolivarian Republic of),VEN,"4,900,000"
Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
Americas,Caribbean,Virgin Islands (British),VGB,"5,800,000"
Americas,Caribbean,Virgin Islands (U.S.),VIR,"11,400,000"
Oceania,Polynesia,Wallis and Futuna,WLF,"15,900,000"
Africa,Northern Africa,Western Sahara,ESH,"597,000"
Asia,Western Asia,Yemen,YEM,"5,500,000"
Africa,Eastern Africa,Zambia,ZMB,"213,000,000"
Africa,Eastern Africa,Zimbabwe,ZWE,"19,100,000"

In [6]:
df_world.loc['Albania']

continent              Europe
sub_region    Southern Europe
code_3                    ALB
Unnamed: 4         3,300,000
Name: Albania, dtype: object

In [7]:
df_Continent.loc['Asia']

,sub_region,country,code_3,Unnamed: 4
continent,,,,
Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
Asia,Western Asia,Armenia,ARM,"45,700,000"
Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
Asia,Western Asia,Bahrain,BHR,"1,900,000"
Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
Asia,Southern Asia,Bhutan,BTN,"771,000"
Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
Asia,Eastern Asia,China,CHN,"1,412,000,000"
Asia,Western Asia,Cyprus,CYP,"1,200,000"
Asia,Western Asia,Georgia,GEO,"5,400,000"
Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
Asia,Southern Asia,India,IND,"1,400,000,000"
Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
Asia,Western Asia,Iraq,IRQ,"89,000,000"
Asia,Western Asia,Israel,ISR,"9,300,000"
Asia,Eastern Asia,Japan,JPN,"18,000,000"
Asia,Western Asia,Jordan,JOR,"10,300,000"
Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
Asia,Western Asia,Kuwait,KWT,"8,300,000"
Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
Asia,Western Asia,Lebanon,LBN,"6,800,000"
Asia,Eastern Asia,Macao,MAC,"650,000"
Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
Asia,Southern Asia,Maldives,MDV,"540,000"
Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
Asia,Southern Asia,Nepal,NPL,"44,000,000"
Asia,Western Asia,Oman,OMN,"5,000,000"
Asia,Southern Asia,Pakistan,PAK,"331,000,000"
Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
Asia,Western Asia,Qatar,QAT,"3,500,000"
Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
Asia,Central Asia,Tajikistan,TJK,"9,500,000"
Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
Asia,Western Asia,Turkey,TUR,"84,000,000"
Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
Asia,Western Asia,Yemen,YEM,"5,500,000"

In [10]:
df.set_index('country', inplace = True)

In [11]:
df

,continent,sub_region,code_3,Unnamed: 4
country,,,,
Afghanistan,Asia,Southern Asia,AFG,"6,900,000"
Åland Islands,Europe,Northern Europe,ALA,"5,500,000"
Albania,Europe,Southern Europe,ALB,"3,300,000"
Algeria,Africa,Northern Africa,DZA,"9,500,000"
American Samoa,Oceania,Polynesia,ASM,"55,000"
Andorra,Europe,Southern Europe,AND,"77,000"
Angola,Africa,Middle Africa,AGO,"54,000,000"
Anguilla,Americas,Caribbean,AIA,"2,100,000"
Antigua and Barbuda,Americas,Caribbean,ATG,"98,000"
Argentina,Americas,South America,ARG,"45,000,000"
Armenia,Asia,Western Asia,ARM,"45,700,000"
Aruba,Americas,Caribbean,ABW,"11,600,000"
Australia,Oceania,Australia and New Zealand,AUS,"36,000,000"
Austria,Europe,Western Europe,AUT,"9,000,000"
Azerbaijan,Asia,Western Asia,AZE,"10,000,000"
Bahamas,Americas,Caribbean,BHS,"7,500,000"
Bahrain,Asia,Western Asia,BHR,"1,900,000"
Bangladesh,Asia,Southern Asia,BGD,"2,500,000"
Barbados,Americas,Caribbean,BRB,"44,000,000"
Belarus,Europe,Eastern Europe,BLR,"9,400,000"
Belgium,Europe,Western Europe,BEL,"12,000,000"
Belize,Americas,Central America,BLZ,"9,000,000"
Benin,Africa,Western Africa,BEN,"17,400,000"
Bermuda,Americas,Northern America,BMU,"64,000"
Bhutan,Asia,Southern Asia,BTN,"771,000"
Bolivia (Plurinational State of),Americas,South America,BOL,"12,900,000"
"Bonaire, Sint Eustatius and Saba",Americas,Caribbean,BES,"4,300,000"
Bosnia and Herzegovina,Europe,Southern Europe,BIH,"5,000,000"
Botswana,Africa,Southern Africa,BWA,"29,000,000"
Brazil,Americas,South America,BRA,"32,700,000"
Brunei Darussalam,Asia,South-Eastern Asia,BRN,"9,400,000"
Bulgaria,Europe,Eastern Europe,BGR,"6,900,000"
Burkina Faso,Africa,Western Africa,BFA,"31,000,000"
Burundi,Africa,Eastern Africa,BDI,"128,000,000"
Cabo Verde,Africa,Western Africa,CPV,"556,000"
Cambodia,Asia,South-Eastern Asia,KHM,"2,200,000"
Cameroon,Africa,Middle Africa,CMR,"38,000,000"
Canada,Americas,Northern America,CAN,"60,000,000"
Cayman Islands,Americas,Caribbean,CYM,"66,000"
Central African Republic,Africa,Middle Africa,CAF,"84,000,000"
Chad,Africa,Middle Africa,TCD,"2,100,000"
Chile,Americas,South America,CHL,"25,000,000"
China,Asia,Eastern Asia,CHN,"1,412,000,000"
Colombia,Americas,South America,COL,"51,000,000"
Comoros,Africa,Eastern Africa,COM,"870,000"
Congo,Africa,Middle Africa,COG,"5,500,000"
Congo (Democratic Republic of the),Africa,Middle Africa,COD,"89,000,000"
Cook Islands,Oceania,Polynesia,COK,"206,000,000"
Costa Rica,Americas,Central America,CRI,"5,100,000"
Côte d'Ivoire,Africa,Western Africa,CIV,"38,000,000"
Croatia,Europe,Southern Europe,HRV,"7,900,000"
Cuba,Americas,Caribbean,CUB,"110,000,000"
Curaçao,Americas,Caribbean,CUW,"2,600,000"
Cyprus,Asia,Western Asia,CYP,"1,200,000"
Czech Republic,Europe,Eastern Europe,CZE,"102,000,000"
Denmark,Europe,Northern Europe,DNK,"5,800,000"
Djibouti,Africa,Eastern Africa,DJI,"988,000"
Dominica,Americas,Caribbean,DMA,"72,000"
Dominican Republic,Americas,Caribbean,DOM,"11,200,000"
Ecuador,Americas,South America,ECU,"2,900,000"
Egypt,Africa,Northern Africa,EGY,"11,300,000"
El Salvador,Americas,Central America,SLV,"6,500,000"
Equatorial Guinea,Africa,Middle Africa,GNQ,"1,700,000"
Eritrea,Africa,Eastern Africa,ERI,"5,100,000"
Estonia,Europe,Northern Europe,EST,"1,300,000"
Ethiopia,Africa,Eastern Africa,ETH,"16,700,000"
Falkland Islands (Malvinas),Americas,South America,FLK,"5,500,000"
Faroe Islands,Europe,Northern Europe,FRO,"49,000"
Fiji,Oceania,Melanesia,FJI,"896,000"
Finland,Europe,Northern Europe,FIN,"5,500,000"
France,Europe,Western Europe,FRA,"67,000,000"
French Guiana,Americas,South America,GUF,"45,000,000"
French Polynesia,Oceania,Polynesia,PYF,"40,000,000"
Gabon,Africa,Middle Africa,GAB,"28,000,000"
Gambia,Africa,Western Africa,GMB,"3,000,000"
Georgia,Asia,Western Asia,GEO,"5,400,000"
Germany,Europe,Western Europe,DEU,"83,200,000"
Ghana,Africa,Western Africa,GHA,"51,000,000"
Gibraltar,Europe,Southern Europe,GIB,"6,500,000"
Greece,Europe,Southern Europe,GRC,"10,800,000"
Greenland,Americas,Northern America,GRL,"56,000"
Grenada,Americas,Caribbean,GRD,"16,700,000"
Guadeloupe,Americas,Caribbean,GLP,"9,000,000"
Guam,Oceania,Micronesia,GUM,"2,800,000"
Guatemala,Americas,Central America,GTM,"21,000,000"
Guernsey,Europe,Northern Europe,GGY,"63,000"
Guinea,Africa,Western Africa,GIN,"18,700,000"
Guinea-Bissau,Africa,Western Africa,GNB,"10,000,000"
Guyana,Americas,South America,GUY,"787,000"
Haiti,Americas,Caribbean,HTI,"114,000,000"
Holy See,Europe,Southern Europe,VAT,800
Honduras,Americas,Central America,HND,"10,000,000"
Hong Kong,Asia,Eastern Asia,HKG,"7,500,000"
Hungary,Europe,Eastern Europe,HUN,"9,600,000"
Iceland,Europe,Northern Europe,ISL,"6,900,000"
India,Asia,Southern Asia,IND,"1,400,000,000"
Indonesia,Asia,South-Eastern Asia,IDN,"4,600,000"
Iran (Islamic Republic of),Asia,Southern Asia,IRN,"84,000,000"
Iraq,Asia,Western Asia,IRQ,"89,000,000"
Ireland,Europe,Northern Europe,IRL,"5,000,000"
Isle of Man,Europe,Northern Europe,IMN,"85,000"
Israel,Asia,Western Asia,ISR,"9,300,000"
Italy,Europe,Southern Europe,ITA,"60,000,000"
Jamaica,Americas,Caribbean,JAM,"3,700,000"
Japan,Asia,Eastern Asia,JPN,"18,000,000"
Jersey,Europe,Northern Europe,JEY,"11,800,000"
Jordan,Asia,Western Asia,JOR,"10,300,000"
Kazakhstan,Asia,Central Asia,KAZ,"22,000,000"
Kenya,Africa,Eastern Africa,KEN,"53,800,000"
Kiribati,Oceania,Micronesia,KIR,"17,600,000"
Korea (Democratic People's Republic of),Asia,Eastern Asia,PRK,"38,000,000"
Korea (Republic of),Asia,Eastern Asia,KOR,"51,600,000"
Kuwait,Asia,Western Asia,KWT,"8,300,000"
Kyrgyzstan,Asia,Central Asia,KGZ,"6,600,000"
Lao People's Democratic Republic,Asia,South-Eastern Asia,LAO,"7,300,000"
Latvia,Europe,Northern Europe,LVA,"10,000,000"
Lebanon,Asia,Western Asia,LBN,"6,800,000"
Lesotho,Africa,Southern Africa,LSO,"27,700,000"
Liberia,Africa,Western Africa,LBR,"5,000,000"
Libya,Africa,Northern Africa,LBY,"6,900,000"
Liechtenstein,Europe,Western Europe,LIE,"68,000,000"
Lithuania,Europe,Northern Europe,LTU,"3,500,000"
Luxembourg,Europe,Western Europe,LUX,"633,000"
Macao,Asia,Eastern Asia,MAC,"650,000"
Macedonia (the former Yugoslav Republic of),Europe,Southern Europe,MKD,"26,000,000"
Madagascar,Africa,Eastern Africa,MDG,"4,300,000"
Malawi,Africa,Eastern Africa,MWI,"25,800,000"
Malaysia,Asia,South-Eastern Asia,MYS,"53,800,000"
Maldives,Asia,Southern Asia,MDV,"540,000"
Mali,Africa,Western Africa,MLI,"30,000,000"
Malta,Europe,Southern Europe,MLT,"97,000,000"
Marshall Islands,Oceania,Micronesia,MHL,"59,000"
Martinique,Americas,Caribbean,MTQ,"6,900,000"
Mauritania,Africa,Western Africa,MRT,"83,200,000"
Mauritius,Africa,Eastern Africa,MUS,"1,300,000"
Mayotte,Africa,Eastern Africa,MYT,"4,800,000"
Mexico,Americas,Central America,MEX,"18,400,000"
Micronesia (Federated States of),Oceania,Micronesia,FSM,"164,000,000"
Moldova (Republic of),Europe,Eastern Europe,MDA,"3,300,000"
Monaco,Europe,Western Europe,MCO,"7,100,000"
Mongolia,Asia,Eastern Asia,MNG,"5,000,000"
Montenegro,Europe,Southern Europe,MNE,"622,000"
Montserrat,Americas,Caribbean,MSR,"5,000"
Morocco,Africa,Northern Africa,MAR,"6,800,000"
Mozambique,Africa,Eastern Africa,MOZ,"51,600,000"
Myanmar,Asia,South-Eastern Asia,MMR,"54,000,000"
Namibia,Africa,Southern Africa,NAM,"3,200,000"
Nauru,Oceania,Micronesia,NRU,"144,000,000"
Nepal,Asia,Southern Asia,NPL,"44,000,000"
Netherlands,Europe,Western Europe,NLD,"2,800,000"
New Caledonia,Oceania,Melanesia,NCL,"44,000,000"
New Zealand,Oceania,Australia and New Zealand,NZL,"84,000,000"
Nicaragua,Americas,Central America,NIC,"6,600,000"
Niger,Africa,Western Africa,NER,"35,000,000"
Nigeria,Africa,Western Africa,NGA,"31,000,000"
Niue,Oceania,Polynesia,NIU,"2,400,000"
Norfolk Island,Oceania,Australia and New Zealand,NFK,"20,300,000"
Northern Mariana Islands,Oceania,Micronesia,MNP,"58,000"
Norway,Europe,Northern Europe,NOR,"5,400,000"
Oman,Asia,Western Asia,OMN,"5,000,000"
Pakistan,Asia,Southern Asia,PAK,"331,000,000"
Palau,Oceania,Micronesia,PLW,"220,000,000"
"Palestine, State of",Asia,Western Asia,PSE,"5,100,000"
Panama,Americas,Central America,PAN,"8,700,000"
Papua New Guinea,Oceania,Melanesia,PNG,"9,000,000"
Paraguay,Americas,South America,PRY,"7,100,000"
Peru,Americas,South America,PER,"59,000,000"
Philippines,Asia,South-Eastern Asia,PHL,"13,100,000"
Pitcairn,Oceania,Polynesia,PCN,"50,000,000"
Poland,Europe,Eastern Europe,POL,"67,000,000"
Portugal,Europe,Southern Europe,PRT,"10,400,000"
Puerto Rico,Americas,Caribbean,PRI,"47,000,000"
Qatar,Asia,Western Asia,QAT,"3,500,000"
Réunion,Africa,Eastern Africa,REU,"859,000"
Romania,Europe,Eastern Europe,ROU,"24,000,000"
Russian Federation,Europe,Eastern Europe,RUS,"19,000,000"
Rwanda,Africa,Eastern Africa,RWA,"17,500,000"
Saint Barthélemy,Americas,Caribbean,BLM,"9,900"
"Saint Helena, Ascension and Tristan da Cunha",Africa,Western Africa,SHN,"6,000"
Saint Kitts and Nevis,Americas,Caribbean,KNA,"53,000"
Saint Lucia,Americas,Caribbean,LCA,"23,800,000"
Saint Martin (French part),Americas,Caribbean,MAF,"7,300,000"
Saint Pierre and Miquelon,Americas,Northern America,SPM,"5,700"
Saint Vincent and the Grenadines,Americas,Caribbean,VCT,"16,400,000"
Samoa,Oceania,Polynesia,WSM,"26,000,000"
San Marino,Europe,Southern Europe,SMR,"6,600,000"
Sao Tome and Principe,Africa,Middle Africa,STP,"33,000,000"
Saudi Arabia,Asia,Western Asia,SAU,"6,600,000"
Senegal,Africa,Western Africa,SEN,"2,300,000"
Serbia,Europe,Southern Europe,SRB,"6,900,000"
Seychelles,Africa,Eastern Africa,SYC,"98,000"
Sierra Leone,Africa,Western Africa,SLE,"7,900,000"
Singapore,Asia,South-Eastern Asia,SGP,"5,900,000"
Sint Maarten (Dutch part),Americas,Caribbean,SXM,"9,300,000"
Slovakia,Europe,Eastern Europe,SVK,"5,500,000"
Slovenia,Europe,Southern Europe,SVN,"276,000,000"
Solomon Islands,Oceania,Melanesia,SLB,"686,000"
Somalia,Africa,Eastern Africa,SOM,"19,100,000"
South Africa,Africa,Southern Africa,ZAF,"59,000,000"
South Sudan,Africa,Eastern Africa,SSD,"11,900,000"
Spain,Europe,Southern Europe,ESP,"47,000,000"
Sri Lanka,Asia,Southern Asia,LKA,"33,000,000"
Sudan,Africa,Northern Africa,SDN,"9,600,000"
Suriname,Americas,South America,SUR,"591,000"
Svalbard and Jan Mayen,Europe,Northern Europe,SJM,"4,000,000"
Swaziland,Africa,Southern Africa,SWZ,"1,200,000"
Sweden,Europe,Northern Europe,SWE,"10,700,000"
Switzerland,Europe,Western Europe,CHE,"8,700,000"
Syrian Arab Republic,Asia,Western Asia,SYR,"2,800,000"
"Taiwan, Province of China",Asia,Eastern Asia,TWN,"34,000,000"
Tajikistan,Asia,Central Asia,TJK,"9,500,000"
"Tanzania, United Republic of",Africa,Eastern Africa,TZA,"59,700,000"
Thailand,Asia,South-Eastern Asia,THA,"69,800,000"
Timor-Leste,Asia,South-Eastern Asia,TLS,"1,300,000"
Togo,Africa,Western Africa,TGO,"8,300,000"
Tokelau,Oceania,Polynesia,TKL,"2,000,000"
Tonga,Oceania,Polynesia,TON,"11,500,000"
Trinidad and Tobago,Americas,Caribbean,TTO,"1,900,000"
Tunisia,Africa,Northern Africa,TUN,"125,000,000"
Turkey,Asia,Western Asia,TUR,"84,000,000"
Turkmenistan,Asia,Central Asia,TKM,"6,000,000"
Turks and Caicos Islands,Americas,Caribbean,TCA,"69,800,000"
Tuvalu,Oceania,Polynesia,TUV,"15,000,000"
Uganda,Africa,Eastern Africa,UGA,"45,700,000"
Ukraine,Europe,Eastern Europe,UKR,"9,900,000"
United Arab Emirates,Asia,Western Asia,ARE,"9,900,000"
United Kingdom of Great Britain and Northern Ireland,Europe,Northern Europe,GBR,"68,000,000"
United States of America,Americas,Northern America,USA,"59,700,000"
Uruguay,Americas,South America,URY,"5,100,000"
Uzbekistan,Asia,Central Asia,UZB,"6,000,000"
Vanuatu,Oceania,Melanesia,VUT,"5,900,000"
Venezuela (Bolivarian Republic of),Americas,South America,VEN,"4,900,000"
Viet Nam,Asia,South-Eastern Asia,VNM,"97,000,000"
Virgin Islands (British),Americas,Caribbean,VGB,"5,800,000"
Virgin Islands (U.S.),Americas,Caribbean,VIR,"11,400,000"
Wallis and Futuna,Oceania,Polynesia,WLF,"15,900,000"
Western Sahara,Africa,Northern Africa,ESH,"597,000"
Yemen,Asia,Western Asia,YEM,"5,500,000"
Zambia,Africa,Eastern Africa,ZMB,"213,000,000"
Zimbabwe,Africa,Eastern Africa,ZWE,"19,100,000"

In [12]:
df.reset_index(inplace = True)

In [13]:
df

,country,continent,sub_region,code_3,Unnamed: 4
0,Afghanistan,Asia,Southern Asia,AFG,"6,900,000"
1,Åland Islands,Europe,Northern Europe,ALA,"5,500,000"
2,Albania,Europe,Southern Europe,ALB,"3,300,000"
3,Algeria,Africa,Northern Africa,DZA,"9,500,000"
4,American Samoa,Oceania,Polynesia,ASM,"55,000"
5,Andorra,Europe,Southern Europe,AND,"77,000"
6,Angola,Africa,Middle Africa,AGO,"54,000,000"
7,Anguilla,Americas,Caribbean,AIA,"2,100,000"
8,Antigua and Barbuda,Americas,Caribbean,ATG,"98,000"
9,Argentina,Americas,South America,ARG,"45,000,000"
10,Armenia,Asia,Western Asia,ARM,"45,700,000"
11,Aruba,Americas,Caribbean,ABW,"11,600,000"
12,Australia,Oceania,Australia and New Zealand,AUS,"36,000,000"
13,Austria,Europe,Western Europe,AUT,"9,000,000"
14,Azerbaijan,Asia,Western Asia,AZE,"10,000,000"
15,Bahamas,Americas,Caribbean,BHS,"7,500,000"
16,Bahrain,Asia,Western Asia,BHR,"1,900,000"
17,Bangladesh,Asia,Southern Asia,BGD,"2,500,000"
18,Barbados,Americas,Caribbean,BRB,"44,000,000"
19,Belarus,Europe,Eastern Europe,BLR,"9,400,000"
20,Belgium,Europe,Western Europe,BEL,"12,000,000"
21,Belize,Americas,Central America,BLZ,"9,000,000"
22,Benin,Africa,Western Africa,BEN,"17,400,000"
23,Bermuda,Americas,Northern America,BMU,"64,000"
24,Bhutan,Asia,Southern Asia,BTN,"771,000"
25,Bolivia (Plurinational State of),Americas,South America,BOL,"12,900,000"
26,"Bonaire, Sint Eustatius and Saba",Americas,Caribbean,BES,"4,300,000"
27,Bosnia and Herzegovina,Europe,Southern Europe,BIH,"5,000,000"
28,Botswana,Africa,Southern Africa,BWA,"29,000,000"
29,Brazil,Americas,South America,BRA,"32,700,000"
30,Brunei Darussalam,Asia,South-Eastern Asia,BRN,"9,400,000"
31,Bulgaria,Europe,Eastern Europe,BGR,"6,900,000"
32,Burkina Faso,Africa,Western Africa,BFA,"31,000,000"
33,Burundi,Africa,Eastern Africa,BDI,"128,000,000"
34,Cabo Verde,Africa,Western Africa,CPV,"556,000"
35,Cambodia,Asia,South-Eastern Asia,KHM,"2,200,000"
36,Cameroon,Africa,Middle Africa,CMR,"38,000,000"
37,Canada,Americas,Northern America,CAN,"60,000,000"
38,Cayman Islands,Americas,Caribbean,CYM,"66,000"
39,Central African Republic,Africa,Middle Africa,CAF,"84,000,000"
40,Chad,Africa,Middle Africa,TCD,"2,100,000"
41,Chile,Americas,South America,CHL,"25,000,000"
42,China,Asia,Eastern Asia,CHN,"1,412,000,000"
43,Colombia,Americas,South America,COL,"51,000,000"
44,Comoros,Africa,Eastern Africa,COM,"870,000"
45,Congo,Africa,Middle Africa,COG,"5,500,000"
46,Congo (Democratic Republic of the),Africa,Middle Africa,COD,"89,000,000"
47,Cook Islands,Oceania,Polynesia,COK,"206,000,000"
48,Costa Rica,Americas,Central America,CRI,"5,100,000"
49,Côte d'Ivoire,Africa,Western Africa,CIV,"38,000,000"
50,Croatia,Europe,Southern Europe,HRV,"7,900,000"
51,Cuba,Americas,Caribbean,CUB,"110,000,000"
52,Curaçao,Americas,Caribbean,CUW,"2,600,000"
53,Cyprus,Asia,Western Asia,CYP,"1,200,000"
54,Czech Republic,Europe,Eastern Europe,CZE,"102,000,000"
55,Denmark,Europe,Northern Europe,DNK,"5,800,000"
56,Djibouti,Africa,Eastern Africa,DJI,"988,000"
57,Dominica,Americas,Caribbean,DMA,"72,000"
58,Dominican Republic,Americas,Caribbean,DOM,"11,200,000"
59,Ecuador,Americas,South America,ECU,"2,900,000"
60,Egypt,Africa,Northern Africa,EGY,"11,300,000"
61,El Salvador,Americas,Central America,SLV,"6,500,000"
62,Equatorial Guinea,Africa,Middle Africa,GNQ,"1,700,000"
63,Eritrea,Africa,Eastern Africa,ERI,"5,100,000"
64,Estonia,Europe,Northern Europe,EST,"1,300,000"
65,Ethiopia,Africa,Eastern Africa,ETH,"16,700,000"
66,Falkland Islands (Malvinas),Americas,South America,FLK,"5,500,000"
67,Faroe Islands,Europe,Northern Europe,FRO,"49,000"
68,Fiji,Oceania,Melanesia,FJI,"896,000"
69,Finland,Europe,Northern Europe,FIN,"5,500,000"
70,France,Europe,Western Europe,FRA,"67,000,000"
71,French Guiana,Americas,South America,GUF,"45,000,000"
72,French Polynesia,Oceania,Polynesia,PYF,"40,000,000"
73,Gabon,Africa,Middle Africa,GAB,"28,000,000"
74,Gambia,Africa,Western Africa,GMB,"3,000,000"
75,Georgia,Asia,Western Asia,GEO,"5,400,000"
76,Germany,Europe,Western Europe,DEU,"83,200,000"
77,Ghana,Africa,Western Africa,GHA,"51,000,000"
78,Gibraltar,Europe,Southern Europe,GIB,"6,500,000"
79,Greece,Europe,Southern Europe,GRC,"10,800,000"
80,Greenland,Americas,Northern America,GRL,"56,000"
81,Grenada,Americas,Caribbean,GRD,"16,700,000"
82,Guadeloupe,Americas,Caribbean,GLP,"9,000,000"
83,Guam,Oceania,Micronesia,GUM,"2,800,000"
84,Guatemala,Americas,Central America,GTM,"21,000,000"
85,Guernsey,Europe,Northern Europe,GGY,"63,000"
86,Guinea,Africa,Western Africa,GIN,"18,700,000"
87,Guinea-Bissau,Africa,Western Africa,GNB,"10,000,000"
88,Guyana,Americas,South America,GUY,"787,000"
89,Haiti,Americas,Caribbean,HTI,"114,000,000"
90,Holy See,Europe,Southern Europe,VAT,800
91,Honduras,Americas,Central America,HND,"10,000,000"
92,Hong Kong,Asia,Eastern Asia,HKG,"7,500,000"
93,Hungary,Europe,Eastern Europe,HUN,"9,600,000"
94,Iceland,Europe,Northern Europe,ISL,"6,900,000"
95,India,Asia,Southern Asia,IND,"1,400,000,000"
96,Indonesia,Asia,South-Eastern Asia,IDN,"4,600,000"
97,Iran (Islamic Republic of),Asia,Southern Asia,IRN,"84,000,000"
98,Iraq,Asia,Western Asia,IRQ,"89,000,000"
99,Ireland,Europe,Northern Europe,IRL,"5,000,000"
100,Isle of Man,Europe,Northern Europe,IMN,"85,000"
101,Israel,Asia,Western Asia,ISR,"9,300,000"
102,Italy,Europe,Southern Europe,ITA,"60,000,000"
103,Jamaica,Americas,Caribbean,JAM,"3,700,000"
104,Japan,Asia,Eastern Asia,JPN,"18,000,000"
105,Jersey,Europe,Northern Europe,JEY,"11,800,000"
106,Jordan,Asia,Western Asia,JOR,"10,300,000"
107,Kazakhstan,Asia,Central Asia,KAZ,"22,000,000"
108,Kenya,Africa,Eastern Africa,KEN,"53,800,000"
109,Kiribati,Oceania,Micronesia,KIR,"17,600,000"
110,Korea (Democratic People's Republic of),Asia,Eastern Asia,PRK,"38,000,000"
111,Korea (Republic of),Asia,Eastern Asia,KOR,"51,600,000"
112,Kuwait,Asia,Western Asia,KWT,"8,300,000"
113,Kyrgyzstan,Asia,Central Asia,KGZ,"6,600,000"
114,Lao People's Democratic Republic,Asia,South-Eastern Asia,LAO,"7,300,000"
115,Latvia,Europe,Northern Europe,LVA,"10,000,000"
116,Lebanon,Asia,Western Asia,LBN,"6,800,000"
117,Lesotho,Africa,Southern Africa,LSO,"27,700,000"
118,Liberia,Africa,Western Africa,LBR,"5,000,000"
119,Libya,Africa,Northern Africa,LBY,"6,900,000"
120,Liechtenstein,Europe,Western Europe,LIE,"68,000,000"
121,Lithuania,Europe,Northern Europe,LTU,"3,500,000"
122,Luxembourg,Europe,Western Europe,LUX,"633,000"
123,Macao,Asia,Eastern Asia,MAC,"650,000"
124,Macedonia (the former Yugoslav Republic of),Europe,Southern Europe,MKD,"26,000,000"
125,Madagascar,Africa,Eastern Africa,MDG,"4,300,000"
126,Malawi,Africa,Eastern Africa,MWI,"25,800,000"
127,Malaysia,Asia,South-Eastern Asia,MYS,"53,800,000"
128,Maldives,Asia,Southern Asia,MDV,"540,000"
129,Mali,Africa,Western Africa,MLI,"30,000,000"
130,Malta,Europe,Southern Europe,MLT,"97,000,000"
131,Marshall Islands,Oceania,Micronesia,MHL,"59,000"
132,Martinique,Americas,Caribbean,MTQ,"6,900,000"
133,Mauritania,Africa,Western Africa,MRT,"83,200,000"
134,Mauritius,Africa,Eastern Africa,MUS,"1,300,000"
135,Mayotte,Africa,Eastern Africa,MYT,"4,800,000"
136,Mexico,Americas,Central America,MEX,"18,400,000"
137,Micronesia (Federated States of),Oceania,Micronesia,FSM,"164,000,000"
138,Moldova (Republic of),Europe,Eastern Europe,MDA,"3,300,000"
139,Monaco,Europe,Western Europe,MCO,"7,100,000"
140,Mongolia,Asia,Eastern Asia,MNG,"5,000,000"
141,Montenegro,Europe,Southern Europe,MNE,"622,000"
142,Montserrat,Americas,Caribbean,MSR,"5,000"
143,Morocco,Africa,Northern Africa,MAR,"6,800,000"
144,Mozambique,Africa,Eastern Africa,MOZ,"51,600,000"
145,Myanmar,Asia,South-Eastern Asia,MMR,"54,000,000"
146,Namibia,Africa,Southern Africa,NAM,"3,200,000"
147,Nauru,Oceania,Micronesia,NRU,"144,000,000"
148,Nepal,Asia,Southern Asia,NPL,"44,000,000"
149,Netherlands,Europe,Western Europe,NLD,"2,800,000"
150,New Caledonia,Oceania,Melanesia,NCL,"44,000,000"
151,New Zealand,Oceania,Australia and New Zealand,NZL,"84,000,000"
152,Nicaragua,Americas,Central America,NIC,"6,600,000"
153,Niger,Africa,Western Africa,NER,"35,000,000"
154,Nigeria,Africa,Western Africa,NGA,"31,000,000"
155,Niue,Oceania,Polynesia,NIU,"2,400,000"
156,Norfolk Island,Oceania,Australia and New Zealand,NFK,"20,300,000"
157,Northern Mariana Islands,Oceania,Micronesia,MNP,"58,000"
158,Norway,Europe,Northern Europe,NOR,"5,400,000"
159,Oman,Asia,Western Asia,OMN,"5,000,000"
160,Pakistan,Asia,Southern Asia,PAK,"331,000,000"
161,Palau,Oceania,Micronesia,PLW,"220,000,000"
162,"Palestine, State of",Asia,Western Asia,PSE,"5,100,000"
163,Panama,Americas,Central America,PAN,"8,700,000"
164,Papua New Guinea,Oceania,Melanesia,PNG,"9,000,000"
165,Paraguay,Americas,South America,PRY,"7,100,000"
166,Peru,Americas,South America,PER,"59,000,000"
167,Philippines,Asia,South-Eastern Asia,PHL,"13,100,000"
168,Pitcairn,Oceania,Polynesia,PCN,"50,000,000"
169,Poland,Europe,Eastern Europe,POL,"67,000,000"
170,Portugal,Europe,Southern Europe,PRT,"10,400,000"
171,Puerto Rico,Americas,Caribbean,PRI,"47,000,000"
172,Qatar,Asia,Western Asia,QAT,"3,500,000"
173,Réunion,Africa,Eastern Africa,REU,"859,000"
174,Romania,Europe,Eastern Europe,ROU,"24,000,000"
175,Russian Federation,Europe,Eastern Europe,RUS,"19,000,000"
176,Rwanda,Africa,Eastern Africa,RWA,"17,500,000"
177,Saint Barthélemy,Americas,Caribbean,BLM,"9,900"
178,"Saint Helena, Ascension and Tristan da Cunha",Africa,Western Africa,SHN,"6,000"
179,Saint Kitts and Nevis,Americas,Caribbean,KNA,"53,000"
180,Saint Lucia,Americas,Caribbean,LCA,"23,800,000"
181,Saint Martin (French part),Americas,Caribbean,MAF,"7,300,000"
182,Saint Pierre and Miquelon,Americas,Northern America,SPM,"5,700"
183,Saint Vincent and the Grenadines,Americas,Caribbean,VCT,"16,400,000"
184,Samoa,Oceania,Polynesia,WSM,"26,000,000"
185,San Marino,Europe,Southern Europe,SMR,"6,600,000"
186,Sao Tome and Principe,Africa,Middle Africa,STP,"33,000,000"
187,Saudi Arabia,Asia,Western Asia,SAU,"6,600,000"
188,Senegal,Africa,Western Africa,SEN,"2,300,000"
189,Serbia,Europe,Southern Europe,SRB,"6,900,000"
190,Seychelles,Africa,Eastern Africa,SYC,"98,000"
191,Sierra Leone,Africa,Western Africa,SLE,"7,900,000"
192,Singapore,Asia,South-Eastern Asia,SGP,"5,900,000"
193,Sint Maarten (Dutch part),Americas,Caribbean,SXM,"9,300,000"
194,Slovakia,Europe,Eastern Europe,SVK,"5,500,000"
195,Slovenia,Europe,Southern Europe,SVN,"276,000,000"
196,Solomon Islands,Oceania,Melanesia,SLB,"686,000"
197,Somalia,Africa,Eastern Africa,SOM,"19,100,000"
198,South Africa,Africa,Southern Africa,ZAF,"59,000,000"
199,South Sudan,Africa,Eastern Africa,SSD,"11,900,000"
200,Spain,Europe,Southern Europe,ESP,"47,000,000"
201,Sri Lanka,Asia,Southern Asia,LKA,"33,000,000"
202,Sudan,Africa,Northern Africa,SDN,"9,600,000"
203,Suriname,Americas,South America,SUR,"591,000"
204,Svalbard and Jan Mayen,Europe,Northern Europe,SJM,"4,000,000"
205,Swaziland,Africa,Southern Africa,SWZ,"1,200,000"
206,Sweden,Europe,Northern Europe,SWE,"10,700,000"
207,Switzerland,Europe,Western Europe,CHE,"8,700,000"
208,Syrian Arab Republic,Asia,Western Asia,SYR,"2,800,000"
209,"Taiwan, Province of China",Asia,Eastern Asia,TWN,"34,000,000"
210,Tajikistan,Asia,Central Asia,TJK,"9,500,000"
211,"Tanzania, United Republic of",Africa,Eastern Africa,TZA,"59,700,000"
212,Thailand,Asia,South-Eastern Asia,THA,"69,800,000"
213,Timor-Leste,Asia,South-Eastern Asia,TLS,"1,300,000"
214,Togo,Africa,Western Africa,TGO,"8,300,000"
215,Tokelau,Oceania,Polynesia,TKL,"2,000,000"
216,Tonga,Oceania,Polynesia,TON,"11,500,000"
217,Trinidad and Tobago,Americas,Caribbean,TTO,"1,900,000"
218,Tunisia,Africa,Northern Africa,TUN,"125,000,000"
219,Turkey,Asia,Western Asia,TUR,"84,000,000"
220,Turkmenistan,Asia,Central Asia,TKM,"6,000,000"
221,Turks and Caicos Islands,Americas,Caribbean,TCA,"69,800,000"
222,Tuvalu,Oceania,Polynesia,TUV,"15,000,000"
223,Uganda,Africa,Eastern Africa,UGA,"45,700,000"
224,Ukraine,Europe,Eastern Europe,UKR,"9,900,000"
225,United Arab Emirates,Asia,Western Asia,ARE,"9,900,000"
226,United Kingdom of Great Britain and Northern I...,Europe,Northern Europe,GBR,"68,000,000"
227,United States of America,Americas,Northern America,USA,"59,700,000"
228,Uruguay,Americas,South America,URY,"5,100,000"
229,Uzbekistan,Asia,Central Asia,UZB,"6,000,000"
230,Vanuatu,Oceania,Melanesia,VUT,"5,900,000"
231,Venezuela (Bolivarian Republic of),Americas,South America,VEN,"4,900,000"
232,Viet Nam,Asia,South-Eastern Asia,VNM,"97,000,000"
233,Virgin Islands (British),Americas,Caribbean,VGB,"5,800,000"
234,Virgin Islands (U.S.),Americas,Caribbean,VIR,"11,400,000"
235,Wallis and Futuna,Oceania,Polynesia,WLF,"15,900,000"
236,Western Sahara,Africa,Northern Africa,ESH,"597,000"
237,Yemen,Asia,Western Asia,YEM,"5,500,000"
238,Zambia,Africa,Eastern Africa,ZMB,"213,000,000"
239,Zimbabwe,Africa,Eastern Africa,ZWE,"19,100,000"

Multi-Level Indexing

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Indexing\Creating an Index\WorldContinents.csv',
                encoding = 'ISO-8859-1')

pd.set_option('display.max.rows', 1359)
pd.set_option('display.max.columns', 15)

In [16]:
df

,continent,sub_region,country,code_3,Unnamed: 4
0,Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
1,Europe,Northern Europe,Åland Islands,ALA,"5,500,000"
2,Europe,Southern Europe,Albania,ALB,"3,300,000"
3,Africa,Northern Africa,Algeria,DZA,"9,500,000"
4,Oceania,Polynesia,American Samoa,ASM,"55,000"
5,Europe,Southern Europe,Andorra,AND,"77,000"
6,Africa,Middle Africa,Angola,AGO,"54,000,000"
7,Americas,Caribbean,Anguilla,AIA,"2,100,000"
8,Americas,Caribbean,Antigua and Barbuda,ATG,"98,000"
9,Americas,South America,Argentina,ARG,"45,000,000"
10,Asia,Western Asia,Armenia,ARM,"45,700,000"
11,Americas,Caribbean,Aruba,ABW,"11,600,000"
12,Oceania,Australia and New Zealand,Australia,AUS,"36,000,000"
13,Europe,Western Europe,Austria,AUT,"9,000,000"
14,Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
15,Americas,Caribbean,Bahamas,BHS,"7,500,000"
16,Asia,Western Asia,Bahrain,BHR,"1,900,000"
17,Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
18,Americas,Caribbean,Barbados,BRB,"44,000,000"
19,Europe,Eastern Europe,Belarus,BLR,"9,400,000"
20,Europe,Western Europe,Belgium,BEL,"12,000,000"
21,Americas,Central America,Belize,BLZ,"9,000,000"
22,Africa,Western Africa,Benin,BEN,"17,400,000"
23,Americas,Northern America,Bermuda,BMU,"64,000"
24,Asia,Southern Asia,Bhutan,BTN,"771,000"
25,Americas,South America,Bolivia (Plurinational State of),BOL,"12,900,000"
26,Americas,Caribbean,"Bonaire, Sint Eustatius and Saba",BES,"4,300,000"
27,Europe,Southern Europe,Bosnia and Herzegovina,BIH,"5,000,000"
28,Africa,Southern Africa,Botswana,BWA,"29,000,000"
29,Americas,South America,Brazil,BRA,"32,700,000"
30,Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
31,Europe,Eastern Europe,Bulgaria,BGR,"6,900,000"
32,Africa,Western Africa,Burkina Faso,BFA,"31,000,000"
33,Africa,Eastern Africa,Burundi,BDI,"128,000,000"
34,Africa,Western Africa,Cabo Verde,CPV,"556,000"
35,Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
36,Africa,Middle Africa,Cameroon,CMR,"38,000,000"
37,Americas,Northern America,Canada,CAN,"60,000,000"
38,Americas,Caribbean,Cayman Islands,CYM,"66,000"
39,Africa,Middle Africa,Central African Republic,CAF,"84,000,000"
40,Africa,Middle Africa,Chad,TCD,"2,100,000"
41,Americas,South America,Chile,CHL,"25,000,000"
42,Asia,Eastern Asia,China,CHN,"1,412,000,000"
43,Americas,South America,Colombia,COL,"51,000,000"
44,Africa,Eastern Africa,Comoros,COM,"870,000"
45,Africa,Middle Africa,Congo,COG,"5,500,000"
46,Africa,Middle Africa,Congo (Democratic Republic of the),COD,"89,000,000"
47,Oceania,Polynesia,Cook Islands,COK,"206,000,000"
48,Americas,Central America,Costa Rica,CRI,"5,100,000"
49,Africa,Western Africa,Côte d'Ivoire,CIV,"38,000,000"
50,Europe,Southern Europe,Croatia,HRV,"7,900,000"
51,Americas,Caribbean,Cuba,CUB,"110,000,000"
52,Americas,Caribbean,Curaçao,CUW,"2,600,000"
53,Asia,Western Asia,Cyprus,CYP,"1,200,000"
54,Europe,Eastern Europe,Czech Republic,CZE,"102,000,000"
55,Europe,Northern Europe,Denmark,DNK,"5,800,000"
56,Africa,Eastern Africa,Djibouti,DJI,"988,000"
57,Americas,Caribbean,Dominica,DMA,"72,000"
58,Americas,Caribbean,Dominican Republic,DOM,"11,200,000"
59,Americas,South America,Ecuador,ECU,"2,900,000"
60,Africa,Northern Africa,Egypt,EGY,"11,300,000"
61,Americas,Central America,El Salvador,SLV,"6,500,000"
62,Africa,Middle Africa,Equatorial Guinea,GNQ,"1,700,000"
63,Africa,Eastern Africa,Eritrea,ERI,"5,100,000"
64,Europe,Northern Europe,Estonia,EST,"1,300,000"
65,Africa,Eastern Africa,Ethiopia,ETH,"16,700,000"
66,Americas,South America,Falkland Islands (Malvinas),FLK,"5,500,000"
67,Europe,Northern Europe,Faroe Islands,FRO,"49,000"
68,Oceania,Melanesia,Fiji,FJI,"896,000"
69,Europe,Northern Europe,Finland,FIN,"5,500,000"
70,Europe,Western Europe,France,FRA,"67,000,000"
71,Americas,South America,French Guiana,GUF,"45,000,000"
72,Oceania,Polynesia,French Polynesia,PYF,"40,000,000"
73,Africa,Middle Africa,Gabon,GAB,"28,000,000"
74,Africa,Western Africa,Gambia,GMB,"3,000,000"
75,Asia,Western Asia,Georgia,GEO,"5,400,000"
76,Europe,Western Europe,Germany,DEU,"83,200,000"
77,Africa,Western Africa,Ghana,GHA,"51,000,000"
78,Europe,Southern Europe,Gibraltar,GIB,"6,500,000"
79,Europe,Southern Europe,Greece,GRC,"10,800,000"
80,Americas,Northern America,Greenland,GRL,"56,000"
81,Americas,Caribbean,Grenada,GRD,"16,700,000"
82,Americas,Caribbean,Guadeloupe,GLP,"9,000,000"
83,Oceania,Micronesia,Guam,GUM,"2,800,000"
84,Americas,Central America,Guatemala,GTM,"21,000,000"
85,Europe,Northern Europe,Guernsey,GGY,"63,000"
86,Africa,Western Africa,Guinea,GIN,"18,700,000"
87,Africa,Western Africa,Guinea-Bissau,GNB,"10,000,000"
88,Americas,South America,Guyana,GUY,"787,000"
89,Americas,Caribbean,Haiti,HTI,"114,000,000"
90,Europe,Southern Europe,Holy See,VAT,800
91,Americas,Central America,Honduras,HND,"10,000,000"
92,Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
93,Europe,Eastern Europe,Hungary,HUN,"9,600,000"
94,Europe,Northern Europe,Iceland,ISL,"6,900,000"
95,Asia,Southern Asia,India,IND,"1,400,000,000"
96,Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
97,Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
98,Asia,Western Asia,Iraq,IRQ,"89,000,000"
99,Europe,Northern Europe,Ireland,IRL,"5,000,000"
100,Europe,Northern Europe,Isle of Man,IMN,"85,000"
101,Asia,Western Asia,Israel,ISR,"9,300,000"
102,Europe,Southern Europe,Italy,ITA,"60,000,000"
103,Americas,Caribbean,Jamaica,JAM,"3,700,000"
104,Asia,Eastern Asia,Japan,JPN,"18,000,000"
105,Europe,Northern Europe,Jersey,JEY,"11,800,000"
106,Asia,Western Asia,Jordan,JOR,"10,300,000"
107,Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
108,Africa,Eastern Africa,Kenya,KEN,"53,800,000"
109,Oceania,Micronesia,Kiribati,KIR,"17,600,000"
110,Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
111,Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
112,Asia,Western Asia,Kuwait,KWT,"8,300,000"
113,Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
114,Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
115,Europe,Northern Europe,Latvia,LVA,"10,000,000"
116,Asia,Western Asia,Lebanon,LBN,"6,800,000"
117,Africa,Southern Africa,Lesotho,LSO,"27,700,000"
118,Africa,Western Africa,Liberia,LBR,"5,000,000"
119,Africa,Northern Africa,Libya,LBY,"6,900,000"
120,Europe,Western Europe,Liechtenstein,LIE,"68,000,000"
121,Europe,Northern Europe,Lithuania,LTU,"3,500,000"
122,Europe,Western Europe,Luxembourg,LUX,"633,000"
123,Asia,Eastern Asia,Macao,MAC,"650,000"
124,Europe,Southern Europe,Macedonia (the former Yugoslav Republic of),MKD,"26,000,000"
125,Africa,Eastern Africa,Madagascar,MDG,"4,300,000"
126,Africa,Eastern Africa,Malawi,MWI,"25,800,000"
127,Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
128,Asia,Southern Asia,Maldives,MDV,"540,000"
129,Africa,Western Africa,Mali,MLI,"30,000,000"
130,Europe,Southern Europe,Malta,MLT,"97,000,000"
131,Oceania,Micronesia,Marshall Islands,MHL,"59,000"
132,Americas,Caribbean,Martinique,MTQ,"6,900,000"
133,Africa,Western Africa,Mauritania,MRT,"83,200,000"
134,Africa,Eastern Africa,Mauritius,MUS,"1,300,000"
135,Africa,Eastern Africa,Mayotte,MYT,"4,800,000"
136,Americas,Central America,Mexico,MEX,"18,400,000"
137,Oceania,Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
138,Europe,Eastern Europe,Moldova (Republic of),MDA,"3,300,000"
139,Europe,Western Europe,Monaco,MCO,"7,100,000"
140,Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
141,Europe,Southern Europe,Montenegro,MNE,"622,000"
142,Americas,Caribbean,Montserrat,MSR,"5,000"
143,Africa,Northern Africa,Morocco,MAR,"6,800,000"
144,Africa,Eastern Africa,Mozambique,MOZ,"51,600,000"
145,Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
146,Africa,Southern Africa,Namibia,NAM,"3,200,000"
147,Oceania,Micronesia,Nauru,NRU,"144,000,000"
148,Asia,Southern Asia,Nepal,NPL,"44,000,000"
149,Europe,Western Europe,Netherlands,NLD,"2,800,000"
150,Oceania,Melanesia,New Caledonia,NCL,"44,000,000"
151,Oceania,Australia and New Zealand,New Zealand,NZL,"84,000,000"
152,Americas,Central America,Nicaragua,NIC,"6,600,000"
153,Africa,Western Africa,Niger,NER,"35,000,000"
154,Africa,Western Africa,Nigeria,NGA,"31,000,000"
155,Oceania,Polynesia,Niue,NIU,"2,400,000"
156,Oceania,Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
157,Oceania,Micronesia,Northern Mariana Islands,MNP,"58,000"
158,Europe,Northern Europe,Norway,NOR,"5,400,000"
159,Asia,Western Asia,Oman,OMN,"5,000,000"
160,Asia,Southern Asia,Pakistan,PAK,"331,000,000"
161,Oceania,Micronesia,Palau,PLW,"220,000,000"
162,Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
163,Americas,Central America,Panama,PAN,"8,700,000"
164,Oceania,Melanesia,Papua New Guinea,PNG,"9,000,000"
165,Americas,South America,Paraguay,PRY,"7,100,000"
166,Americas,South America,Peru,PER,"59,000,000"
167,Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
168,Oceania,Polynesia,Pitcairn,PCN,"50,000,000"
169,Europe,Eastern Europe,Poland,POL,"67,000,000"
170,Europe,Southern Europe,Portugal,PRT,"10,400,000"
171,Americas,Caribbean,Puerto Rico,PRI,"47,000,000"
172,Asia,Western Asia,Qatar,QAT,"3,500,000"
173,Africa,Eastern Africa,Réunion,REU,"859,000"
174,Europe,Eastern Europe,Romania,ROU,"24,000,000"
175,Europe,Eastern Europe,Russian Federation,RUS,"19,000,000"
176,Africa,Eastern Africa,Rwanda,RWA,"17,500,000"
177,Americas,Caribbean,Saint Barthélemy,BLM,"9,900"
178,Africa,Western Africa,"Saint Helena, Ascension and Tristan da Cunha",SHN,"6,000"
179,Americas,Caribbean,Saint Kitts and Nevis,KNA,"53,000"
180,Americas,Caribbean,Saint Lucia,LCA,"23,800,000"
181,Americas,Caribbean,Saint Martin (French part),MAF,"7,300,000"
182,Americas,Northern America,Saint Pierre and Miquelon,SPM,"5,700"
183,Americas,Caribbean,Saint Vincent and the Grenadines,VCT,"16,400,000"
184,Oceania,Polynesia,Samoa,WSM,"26,000,000"
185,Europe,Southern Europe,San Marino,SMR,"6,600,000"
186,Africa,Middle Africa,Sao Tome and Principe,STP,"33,000,000"
187,Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
188,Africa,Western Africa,Senegal,SEN,"2,300,000"
189,Europe,Southern Europe,Serbia,SRB,"6,900,000"
190,Africa,Eastern Africa,Seychelles,SYC,"98,000"
191,Africa,Western Africa,Sierra Leone,SLE,"7,900,000"
192,Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
193,Americas,Caribbean,Sint Maarten (Dutch part),SXM,"9,300,000"
194,Europe,Eastern Europe,Slovakia,SVK,"5,500,000"
195,Europe,Southern Europe,Slovenia,SVN,"276,000,000"
196,Oceania,Melanesia,Solomon Islands,SLB,"686,000"
197,Africa,Eastern Africa,Somalia,SOM,"19,100,000"
198,Africa,Southern Africa,South Africa,ZAF,"59,000,000"
199,Africa,Eastern Africa,South Sudan,SSD,"11,900,000"
200,Europe,Southern Europe,Spain,ESP,"47,000,000"
201,Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
202,Africa,Northern Africa,Sudan,SDN,"9,600,000"
203,Americas,South America,Suriname,SUR,"591,000"
204,Europe,Northern Europe,Svalbard and Jan Mayen,SJM,"4,000,000"
205,Africa,Southern Africa,Swaziland,SWZ,"1,200,000"
206,Europe,Northern Europe,Sweden,SWE,"10,700,000"
207,Europe,Western Europe,Switzerland,CHE,"8,700,000"
208,Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
209,Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
210,Asia,Central Asia,Tajikistan,TJK,"9,500,000"
211,Africa,Eastern Africa,"Tanzania, United Republic of",TZA,"59,700,000"
212,Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
213,Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
214,Africa,Western Africa,Togo,TGO,"8,300,000"
215,Oceania,Polynesia,Tokelau,TKL,"2,000,000"
216,Oceania,Polynesia,Tonga,TON,"11,500,000"
217,Americas,Caribbean,Trinidad and Tobago,TTO,"1,900,000"
218,Africa,Northern Africa,Tunisia,TUN,"125,000,000"
219,Asia,Western Asia,Turkey,TUR,"84,000,000"
220,Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
221,Americas,Caribbean,Turks and Caicos Islands,TCA,"69,800,000"
222,Oceania,Polynesia,Tuvalu,TUV,"15,000,000"
223,Africa,Eastern Africa,Uganda,UGA,"45,700,000"
224,Europe,Eastern Europe,Ukraine,UKR,"9,900,000"
225,Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
226,Europe,Northern Europe,United Kingdom of Great Britain and Northern I...,GBR,"68,000,000"
227,Americas,Northern America,United States of America,USA,"59,700,000"
228,Americas,South America,Uruguay,URY,"5,100,000"
229,Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
230,Oceania,Melanesia,Vanuatu,VUT,"5,900,000"
231,Americas,South America,Venezuela (Bolivarian Republic of),VEN,"4,900,000"
232,Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
233,Americas,Caribbean,Virgin Islands (British),VGB,"5,800,000"
234,Americas,Caribbean,Virgin Islands (U.S.),VIR,"11,400,000"
235,Oceania,Polynesia,Wallis and Futuna,WLF,"15,900,000"
236,Africa,Northern Africa,Western Sahara,ESH,"597,000"
237,Asia,Western Asia,Yemen,YEM,"5,500,000"
238,Africa,Eastern Africa,Zambia,ZMB,"213,000,000"
239,Africa,Eastern Africa,Zimbabwe,ZWE,"19,100,000"

In [20]:
df_continent = df.set_index(['continent', 'sub_region']).sort_values(by = ['continent', 'sub_region'], ascending = [False, True])

In [21]:
df_continent

                                                                               country  \
continent sub_region
Oceania   Australia and New Zealand                                          Australia
          Australia and New Zealand                                        New Zealand
          Australia and New Zealand                                     Norfolk Island
          Melanesia                                                               Fiji
          Melanesia                                                      New Caledonia
          Melanesia                                                   Papua New Guinea
          Melanesia                                                    Solomon Islands
          Melanesia                                                            Vanuatu
          Micronesia                                                              Guam
          Micronesia                                                          Kiribati
          Micronesia                                                  Marshall Islands
          Micronesia                                  Micronesia (Federated States of)
          Micronesia                                                             Nauru
          Micronesia                                          Northern Mariana Islands
          Micronesia                                                             Palau
          Polynesia                                                     American Samoa
          Polynesia                                                       Cook Islands
          Polynesia                                                   French Polynesia
          Polynesia                                                               Niue
          Polynesia                                                           Pitcairn
          Polynesia                                                              Samoa
          Polynesia                                                            Tokelau
          Polynesia                                                              Tonga
          Polynesia                                                             Tuvalu
          Polynesia                                                  Wallis and Futuna
Europe    Eastern Europe                                                       Belarus
          Eastern Europe                                                      Bulgaria
          Eastern Europe                                                Czech Republic
          Eastern Europe                                                       Hungary
          Eastern Europe                                         Moldova (Republic of)
          Eastern Europe                                                        Poland
          Eastern Europe                                                       Romania
          Eastern Europe                                            Russian Federation
          Eastern Europe                                                      Slovakia
          Eastern Europe                                                       Ukraine
          Northern Europe                                                Åland Islands
          Northern Europe                                                      Denmark
          Northern Europe                                                      Estonia
          Northern Europe                                                Faroe Islands
          Northern Europe                                                      Finland
          Northern Europe                                                     Guernsey
          Northern Europe                                                      Iceland
          Northern Europe                                                      Ireland
          Northern Europe                                                  Isle of Man
          Northern Europe                                                       Jersey
          Northern Europe                                                       Latvia
          Northern Europe                                                    Lithuania
          Northern Europe                                                       Norway
          Northern Europe                                       Svalbard and Jan Mayen
          Northern Europe                                                       Sweden
          Northern Europe            United Kingdom of Great Britain and Northern I...
          Southern Europe                                                      Albania
          Southern Europe                                                      Andorra
          Southern Europe                                       Bosnia and Herzegovina
          Southern Europe                                                      Croatia
          Southern Europe                                                    Gibraltar
          Southern Europe                                                       Greece
          Southern Europe                                                     Holy See
          Southern Europe                                                        Italy
          Southern Europe                  Macedonia (the former Yugoslav Republic of)
          Southern Europe                                                        Malta
          Southern Europe                                                   Montenegro
          Southern Europe                                                     Portugal
          Southern Europe                                                   San Marino
          Southern Europe                                                       Serbia
          Southern Europe                                                     Slovenia
          Southern Europe                                                        Spain
          Western Europe                                                       Austria
          Western Europe                                                       Belgium
          Western Europe                                                        France
          Western Europe                                                       Germany
          Western Europe                                                 Liechtenstein
          Western Europe                                                    Luxembourg
          Western Europe                                                        Monaco
          Western Europe                                                   Netherlands
          Western Europe                                                   Switzerland
Asia      Central Asia                                                      Kazakhstan
          Central Asia                                                      Kyrgyzstan
          Central Asia                                                      Tajikistan
          Central Asia                                                    Turkmenistan
          Central Asia                                                      Uzbekistan
          Eastern Asia                                                           China
          Eastern Asia                                                       Hong Kong
          Eastern Asia                                                           Japan
          Eastern Asia                         Korea (Democratic People's Republic of)
          Eastern Asia                                             Korea (Republic of)
          Eastern Asia                                                           Macao
          Eastern Asia                                                        Mongolia
          Eastern Asia                                       Taiwan, Province of China
          South-Eastern Asia                                         Brunei Darussalam
          South-Eastern Asia                                                  Cambodia
          South-Eastern Asia                                                 Indonesia
          South-Eastern Asia                          Lao People's Democratic Republic
          South-Eastern Asia                                                  Malaysia
          South-Eastern Asia                                                   Myanmar
          South-Eastern Asia                                               Philippines
          South-Eastern Asia                                                 Singapore
          South-Eastern Asia                                                  Thailand
          South-Eastern Asia                                               Timor-Leste
          South-Eastern Asia                                                  Viet Nam
          Southern Asia                                                    Afghanistan
          Southern Asia                                                     Bangladesh
          Southern Asia                                                         Bhutan
          Southern Asia                                                          India
          Southern Asia                                     Iran (Islamic Republic of)
          Southern Asia                                                       Maldives
          Southern Asia                                                          Nepal
          Southern Asia                                                       Pakistan
          Southern Asia                                                      Sri Lanka
          Western Asia                                                         Armenia
          Western Asia                                                      Azerbaijan
          Western Asia                                                         Bahrain
          Western Asia                                                          Cyprus
          Western Asia                                                         Georgia
          Western Asia                                                            Iraq
          Western Asia                                                          Israel
          Western Asia                                                          Jordan
          Western Asia                                                          Kuwait
          Western Asia                                                         Lebanon
          Western Asia                                                            Oman
          Western Asia                                             Palestine, State of
          Western Asia                                                           Qatar
          Western Asia                                                    Saudi Arabia
          Western Asia                                            Syrian Arab Republic
          Western Asia                                                          Turkey
          Western Asia                                            United Arab Emirates
          Western Asia                                                           Yemen
Americas  Caribbean                                                           Anguilla
          Caribbean                                                Antigua and Barbuda
          Caribbean                                                              Aruba
          Caribbean                                                            Bahamas
          Caribbean                                                           Barbados
          Caribbean                                   Bonaire, Sint Eustatius and Saba
          Caribbean                                                     Cayman Islands
          Caribbean                                                               Cuba
          Caribbean                                                            Curaçao
          Caribbean                                                           Dominica
          Caribbean                                                 Dominican Republic
          Caribbean                                                            Grenada
          Caribbean                                                         Guadeloupe
          Caribbean                                                              Haiti
          Caribbean                                                            Jamaica
          Caribbean                                                         Martinique
          Caribbean                                                         Montserrat
          Caribbean                                                        Puerto Rico
          Caribbean                                                   Saint Barthélemy
          Caribbean                                              Saint Kitts and Nevis
          Caribbean                                                        Saint Lucia
          Caribbean                                         Saint Martin (French part)
          Caribbean                                   Saint Vincent and the Grenadines
          Caribbean                                          Sint Maarten (Dutch part)
          Caribbean                                                Trinidad and Tobago
          Caribbean                                           Turks and Caicos Islands
          Caribbean                                           Virgin Islands (British)
          Caribbean                                              Virgin Islands (U.S.)
          Central America                                                       Belize
          Central America                                                   Costa Rica
          Central America                                                  El Salvador
          Central America                                                    Guatemala
          Central America                                                     Honduras
          Central America                                                       Mexico
          Central America                                                    Nicaragua
          Central America                                                       Panama
          Northern America                                                     Bermuda
          Northern America                                                      Canada
          Northern America                                                   Greenland
          Northern America                                   Saint Pierre and Miquelon
          Northern America                                    United States of America
          South America                                                      Argentina
          South America                               Bolivia (Plurinational State of)
          South America                                                         Brazil
          South America                                                          Chile
          South America                                                       Colombia
          South America                                                        Ecuador
          South America                                    Falkland Islands (Malvinas)
          South America                                                  French Guiana
          South America                                                         Guyana
          South America                                                       Paraguay
          South America                                                           Peru
          South America                                                       Suriname
          South America                                                        Uruguay
          South America                             Venezuela (Bolivarian Republic of)
Africa    Eastern Africa                                                       Burundi
          Eastern Africa                                                       Comoros
          Eastern Africa                                                      Djibouti
          Eastern Africa                                                       Eritrea
          Eastern Africa                                                      Ethiopia
          Eastern Africa                                                         Kenya
          Eastern Africa                                                    Madagascar
          Eastern Africa                                                        Malawi
          Eastern Africa                                                     Mauritius
          Eastern Africa                                                       Mayotte
          Eastern Africa                                                    Mozambique
          Eastern Africa                                                       Réunion
          Eastern Africa                                                        Rwanda
          Eastern Africa                                                    Seychelles
          Eastern Africa                                                       Somalia
          Eastern Africa                                                   South Sudan
          Eastern Africa                                  Tanzania, United Republic of
          Eastern Africa                                                        Uganda
          Eastern Africa                                                        Zambia
          Eastern Africa                                                      Zimbabwe
          Middle Africa                                                         Angola
          Middle Africa                                                       Cameroon
          Middle Africa                                       Central African Republic
          Middle Africa                                                           Chad
          Middle Africa                                                          Congo
          Middle Africa                             Congo (Democratic Republic of the)
          Middle Africa                                              Equatorial Guinea
          Middle Africa                                                          Gabon
          Middle Africa                                          Sao Tome and Principe
          Northern Africa                                                      Algeria
          Northern Africa                                                        Egypt
          Northern Africa                                                        Libya
          Northern Africa                                                      Morocco
          Northern Africa                                                        Sudan
          Northern Africa                                                      Tunisia
          Northern Africa                                               Western Sahara
          Southern Africa                                                     Botswana
          Southern Africa                                                      Lesotho
          Southern Africa                                                      Namibia
          Southern Africa                                                 South Africa
          Southern Africa                                                    Swaziland
          Western Africa                                                         Benin
          Western Africa                                                  Burkina Faso
          Western Africa                                                    Cabo Verde
          Western Africa                                                 Côte d'Ivoire
          Western Africa                                                        Gambia

In [23]:
df_continent.loc['Oceania']

,country,code_3,Unnamed: 4
sub_region,,,
Australia and New Zealand,Australia,AUS,"36,000,000"
Australia and New Zealand,New Zealand,NZL,"84,000,000"
Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
Melanesia,Fiji,FJI,"896,000"
Melanesia,New Caledonia,NCL,"44,000,000"
Melanesia,Papua New Guinea,PNG,"9,000,000"
Melanesia,Solomon Islands,SLB,"686,000"
Melanesia,Vanuatu,VUT,"5,900,000"
Micronesia,Guam,GUM,"2,800,000"
Micronesia,Kiribati,KIR,"17,600,000"
Micronesia,Marshall Islands,MHL,"59,000"
Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
Micronesia,Nauru,NRU,"144,000,000"
Micronesia,Northern Mariana Islands,MNP,"58,000"
Micronesia,Palau,PLW,"220,000,000"
Polynesia,American Samoa,ASM,"55,000"
Polynesia,Cook Islands,COK,"206,000,000"
Polynesia,French Polynesia,PYF,"40,000,000"
Polynesia,Niue,NIU,"2,400,000"
Polynesia,Pitcairn,PCN,"50,000,000"
Polynesia,Samoa,WSM,"26,000,000"
Polynesia,Tokelau,TKL,"2,000,000"
Polynesia,Tonga,TON,"11,500,000"
Polynesia,Tuvalu,TUV,"15,000,000"
Polynesia,Wallis and Futuna,WLF,"15,900,000"

Filtering Indexes with loc and iloc

In [24]:
import pandas as pd

In [25]:
df = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Indexing\Creating an Index\WorldContinents.csv',
                encoding = 'ISO-8859-1')

pd.set_option('display.max.rows', 1359)
pd.set_option('display.max.columns', 15)

In [26]:
df

,continent,sub_region,country,code_3,Unnamed: 4
0,Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
1,Europe,Northern Europe,Åland Islands,ALA,"5,500,000"
2,Europe,Southern Europe,Albania,ALB,"3,300,000"
3,Africa,Northern Africa,Algeria,DZA,"9,500,000"
4,Oceania,Polynesia,American Samoa,ASM,"55,000"
5,Europe,Southern Europe,Andorra,AND,"77,000"
6,Africa,Middle Africa,Angola,AGO,"54,000,000"
7,Americas,Caribbean,Anguilla,AIA,"2,100,000"
8,Americas,Caribbean,Antigua and Barbuda,ATG,"98,000"
9,Americas,South America,Argentina,ARG,"45,000,000"
10,Asia,Western Asia,Armenia,ARM,"45,700,000"
11,Americas,Caribbean,Aruba,ABW,"11,600,000"
12,Oceania,Australia and New Zealand,Australia,AUS,"36,000,000"
13,Europe,Western Europe,Austria,AUT,"9,000,000"
14,Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
15,Americas,Caribbean,Bahamas,BHS,"7,500,000"
16,Asia,Western Asia,Bahrain,BHR,"1,900,000"
17,Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
18,Americas,Caribbean,Barbados,BRB,"44,000,000"
19,Europe,Eastern Europe,Belarus,BLR,"9,400,000"
20,Europe,Western Europe,Belgium,BEL,"12,000,000"
21,Americas,Central America,Belize,BLZ,"9,000,000"
22,Africa,Western Africa,Benin,BEN,"17,400,000"
23,Americas,Northern America,Bermuda,BMU,"64,000"
24,Asia,Southern Asia,Bhutan,BTN,"771,000"
25,Americas,South America,Bolivia (Plurinational State of),BOL,"12,900,000"
26,Americas,Caribbean,"Bonaire, Sint Eustatius and Saba",BES,"4,300,000"
27,Europe,Southern Europe,Bosnia and Herzegovina,BIH,"5,000,000"
28,Africa,Southern Africa,Botswana,BWA,"29,000,000"
29,Americas,South America,Brazil,BRA,"32,700,000"
30,Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
31,Europe,Eastern Europe,Bulgaria,BGR,"6,900,000"
32,Africa,Western Africa,Burkina Faso,BFA,"31,000,000"
33,Africa,Eastern Africa,Burundi,BDI,"128,000,000"
34,Africa,Western Africa,Cabo Verde,CPV,"556,000"
35,Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
36,Africa,Middle Africa,Cameroon,CMR,"38,000,000"
37,Americas,Northern America,Canada,CAN,"60,000,000"
38,Americas,Caribbean,Cayman Islands,CYM,"66,000"
39,Africa,Middle Africa,Central African Republic,CAF,"84,000,000"
40,Africa,Middle Africa,Chad,TCD,"2,100,000"
41,Americas,South America,Chile,CHL,"25,000,000"
42,Asia,Eastern Asia,China,CHN,"1,412,000,000"
43,Americas,South America,Colombia,COL,"51,000,000"
44,Africa,Eastern Africa,Comoros,COM,"870,000"
45,Africa,Middle Africa,Congo,COG,"5,500,000"
46,Africa,Middle Africa,Congo (Democratic Republic of the),COD,"89,000,000"
47,Oceania,Polynesia,Cook Islands,COK,"206,000,000"
48,Americas,Central America,Costa Rica,CRI,"5,100,000"
49,Africa,Western Africa,Côte d'Ivoire,CIV,"38,000,000"
50,Europe,Southern Europe,Croatia,HRV,"7,900,000"
51,Americas,Caribbean,Cuba,CUB,"110,000,000"
52,Americas,Caribbean,Curaçao,CUW,"2,600,000"
53,Asia,Western Asia,Cyprus,CYP,"1,200,000"
54,Europe,Eastern Europe,Czech Republic,CZE,"102,000,000"
55,Europe,Northern Europe,Denmark,DNK,"5,800,000"
56,Africa,Eastern Africa,Djibouti,DJI,"988,000"
57,Americas,Caribbean,Dominica,DMA,"72,000"
58,Americas,Caribbean,Dominican Republic,DOM,"11,200,000"
59,Americas,South America,Ecuador,ECU,"2,900,000"
60,Africa,Northern Africa,Egypt,EGY,"11,300,000"
61,Americas,Central America,El Salvador,SLV,"6,500,000"
62,Africa,Middle Africa,Equatorial Guinea,GNQ,"1,700,000"
63,Africa,Eastern Africa,Eritrea,ERI,"5,100,000"
64,Europe,Northern Europe,Estonia,EST,"1,300,000"
65,Africa,Eastern Africa,Ethiopia,ETH,"16,700,000"
66,Americas,South America,Falkland Islands (Malvinas),FLK,"5,500,000"
67,Europe,Northern Europe,Faroe Islands,FRO,"49,000"
68,Oceania,Melanesia,Fiji,FJI,"896,000"
69,Europe,Northern Europe,Finland,FIN,"5,500,000"
70,Europe,Western Europe,France,FRA,"67,000,000"
71,Americas,South America,French Guiana,GUF,"45,000,000"
72,Oceania,Polynesia,French Polynesia,PYF,"40,000,000"
73,Africa,Middle Africa,Gabon,GAB,"28,000,000"
74,Africa,Western Africa,Gambia,GMB,"3,000,000"
75,Asia,Western Asia,Georgia,GEO,"5,400,000"
76,Europe,Western Europe,Germany,DEU,"83,200,000"
77,Africa,Western Africa,Ghana,GHA,"51,000,000"
78,Europe,Southern Europe,Gibraltar,GIB,"6,500,000"
79,Europe,Southern Europe,Greece,GRC,"10,800,000"
80,Americas,Northern America,Greenland,GRL,"56,000"
81,Americas,Caribbean,Grenada,GRD,"16,700,000"
82,Americas,Caribbean,Guadeloupe,GLP,"9,000,000"
83,Oceania,Micronesia,Guam,GUM,"2,800,000"
84,Americas,Central America,Guatemala,GTM,"21,000,000"
85,Europe,Northern Europe,Guernsey,GGY,"63,000"
86,Africa,Western Africa,Guinea,GIN,"18,700,000"
87,Africa,Western Africa,Guinea-Bissau,GNB,"10,000,000"
88,Americas,South America,Guyana,GUY,"787,000"
89,Americas,Caribbean,Haiti,HTI,"114,000,000"
90,Europe,Southern Europe,Holy See,VAT,800
91,Americas,Central America,Honduras,HND,"10,000,000"
92,Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
93,Europe,Eastern Europe,Hungary,HUN,"9,600,000"
94,Europe,Northern Europe,Iceland,ISL,"6,900,000"
95,Asia,Southern Asia,India,IND,"1,400,000,000"
96,Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
97,Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
98,Asia,Western Asia,Iraq,IRQ,"89,000,000"
99,Europe,Northern Europe,Ireland,IRL,"5,000,000"
100,Europe,Northern Europe,Isle of Man,IMN,"85,000"
101,Asia,Western Asia,Israel,ISR,"9,300,000"
102,Europe,Southern Europe,Italy,ITA,"60,000,000"
103,Americas,Caribbean,Jamaica,JAM,"3,700,000"
104,Asia,Eastern Asia,Japan,JPN,"18,000,000"
105,Europe,Northern Europe,Jersey,JEY,"11,800,000"
106,Asia,Western Asia,Jordan,JOR,"10,300,000"
107,Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
108,Africa,Eastern Africa,Kenya,KEN,"53,800,000"
109,Oceania,Micronesia,Kiribati,KIR,"17,600,000"
110,Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
111,Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
112,Asia,Western Asia,Kuwait,KWT,"8,300,000"
113,Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
114,Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
115,Europe,Northern Europe,Latvia,LVA,"10,000,000"
116,Asia,Western Asia,Lebanon,LBN,"6,800,000"
117,Africa,Southern Africa,Lesotho,LSO,"27,700,000"
118,Africa,Western Africa,Liberia,LBR,"5,000,000"
119,Africa,Northern Africa,Libya,LBY,"6,900,000"
120,Europe,Western Europe,Liechtenstein,LIE,"68,000,000"
121,Europe,Northern Europe,Lithuania,LTU,"3,500,000"
122,Europe,Western Europe,Luxembourg,LUX,"633,000"
123,Asia,Eastern Asia,Macao,MAC,"650,000"
124,Europe,Southern Europe,Macedonia (the former Yugoslav Republic of),MKD,"26,000,000"
125,Africa,Eastern Africa,Madagascar,MDG,"4,300,000"
126,Africa,Eastern Africa,Malawi,MWI,"25,800,000"
127,Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
128,Asia,Southern Asia,Maldives,MDV,"540,000"
129,Africa,Western Africa,Mali,MLI,"30,000,000"
130,Europe,Southern Europe,Malta,MLT,"97,000,000"
131,Oceania,Micronesia,Marshall Islands,MHL,"59,000"
132,Americas,Caribbean,Martinique,MTQ,"6,900,000"
133,Africa,Western Africa,Mauritania,MRT,"83,200,000"
134,Africa,Eastern Africa,Mauritius,MUS,"1,300,000"
135,Africa,Eastern Africa,Mayotte,MYT,"4,800,000"
136,Americas,Central America,Mexico,MEX,"18,400,000"
137,Oceania,Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
138,Europe,Eastern Europe,Moldova (Republic of),MDA,"3,300,000"
139,Europe,Western Europe,Monaco,MCO,"7,100,000"
140,Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
141,Europe,Southern Europe,Montenegro,MNE,"622,000"
142,Americas,Caribbean,Montserrat,MSR,"5,000"
143,Africa,Northern Africa,Morocco,MAR,"6,800,000"
144,Africa,Eastern Africa,Mozambique,MOZ,"51,600,000"
145,Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
146,Africa,Southern Africa,Namibia,NAM,"3,200,000"
147,Oceania,Micronesia,Nauru,NRU,"144,000,000"
148,Asia,Southern Asia,Nepal,NPL,"44,000,000"
149,Europe,Western Europe,Netherlands,NLD,"2,800,000"
150,Oceania,Melanesia,New Caledonia,NCL,"44,000,000"
151,Oceania,Australia and New Zealand,New Zealand,NZL,"84,000,000"
152,Americas,Central America,Nicaragua,NIC,"6,600,000"
153,Africa,Western Africa,Niger,NER,"35,000,000"
154,Africa,Western Africa,Nigeria,NGA,"31,000,000"
155,Oceania,Polynesia,Niue,NIU,"2,400,000"
156,Oceania,Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
157,Oceania,Micronesia,Northern Mariana Islands,MNP,"58,000"
158,Europe,Northern Europe,Norway,NOR,"5,400,000"
159,Asia,Western Asia,Oman,OMN,"5,000,000"
160,Asia,Southern Asia,Pakistan,PAK,"331,000,000"
161,Oceania,Micronesia,Palau,PLW,"220,000,000"
162,Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
163,Americas,Central America,Panama,PAN,"8,700,000"
164,Oceania,Melanesia,Papua New Guinea,PNG,"9,000,000"
165,Americas,South America,Paraguay,PRY,"7,100,000"
166,Americas,South America,Peru,PER,"59,000,000"
167,Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
168,Oceania,Polynesia,Pitcairn,PCN,"50,000,000"
169,Europe,Eastern Europe,Poland,POL,"67,000,000"
170,Europe,Southern Europe,Portugal,PRT,"10,400,000"
171,Americas,Caribbean,Puerto Rico,PRI,"47,000,000"
172,Asia,Western Asia,Qatar,QAT,"3,500,000"
173,Africa,Eastern Africa,Réunion,REU,"859,000"
174,Europe,Eastern Europe,Romania,ROU,"24,000,000"
175,Europe,Eastern Europe,Russian Federation,RUS,"19,000,000"
176,Africa,Eastern Africa,Rwanda,RWA,"17,500,000"
177,Americas,Caribbean,Saint Barthélemy,BLM,"9,900"
178,Africa,Western Africa,"Saint Helena, Ascension and Tristan da Cunha",SHN,"6,000"
179,Americas,Caribbean,Saint Kitts and Nevis,KNA,"53,000"
180,Americas,Caribbean,Saint Lucia,LCA,"23,800,000"
181,Americas,Caribbean,Saint Martin (French part),MAF,"7,300,000"
182,Americas,Northern America,Saint Pierre and Miquelon,SPM,"5,700"
183,Americas,Caribbean,Saint Vincent and the Grenadines,VCT,"16,400,000"
184,Oceania,Polynesia,Samoa,WSM,"26,000,000"
185,Europe,Southern Europe,San Marino,SMR,"6,600,000"
186,Africa,Middle Africa,Sao Tome and Principe,STP,"33,000,000"
187,Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
188,Africa,Western Africa,Senegal,SEN,"2,300,000"
189,Europe,Southern Europe,Serbia,SRB,"6,900,000"
190,Africa,Eastern Africa,Seychelles,SYC,"98,000"
191,Africa,Western Africa,Sierra Leone,SLE,"7,900,000"
192,Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
193,Americas,Caribbean,Sint Maarten (Dutch part),SXM,"9,300,000"
194,Europe,Eastern Europe,Slovakia,SVK,"5,500,000"
195,Europe,Southern Europe,Slovenia,SVN,"276,000,000"
196,Oceania,Melanesia,Solomon Islands,SLB,"686,000"
197,Africa,Eastern Africa,Somalia,SOM,"19,100,000"
198,Africa,Southern Africa,South Africa,ZAF,"59,000,000"
199,Africa,Eastern Africa,South Sudan,SSD,"11,900,000"
200,Europe,Southern Europe,Spain,ESP,"47,000,000"
201,Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
202,Africa,Northern Africa,Sudan,SDN,"9,600,000"
203,Americas,South America,Suriname,SUR,"591,000"
204,Europe,Northern Europe,Svalbard and Jan Mayen,SJM,"4,000,000"
205,Africa,Southern Africa,Swaziland,SWZ,"1,200,000"
206,Europe,Northern Europe,Sweden,SWE,"10,700,000"
207,Europe,Western Europe,Switzerland,CHE,"8,700,000"
208,Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
209,Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
210,Asia,Central Asia,Tajikistan,TJK,"9,500,000"
211,Africa,Eastern Africa,"Tanzania, United Republic of",TZA,"59,700,000"
212,Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
213,Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
214,Africa,Western Africa,Togo,TGO,"8,300,000"
215,Oceania,Polynesia,Tokelau,TKL,"2,000,000"
216,Oceania,Polynesia,Tonga,TON,"11,500,000"
217,Americas,Caribbean,Trinidad and Tobago,TTO,"1,900,000"
218,Africa,Northern Africa,Tunisia,TUN,"125,000,000"
219,Asia,Western Asia,Turkey,TUR,"84,000,000"
220,Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
221,Americas,Caribbean,Turks and Caicos Islands,TCA,"69,800,000"
222,Oceania,Polynesia,Tuvalu,TUV,"15,000,000"
223,Africa,Eastern Africa,Uganda,UGA,"45,700,000"
224,Europe,Eastern Europe,Ukraine,UKR,"9,900,000"
225,Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
226,Europe,Northern Europe,United Kingdom of Great Britain and Northern I...,GBR,"68,000,000"
227,Americas,Northern America,United States of America,USA,"59,700,000"
228,Americas,South America,Uruguay,URY,"5,100,000"
229,Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
230,Oceania,Melanesia,Vanuatu,VUT,"5,900,000"
231,Americas,South America,Venezuela (Bolivarian Republic of),VEN,"4,900,000"
232,Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
233,Americas,Caribbean,Virgin Islands (British),VGB,"5,800,000"
234,Americas,Caribbean,Virgin Islands (U.S.),VIR,"11,400,000"
235,Oceania,Polynesia,Wallis and Futuna,WLF,"15,900,000"
236,Africa,Northern Africa,Western Sahara,ESH,"597,000"
237,Asia,Western Asia,Yemen,YEM,"5,500,000"
238,Africa,Eastern Africa,Zambia,ZMB,"213,000,000"
239,Africa,Eastern Africa,Zimbabwe,ZWE,"19,100,000"

In [27]:
df.loc[0]

continent              Asia
sub_region    Southern Asia
country         Afghanistan
code_3                  AFG
Unnamed: 4       6,900,000
Name: 0, dtype: object

In [28]:
df.iloc[0]

continent              Asia
sub_region    Southern Asia
country         Afghanistan
code_3                  AFG
Unnamed: 4       6,900,000
Name: 0, dtype: object

In [29]:
df.set_index(['country'], inplace = True)

In [30]:
df

,continent,sub_region,code_3,Unnamed: 4
country,,,,
Afghanistan,Asia,Southern Asia,AFG,"6,900,000"
Åland Islands,Europe,Northern Europe,ALA,"5,500,000"
Albania,Europe,Southern Europe,ALB,"3,300,000"
Algeria,Africa,Northern Africa,DZA,"9,500,000"
American Samoa,Oceania,Polynesia,ASM,"55,000"
Andorra,Europe,Southern Europe,AND,"77,000"
Angola,Africa,Middle Africa,AGO,"54,000,000"
Anguilla,Americas,Caribbean,AIA,"2,100,000"
Antigua and Barbuda,Americas,Caribbean,ATG,"98,000"
Argentina,Americas,South America,ARG,"45,000,000"
Armenia,Asia,Western Asia,ARM,"45,700,000"
Aruba,Americas,Caribbean,ABW,"11,600,000"
Australia,Oceania,Australia and New Zealand,AUS,"36,000,000"
Austria,Europe,Western Europe,AUT,"9,000,000"
Azerbaijan,Asia,Western Asia,AZE,"10,000,000"
Bahamas,Americas,Caribbean,BHS,"7,500,000"
Bahrain,Asia,Western Asia,BHR,"1,900,000"
Bangladesh,Asia,Southern Asia,BGD,"2,500,000"
Barbados,Americas,Caribbean,BRB,"44,000,000"
Belarus,Europe,Eastern Europe,BLR,"9,400,000"
Belgium,Europe,Western Europe,BEL,"12,000,000"
Belize,Americas,Central America,BLZ,"9,000,000"
Benin,Africa,Western Africa,BEN,"17,400,000"
Bermuda,Americas,Northern America,BMU,"64,000"
Bhutan,Asia,Southern Asia,BTN,"771,000"
Bolivia (Plurinational State of),Americas,South America,BOL,"12,900,000"
"Bonaire, Sint Eustatius and Saba",Americas,Caribbean,BES,"4,300,000"
Bosnia and Herzegovina,Europe,Southern Europe,BIH,"5,000,000"
Botswana,Africa,Southern Africa,BWA,"29,000,000"
Brazil,Americas,South America,BRA,"32,700,000"
Brunei Darussalam,Asia,South-Eastern Asia,BRN,"9,400,000"
Bulgaria,Europe,Eastern Europe,BGR,"6,900,000"
Burkina Faso,Africa,Western Africa,BFA,"31,000,000"
Burundi,Africa,Eastern Africa,BDI,"128,000,000"
Cabo Verde,Africa,Western Africa,CPV,"556,000"
Cambodia,Asia,South-Eastern Asia,KHM,"2,200,000"
Cameroon,Africa,Middle Africa,CMR,"38,000,000"
Canada,Americas,Northern America,CAN,"60,000,000"
Cayman Islands,Americas,Caribbean,CYM,"66,000"
Central African Republic,Africa,Middle Africa,CAF,"84,000,000"
Chad,Africa,Middle Africa,TCD,"2,100,000"
Chile,Americas,South America,CHL,"25,000,000"
China,Asia,Eastern Asia,CHN,"1,412,000,000"
Colombia,Americas,South America,COL,"51,000,000"
Comoros,Africa,Eastern Africa,COM,"870,000"
Congo,Africa,Middle Africa,COG,"5,500,000"
Congo (Democratic Republic of the),Africa,Middle Africa,COD,"89,000,000"
Cook Islands,Oceania,Polynesia,COK,"206,000,000"
Costa Rica,Americas,Central America,CRI,"5,100,000"
Côte d'Ivoire,Africa,Western Africa,CIV,"38,000,000"
Croatia,Europe,Southern Europe,HRV,"7,900,000"
Cuba,Americas,Caribbean,CUB,"110,000,000"
Curaçao,Americas,Caribbean,CUW,"2,600,000"
Cyprus,Asia,Western Asia,CYP,"1,200,000"
Czech Republic,Europe,Eastern Europe,CZE,"102,000,000"
Denmark,Europe,Northern Europe,DNK,"5,800,000"
Djibouti,Africa,Eastern Africa,DJI,"988,000"
Dominica,Americas,Caribbean,DMA,"72,000"
Dominican Republic,Americas,Caribbean,DOM,"11,200,000"
Ecuador,Americas,South America,ECU,"2,900,000"
Egypt,Africa,Northern Africa,EGY,"11,300,000"
El Salvador,Americas,Central America,SLV,"6,500,000"
Equatorial Guinea,Africa,Middle Africa,GNQ,"1,700,000"
Eritrea,Africa,Eastern Africa,ERI,"5,100,000"
Estonia,Europe,Northern Europe,EST,"1,300,000"
Ethiopia,Africa,Eastern Africa,ETH,"16,700,000"
Falkland Islands (Malvinas),Americas,South America,FLK,"5,500,000"
Faroe Islands,Europe,Northern Europe,FRO,"49,000"
Fiji,Oceania,Melanesia,FJI,"896,000"
Finland,Europe,Northern Europe,FIN,"5,500,000"
France,Europe,Western Europe,FRA,"67,000,000"
French Guiana,Americas,South America,GUF,"45,000,000"
French Polynesia,Oceania,Polynesia,PYF,"40,000,000"
Gabon,Africa,Middle Africa,GAB,"28,000,000"
Gambia,Africa,Western Africa,GMB,"3,000,000"
Georgia,Asia,Western Asia,GEO,"5,400,000"
Germany,Europe,Western Europe,DEU,"83,200,000"
Ghana,Africa,Western Africa,GHA,"51,000,000"
Gibraltar,Europe,Southern Europe,GIB,"6,500,000"
Greece,Europe,Southern Europe,GRC,"10,800,000"
Greenland,Americas,Northern America,GRL,"56,000"
Grenada,Americas,Caribbean,GRD,"16,700,000"
Guadeloupe,Americas,Caribbean,GLP,"9,000,000"
Guam,Oceania,Micronesia,GUM,"2,800,000"
Guatemala,Americas,Central America,GTM,"21,000,000"
Guernsey,Europe,Northern Europe,GGY,"63,000"
Guinea,Africa,Western Africa,GIN,"18,700,000"
Guinea-Bissau,Africa,Western Africa,GNB,"10,000,000"
Guyana,Americas,South America,GUY,"787,000"
Haiti,Americas,Caribbean,HTI,"114,000,000"
Holy See,Europe,Southern Europe,VAT,800
Honduras,Americas,Central America,HND,"10,000,000"
Hong Kong,Asia,Eastern Asia,HKG,"7,500,000"
Hungary,Europe,Eastern Europe,HUN,"9,600,000"
Iceland,Europe,Northern Europe,ISL,"6,900,000"
India,Asia,Southern Asia,IND,"1,400,000,000"
Indonesia,Asia,South-Eastern Asia,IDN,"4,600,000"
Iran (Islamic Republic of),Asia,Southern Asia,IRN,"84,000,000"
Iraq,Asia,Western Asia,IRQ,"89,000,000"
Ireland,Europe,Northern Europe,IRL,"5,000,000"
Isle of Man,Europe,Northern Europe,IMN,"85,000"
Israel,Asia,Western Asia,ISR,"9,300,000"
Italy,Europe,Southern Europe,ITA,"60,000,000"
Jamaica,Americas,Caribbean,JAM,"3,700,000"
Japan,Asia,Eastern Asia,JPN,"18,000,000"
Jersey,Europe,Northern Europe,JEY,"11,800,000"
Jordan,Asia,Western Asia,JOR,"10,300,000"
Kazakhstan,Asia,Central Asia,KAZ,"22,000,000"
Kenya,Africa,Eastern Africa,KEN,"53,800,000"
Kiribati,Oceania,Micronesia,KIR,"17,600,000"
Korea (Democratic People's Republic of),Asia,Eastern Asia,PRK,"38,000,000"
Korea (Republic of),Asia,Eastern Asia,KOR,"51,600,000"
Kuwait,Asia,Western Asia,KWT,"8,300,000"
Kyrgyzstan,Asia,Central Asia,KGZ,"6,600,000"
Lao People's Democratic Republic,Asia,South-Eastern Asia,LAO,"7,300,000"
Latvia,Europe,Northern Europe,LVA,"10,000,000"
Lebanon,Asia,Western Asia,LBN,"6,800,000"
Lesotho,Africa,Southern Africa,LSO,"27,700,000"
Liberia,Africa,Western Africa,LBR,"5,000,000"
Libya,Africa,Northern Africa,LBY,"6,900,000"
Liechtenstein,Europe,Western Europe,LIE,"68,000,000"
Lithuania,Europe,Northern Europe,LTU,"3,500,000"
Luxembourg,Europe,Western Europe,LUX,"633,000"
Macao,Asia,Eastern Asia,MAC,"650,000"
Macedonia (the former Yugoslav Republic of),Europe,Southern Europe,MKD,"26,000,000"
Madagascar,Africa,Eastern Africa,MDG,"4,300,000"
Malawi,Africa,Eastern Africa,MWI,"25,800,000"
Malaysia,Asia,South-Eastern Asia,MYS,"53,800,000"
Maldives,Asia,Southern Asia,MDV,"540,000"
Mali,Africa,Western Africa,MLI,"30,000,000"
Malta,Europe,Southern Europe,MLT,"97,000,000"
Marshall Islands,Oceania,Micronesia,MHL,"59,000"
Martinique,Americas,Caribbean,MTQ,"6,900,000"
Mauritania,Africa,Western Africa,MRT,"83,200,000"
Mauritius,Africa,Eastern Africa,MUS,"1,300,000"
Mayotte,Africa,Eastern Africa,MYT,"4,800,000"
Mexico,Americas,Central America,MEX,"18,400,000"
Micronesia (Federated States of),Oceania,Micronesia,FSM,"164,000,000"
Moldova (Republic of),Europe,Eastern Europe,MDA,"3,300,000"
Monaco,Europe,Western Europe,MCO,"7,100,000"
Mongolia,Asia,Eastern Asia,MNG,"5,000,000"
Montenegro,Europe,Southern Europe,MNE,"622,000"
Montserrat,Americas,Caribbean,MSR,"5,000"
Morocco,Africa,Northern Africa,MAR,"6,800,000"
Mozambique,Africa,Eastern Africa,MOZ,"51,600,000"
Myanmar,Asia,South-Eastern Asia,MMR,"54,000,000"
Namibia,Africa,Southern Africa,NAM,"3,200,000"
Nauru,Oceania,Micronesia,NRU,"144,000,000"
Nepal,Asia,Southern Asia,NPL,"44,000,000"
Netherlands,Europe,Western Europe,NLD,"2,800,000"
New Caledonia,Oceania,Melanesia,NCL,"44,000,000"
New Zealand,Oceania,Australia and New Zealand,NZL,"84,000,000"
Nicaragua,Americas,Central America,NIC,"6,600,000"
Niger,Africa,Western Africa,NER,"35,000,000"
Nigeria,Africa,Western Africa,NGA,"31,000,000"
Niue,Oceania,Polynesia,NIU,"2,400,000"
Norfolk Island,Oceania,Australia and New Zealand,NFK,"20,300,000"
Northern Mariana Islands,Oceania,Micronesia,MNP,"58,000"
Norway,Europe,Northern Europe,NOR,"5,400,000"
Oman,Asia,Western Asia,OMN,"5,000,000"
Pakistan,Asia,Southern Asia,PAK,"331,000,000"
Palau,Oceania,Micronesia,PLW,"220,000,000"
"Palestine, State of",Asia,Western Asia,PSE,"5,100,000"
Panama,Americas,Central America,PAN,"8,700,000"
Papua New Guinea,Oceania,Melanesia,PNG,"9,000,000"
Paraguay,Americas,South America,PRY,"7,100,000"
Peru,Americas,South America,PER,"59,000,000"
Philippines,Asia,South-Eastern Asia,PHL,"13,100,000"
Pitcairn,Oceania,Polynesia,PCN,"50,000,000"
Poland,Europe,Eastern Europe,POL,"67,000,000"
Portugal,Europe,Southern Europe,PRT,"10,400,000"
Puerto Rico,Americas,Caribbean,PRI,"47,000,000"
Qatar,Asia,Western Asia,QAT,"3,500,000"
Réunion,Africa,Eastern Africa,REU,"859,000"
Romania,Europe,Eastern Europe,ROU,"24,000,000"
Russian Federation,Europe,Eastern Europe,RUS,"19,000,000"
Rwanda,Africa,Eastern Africa,RWA,"17,500,000"
Saint Barthélemy,Americas,Caribbean,BLM,"9,900"
"Saint Helena, Ascension and Tristan da Cunha",Africa,Western Africa,SHN,"6,000"
Saint Kitts and Nevis,Americas,Caribbean,KNA,"53,000"
Saint Lucia,Americas,Caribbean,LCA,"23,800,000"
Saint Martin (French part),Americas,Caribbean,MAF,"7,300,000"
Saint Pierre and Miquelon,Americas,Northern America,SPM,"5,700"
Saint Vincent and the Grenadines,Americas,Caribbean,VCT,"16,400,000"
Samoa,Oceania,Polynesia,WSM,"26,000,000"
San Marino,Europe,Southern Europe,SMR,"6,600,000"
Sao Tome and Principe,Africa,Middle Africa,STP,"33,000,000"
Saudi Arabia,Asia,Western Asia,SAU,"6,600,000"
Senegal,Africa,Western Africa,SEN,"2,300,000"
Serbia,Europe,Southern Europe,SRB,"6,900,000"
Seychelles,Africa,Eastern Africa,SYC,"98,000"
Sierra Leone,Africa,Western Africa,SLE,"7,900,000"
Singapore,Asia,South-Eastern Asia,SGP,"5,900,000"
Sint Maarten (Dutch part),Americas,Caribbean,SXM,"9,300,000"
Slovakia,Europe,Eastern Europe,SVK,"5,500,000"
Slovenia,Europe,Southern Europe,SVN,"276,000,000"
Solomon Islands,Oceania,Melanesia,SLB,"686,000"
Somalia,Africa,Eastern Africa,SOM,"19,100,000"
South Africa,Africa,Southern Africa,ZAF,"59,000,000"
South Sudan,Africa,Eastern Africa,SSD,"11,900,000"
Spain,Europe,Southern Europe,ESP,"47,000,000"
Sri Lanka,Asia,Southern Asia,LKA,"33,000,000"
Sudan,Africa,Northern Africa,SDN,"9,600,000"
Suriname,Americas,South America,SUR,"591,000"
Svalbard and Jan Mayen,Europe,Northern Europe,SJM,"4,000,000"
Swaziland,Africa,Southern Africa,SWZ,"1,200,000"
Sweden,Europe,Northern Europe,SWE,"10,700,000"
Switzerland,Europe,Western Europe,CHE,"8,700,000"
Syrian Arab Republic,Asia,Western Asia,SYR,"2,800,000"
"Taiwan, Province of China",Asia,Eastern Asia,TWN,"34,000,000"
Tajikistan,Asia,Central Asia,TJK,"9,500,000"
"Tanzania, United Republic of",Africa,Eastern Africa,TZA,"59,700,000"
Thailand,Asia,South-Eastern Asia,THA,"69,800,000"
Timor-Leste,Asia,South-Eastern Asia,TLS,"1,300,000"
Togo,Africa,Western Africa,TGO,"8,300,000"
Tokelau,Oceania,Polynesia,TKL,"2,000,000"
Tonga,Oceania,Polynesia,TON,"11,500,000"
Trinidad and Tobago,Americas,Caribbean,TTO,"1,900,000"
Tunisia,Africa,Northern Africa,TUN,"125,000,000"
Turkey,Asia,Western Asia,TUR,"84,000,000"
Turkmenistan,Asia,Central Asia,TKM,"6,000,000"
Turks and Caicos Islands,Americas,Caribbean,TCA,"69,800,000"
Tuvalu,Oceania,Polynesia,TUV,"15,000,000"
Uganda,Africa,Eastern Africa,UGA,"45,700,000"
Ukraine,Europe,Eastern Europe,UKR,"9,900,000"
United Arab Emirates,Asia,Western Asia,ARE,"9,900,000"
United Kingdom of Great Britain and Northern Ireland,Europe,Northern Europe,GBR,"68,000,000"
United States of America,Americas,Northern America,USA,"59,700,000"
Uruguay,Americas,South America,URY,"5,100,000"
Uzbekistan,Asia,Central Asia,UZB,"6,000,000"
Vanuatu,Oceania,Melanesia,VUT,"5,900,000"
Venezuela (Bolivarian Republic of),Americas,South America,VEN,"4,900,000"
Viet Nam,Asia,South-Eastern Asia,VNM,"97,000,000"
Virgin Islands (British),Americas,Caribbean,VGB,"5,800,000"
Virgin Islands (U.S.),Americas,Caribbean,VIR,"11,400,000"
Wallis and Futuna,Oceania,Polynesia,WLF,"15,900,000"
Western Sahara,Africa,Northern Africa,ESH,"597,000"
Yemen,Asia,Western Asia,YEM,"5,500,000"
Zambia,Africa,Eastern Africa,ZMB,"213,000,000"
Zimbabwe,Africa,Eastern Africa,ZWE,"19,100,000"

In [33]:
df.loc['Afghanistan']

continent              Asia
sub_region    Southern Asia
code_3                  AFG
Unnamed: 4       6,900,000
Name: Afghanistan, dtype: object

In [31]:
df.iloc[0]

continent              Asia
sub_region    Southern Asia
code_3                  AFG
Unnamed: 4       6,900,000
Name: Afghanistan, dtype: object

In [35]:
df.reset_index(inplace = True)

In [36]:
df.set_index('continent', inplace = True)

In [37]:
df

,index,country,sub_region,code_3,Unnamed: 4
continent,,,,,
Asia,0,Afghanistan,Southern Asia,AFG,"6,900,000"
Europe,1,Åland Islands,Northern Europe,ALA,"5,500,000"
Europe,2,Albania,Southern Europe,ALB,"3,300,000"
Africa,3,Algeria,Northern Africa,DZA,"9,500,000"
Oceania,4,American Samoa,Polynesia,ASM,"55,000"
Europe,5,Andorra,Southern Europe,AND,"77,000"
Africa,6,Angola,Middle Africa,AGO,"54,000,000"
Americas,7,Anguilla,Caribbean,AIA,"2,100,000"
Americas,8,Antigua and Barbuda,Caribbean,ATG,"98,000"
Americas,9,Argentina,South America,ARG,"45,000,000"
Asia,10,Armenia,Western Asia,ARM,"45,700,000"
Americas,11,Aruba,Caribbean,ABW,"11,600,000"
Oceania,12,Australia,Australia and New Zealand,AUS,"36,000,000"
Europe,13,Austria,Western Europe,AUT,"9,000,000"
Asia,14,Azerbaijan,Western Asia,AZE,"10,000,000"
Americas,15,Bahamas,Caribbean,BHS,"7,500,000"
Asia,16,Bahrain,Western Asia,BHR,"1,900,000"
Asia,17,Bangladesh,Southern Asia,BGD,"2,500,000"
Americas,18,Barbados,Caribbean,BRB,"44,000,000"
Europe,19,Belarus,Eastern Europe,BLR,"9,400,000"
Europe,20,Belgium,Western Europe,BEL,"12,000,000"
Americas,21,Belize,Central America,BLZ,"9,000,000"
Africa,22,Benin,Western Africa,BEN,"17,400,000"
Americas,23,Bermuda,Northern America,BMU,"64,000"
Asia,24,Bhutan,Southern Asia,BTN,"771,000"
Americas,25,Bolivia (Plurinational State of),South America,BOL,"12,900,000"
Americas,26,"Bonaire, Sint Eustatius and Saba",Caribbean,BES,"4,300,000"
Europe,27,Bosnia and Herzegovina,Southern Europe,BIH,"5,000,000"
Africa,28,Botswana,Southern Africa,BWA,"29,000,000"
Americas,29,Brazil,South America,BRA,"32,700,000"
Asia,30,Brunei Darussalam,South-Eastern Asia,BRN,"9,400,000"
Europe,31,Bulgaria,Eastern Europe,BGR,"6,900,000"
Africa,32,Burkina Faso,Western Africa,BFA,"31,000,000"
Africa,33,Burundi,Eastern Africa,BDI,"128,000,000"
Africa,34,Cabo Verde,Western Africa,CPV,"556,000"
Asia,35,Cambodia,South-Eastern Asia,KHM,"2,200,000"
Africa,36,Cameroon,Middle Africa,CMR,"38,000,000"
Americas,37,Canada,Northern America,CAN,"60,000,000"
Americas,38,Cayman Islands,Caribbean,CYM,"66,000"
Africa,39,Central African Republic,Middle Africa,CAF,"84,000,000"
Africa,40,Chad,Middle Africa,TCD,"2,100,000"
Americas,41,Chile,South America,CHL,"25,000,000"
Asia,42,China,Eastern Asia,CHN,"1,412,000,000"
Americas,43,Colombia,South America,COL,"51,000,000"
Africa,44,Comoros,Eastern Africa,COM,"870,000"
Africa,45,Congo,Middle Africa,COG,"5,500,000"
Africa,46,Congo (Democratic Republic of the),Middle Africa,COD,"89,000,000"
Oceania,47,Cook Islands,Polynesia,COK,"206,000,000"
Americas,48,Costa Rica,Central America,CRI,"5,100,000"
Africa,49,Côte d'Ivoire,Western Africa,CIV,"38,000,000"
Europe,50,Croatia,Southern Europe,HRV,"7,900,000"
Americas,51,Cuba,Caribbean,CUB,"110,000,000"
Americas,52,Curaçao,Caribbean,CUW,"2,600,000"
Asia,53,Cyprus,Western Asia,CYP,"1,200,000"
Europe,54,Czech Republic,Eastern Europe,CZE,"102,000,000"
Europe,55,Denmark,Northern Europe,DNK,"5,800,000"
Africa,56,Djibouti,Eastern Africa,DJI,"988,000"
Americas,57,Dominica,Caribbean,DMA,"72,000"
Americas,58,Dominican Republic,Caribbean,DOM,"11,200,000"
Americas,59,Ecuador,South America,ECU,"2,900,000"
Africa,60,Egypt,Northern Africa,EGY,"11,300,000"
Americas,61,El Salvador,Central America,SLV,"6,500,000"
Africa,62,Equatorial Guinea,Middle Africa,GNQ,"1,700,000"
Africa,63,Eritrea,Eastern Africa,ERI,"5,100,000"
Europe,64,Estonia,Northern Europe,EST,"1,300,000"
Africa,65,Ethiopia,Eastern Africa,ETH,"16,700,000"
Americas,66,Falkland Islands (Malvinas),South America,FLK,"5,500,000"
Europe,67,Faroe Islands,Northern Europe,FRO,"49,000"
Oceania,68,Fiji,Melanesia,FJI,"896,000"
Europe,69,Finland,Northern Europe,FIN,"5,500,000"
Europe,70,France,Western Europe,FRA,"67,000,000"
Americas,71,French Guiana,South America,GUF,"45,000,000"
Oceania,72,French Polynesia,Polynesia,PYF,"40,000,000"
Africa,73,Gabon,Middle Africa,GAB,"28,000,000"
Africa,74,Gambia,Western Africa,GMB,"3,000,000"
Asia,75,Georgia,Western Asia,GEO,"5,400,000"
Europe,76,Germany,Western Europe,DEU,"83,200,000"
Africa,77,Ghana,Western Africa,GHA,"51,000,000"
Europe,78,Gibraltar,Southern Europe,GIB,"6,500,000"
Europe,79,Greece,Southern Europe,GRC,"10,800,000"
Americas,80,Greenland,Northern America,GRL,"56,000"
Americas,81,Grenada,Caribbean,GRD,"16,700,000"
Americas,82,Guadeloupe,Caribbean,GLP,"9,000,000"
Oceania,83,Guam,Micronesia,GUM,"2,800,000"
Americas,84,Guatemala,Central America,GTM,"21,000,000"
Europe,85,Guernsey,Northern Europe,GGY,"63,000"
Africa,86,Guinea,Western Africa,GIN,"18,700,000"
Africa,87,Guinea-Bissau,Western Africa,GNB,"10,000,000"
Americas,88,Guyana,South America,GUY,"787,000"
Americas,89,Haiti,Caribbean,HTI,"114,000,000"
Europe,90,Holy See,Southern Europe,VAT,800
Americas,91,Honduras,Central America,HND,"10,000,000"
Asia,92,Hong Kong,Eastern Asia,HKG,"7,500,000"
Europe,93,Hungary,Eastern Europe,HUN,"9,600,000"
Europe,94,Iceland,Northern Europe,ISL,"6,900,000"
Asia,95,India,Southern Asia,IND,"1,400,000,000"
Asia,96,Indonesia,South-Eastern Asia,IDN,"4,600,000"
Asia,97,Iran (Islamic Republic of),Southern Asia,IRN,"84,000,000"
Asia,98,Iraq,Western Asia,IRQ,"89,000,000"
Europe,99,Ireland,Northern Europe,IRL,"5,000,000"
Europe,100,Isle of Man,Northern Europe,IMN,"85,000"
Asia,101,Israel,Western Asia,ISR,"9,300,000"
Europe,102,Italy,Southern Europe,ITA,"60,000,000"
Americas,103,Jamaica,Caribbean,JAM,"3,700,000"
Asia,104,Japan,Eastern Asia,JPN,"18,000,000"
Europe,105,Jersey,Northern Europe,JEY,"11,800,000"
Asia,106,Jordan,Western Asia,JOR,"10,300,000"
Asia,107,Kazakhstan,Central Asia,KAZ,"22,000,000"
Africa,108,Kenya,Eastern Africa,KEN,"53,800,000"
Oceania,109,Kiribati,Micronesia,KIR,"17,600,000"
Asia,110,Korea (Democratic People's Republic of),Eastern Asia,PRK,"38,000,000"
Asia,111,Korea (Republic of),Eastern Asia,KOR,"51,600,000"
Asia,112,Kuwait,Western Asia,KWT,"8,300,000"
Asia,113,Kyrgyzstan,Central Asia,KGZ,"6,600,000"
Asia,114,Lao People's Democratic Republic,South-Eastern Asia,LAO,"7,300,000"
Europe,115,Latvia,Northern Europe,LVA,"10,000,000"
Asia,116,Lebanon,Western Asia,LBN,"6,800,000"
Africa,117,Lesotho,Southern Africa,LSO,"27,700,000"
Africa,118,Liberia,Western Africa,LBR,"5,000,000"
Africa,119,Libya,Northern Africa,LBY,"6,900,000"
Europe,120,Liechtenstein,Western Europe,LIE,"68,000,000"
Europe,121,Lithuania,Northern Europe,LTU,"3,500,000"
Europe,122,Luxembourg,Western Europe,LUX,"633,000"
Asia,123,Macao,Eastern Asia,MAC,"650,000"
Europe,124,Macedonia (the former Yugoslav Republic of),Southern Europe,MKD,"26,000,000"
Africa,125,Madagascar,Eastern Africa,MDG,"4,300,000"
Africa,126,Malawi,Eastern Africa,MWI,"25,800,000"
Asia,127,Malaysia,South-Eastern Asia,MYS,"53,800,000"
Asia,128,Maldives,Southern Asia,MDV,"540,000"
Africa,129,Mali,Western Africa,MLI,"30,000,000"
Europe,130,Malta,Southern Europe,MLT,"97,000,000"
Oceania,131,Marshall Islands,Micronesia,MHL,"59,000"
Americas,132,Martinique,Caribbean,MTQ,"6,900,000"
Africa,133,Mauritania,Western Africa,MRT,"83,200,000"
Africa,134,Mauritius,Eastern Africa,MUS,"1,300,000"
Africa,135,Mayotte,Eastern Africa,MYT,"4,800,000"
Americas,136,Mexico,Central America,MEX,"18,400,000"
Oceania,137,Micronesia (Federated States of),Micronesia,FSM,"164,000,000"
Europe,138,Moldova (Republic of),Eastern Europe,MDA,"3,300,000"
Europe,139,Monaco,Western Europe,MCO,"7,100,000"
Asia,140,Mongolia,Eastern Asia,MNG,"5,000,000"
Europe,141,Montenegro,Southern Europe,MNE,"622,000"
Americas,142,Montserrat,Caribbean,MSR,"5,000"
Africa,143,Morocco,Northern Africa,MAR,"6,800,000"
Africa,144,Mozambique,Eastern Africa,MOZ,"51,600,000"
Asia,145,Myanmar,South-Eastern Asia,MMR,"54,000,000"
Africa,146,Namibia,Southern Africa,NAM,"3,200,000"
Oceania,147,Nauru,Micronesia,NRU,"144,000,000"
Asia,148,Nepal,Southern Asia,NPL,"44,000,000"
Europe,149,Netherlands,Western Europe,NLD,"2,800,000"
Oceania,150,New Caledonia,Melanesia,NCL,"44,000,000"
Oceania,151,New Zealand,Australia and New Zealand,NZL,"84,000,000"
Americas,152,Nicaragua,Central America,NIC,"6,600,000"
Africa,153,Niger,Western Africa,NER,"35,000,000"
Africa,154,Nigeria,Western Africa,NGA,"31,000,000"
Oceania,155,Niue,Polynesia,NIU,"2,400,000"
Oceania,156,Norfolk Island,Australia and New Zealand,NFK,"20,300,000"
Oceania,157,Northern Mariana Islands,Micronesia,MNP,"58,000"
Europe,158,Norway,Northern Europe,NOR,"5,400,000"
Asia,159,Oman,Western Asia,OMN,"5,000,000"
Asia,160,Pakistan,Southern Asia,PAK,"331,000,000"
Oceania,161,Palau,Micronesia,PLW,"220,000,000"
Asia,162,"Palestine, State of",Western Asia,PSE,"5,100,000"
Americas,163,Panama,Central America,PAN,"8,700,000"
Oceania,164,Papua New Guinea,Melanesia,PNG,"9,000,000"
Americas,165,Paraguay,South America,PRY,"7,100,000"
Americas,166,Peru,South America,PER,"59,000,000"
Asia,167,Philippines,South-Eastern Asia,PHL,"13,100,000"
Oceania,168,Pitcairn,Polynesia,PCN,"50,000,000"
Europe,169,Poland,Eastern Europe,POL,"67,000,000"
Europe,170,Portugal,Southern Europe,PRT,"10,400,000"
Americas,171,Puerto Rico,Caribbean,PRI,"47,000,000"
Asia,172,Qatar,Western Asia,QAT,"3,500,000"
Africa,173,Réunion,Eastern Africa,REU,"859,000"
Europe,174,Romania,Eastern Europe,ROU,"24,000,000"
Europe,175,Russian Federation,Eastern Europe,RUS,"19,000,000"
Africa,176,Rwanda,Eastern Africa,RWA,"17,500,000"
Americas,177,Saint Barthélemy,Caribbean,BLM,"9,900"
Africa,178,"Saint Helena, Ascension and Tristan da Cunha",Western Africa,SHN,"6,000"
Americas,179,Saint Kitts and Nevis,Caribbean,KNA,"53,000"
Americas,180,Saint Lucia,Caribbean,LCA,"23,800,000"
Americas,181,Saint Martin (French part),Caribbean,MAF,"7,300,000"
Americas,182,Saint Pierre and Miquelon,Northern America,SPM,"5,700"
Americas,183,Saint Vincent and the Grenadines,Caribbean,VCT,"16,400,000"
Oceania,184,Samoa,Polynesia,WSM,"26,000,000"
Europe,185,San Marino,Southern Europe,SMR,"6,600,000"
Africa,186,Sao Tome and Principe,Middle Africa,STP,"33,000,000"
Asia,187,Saudi Arabia,Western Asia,SAU,"6,600,000"
Africa,188,Senegal,Western Africa,SEN,"2,300,000"
Europe,189,Serbia,Southern Europe,SRB,"6,900,000"
Africa,190,Seychelles,Eastern Africa,SYC,"98,000"
Africa,191,Sierra Leone,Western Africa,SLE,"7,900,000"
Asia,192,Singapore,South-Eastern Asia,SGP,"5,900,000"
Americas,193,Sint Maarten (Dutch part),Caribbean,SXM,"9,300,000"
Europe,194,Slovakia,Eastern Europe,SVK,"5,500,000"
Europe,195,Slovenia,Southern Europe,SVN,"276,000,000"
Oceania,196,Solomon Islands,Melanesia,SLB,"686,000"
Africa,197,Somalia,Eastern Africa,SOM,"19,100,000"
Africa,198,South Africa,Southern Africa,ZAF,"59,000,000"
Africa,199,South Sudan,Eastern Africa,SSD,"11,900,000"
Europe,200,Spain,Southern Europe,ESP,"47,000,000"
Asia,201,Sri Lanka,Southern Asia,LKA,"33,000,000"
Africa,202,Sudan,Northern Africa,SDN,"9,600,000"
Americas,203,Suriname,South America,SUR,"591,000"
Europe,204,Svalbard and Jan Mayen,Northern Europe,SJM,"4,000,000"
Africa,205,Swaziland,Southern Africa,SWZ,"1,200,000"
Europe,206,Sweden,Northern Europe,SWE,"10,700,000"
Europe,207,Switzerland,Western Europe,CHE,"8,700,000"
Asia,208,Syrian Arab Republic,Western Asia,SYR,"2,800,000"
Asia,209,"Taiwan, Province of China",Eastern Asia,TWN,"34,000,000"
Asia,210,Tajikistan,Central Asia,TJK,"9,500,000"
Africa,211,"Tanzania, United Republic of",Eastern Africa,TZA,"59,700,000"
Asia,212,Thailand,South-Eastern Asia,THA,"69,800,000"
Asia,213,Timor-Leste,South-Eastern Asia,TLS,"1,300,000"
Africa,214,Togo,Western Africa,TGO,"8,300,000"
Oceania,215,Tokelau,Polynesia,TKL,"2,000,000"
Oceania,216,Tonga,Polynesia,TON,"11,500,000"
Americas,217,Trinidad and Tobago,Caribbean,TTO,"1,900,000"
Africa,218,Tunisia,Northern Africa,TUN,"125,000,000"
Asia,219,Turkey,Western Asia,TUR,"84,000,000"
Asia,220,Turkmenistan,Central Asia,TKM,"6,000,000"
Americas,221,Turks and Caicos Islands,Caribbean,TCA,"69,800,000"
Oceania,222,Tuvalu,Polynesia,TUV,"15,000,000"
Africa,223,Uganda,Eastern Africa,UGA,"45,700,000"
Europe,224,Ukraine,Eastern Europe,UKR,"9,900,000"
Asia,225,United Arab Emirates,Western Asia,ARE,"9,900,000"
Europe,226,United Kingdom of Great Britain and Northern I...,Northern Europe,GBR,"68,000,000"
Americas,227,United States of America,Northern America,USA,"59,700,000"
Americas,228,Uruguay,South America,URY,"5,100,000"
Asia,229,Uzbekistan,Central Asia,UZB,"6,000,000"
Oceania,230,Vanuatu,Melanesia,VUT,"5,900,000"
Americas,231,Venezuela (Bolivarian Republic of),South America,VEN,"4,900,000"
Asia,232,Viet Nam,South-Eastern Asia,VNM,"97,000,000"
Americas,233,Virgin Islands (British),Caribbean,VGB,"5,800,000"
Americas,234,Virgin Islands (U.S.),Caribbean,VIR,"11,400,000"
Oceania,235,Wallis and Futuna,Polynesia,WLF,"15,900,000"
Africa,236,Western Sahara,Northern Africa,ESH,"597,000"
Asia,237,Yemen,Western Asia,YEM,"5,500,000"
Africa,238,Zambia,Eastern Africa,ZMB,"213,000,000"
Africa,239,Zimbabwe,Eastern Africa,ZWE,"19,100,000"

In [39]:
df.loc['Asia']

,index,country,sub_region,code_3,Unnamed: 4
continent,,,,,
Asia,0,Afghanistan,Southern Asia,AFG,"6,900,000"
Asia,10,Armenia,Western Asia,ARM,"45,700,000"
Asia,14,Azerbaijan,Western Asia,AZE,"10,000,000"
Asia,16,Bahrain,Western Asia,BHR,"1,900,000"
Asia,17,Bangladesh,Southern Asia,BGD,"2,500,000"
Asia,24,Bhutan,Southern Asia,BTN,"771,000"
Asia,30,Brunei Darussalam,South-Eastern Asia,BRN,"9,400,000"
Asia,35,Cambodia,South-Eastern Asia,KHM,"2,200,000"
Asia,42,China,Eastern Asia,CHN,"1,412,000,000"
Asia,53,Cyprus,Western Asia,CYP,"1,200,000"
Asia,75,Georgia,Western Asia,GEO,"5,400,000"
Asia,92,Hong Kong,Eastern Asia,HKG,"7,500,000"
Asia,95,India,Southern Asia,IND,"1,400,000,000"
Asia,96,Indonesia,South-Eastern Asia,IDN,"4,600,000"
Asia,97,Iran (Islamic Republic of),Southern Asia,IRN,"84,000,000"
Asia,98,Iraq,Western Asia,IRQ,"89,000,000"
Asia,101,Israel,Western Asia,ISR,"9,300,000"
Asia,104,Japan,Eastern Asia,JPN,"18,000,000"
Asia,106,Jordan,Western Asia,JOR,"10,300,000"
Asia,107,Kazakhstan,Central Asia,KAZ,"22,000,000"
Asia,110,Korea (Democratic People's Republic of),Eastern Asia,PRK,"38,000,000"
Asia,111,Korea (Republic of),Eastern Asia,KOR,"51,600,000"
Asia,112,Kuwait,Western Asia,KWT,"8,300,000"
Asia,113,Kyrgyzstan,Central Asia,KGZ,"6,600,000"
Asia,114,Lao People's Democratic Republic,South-Eastern Asia,LAO,"7,300,000"
Asia,116,Lebanon,Western Asia,LBN,"6,800,000"
Asia,123,Macao,Eastern Asia,MAC,"650,000"
Asia,127,Malaysia,South-Eastern Asia,MYS,"53,800,000"
Asia,128,Maldives,Southern Asia,MDV,"540,000"
Asia,140,Mongolia,Eastern Asia,MNG,"5,000,000"
Asia,145,Myanmar,South-Eastern Asia,MMR,"54,000,000"
Asia,148,Nepal,Southern Asia,NPL,"44,000,000"
Asia,159,Oman,Western Asia,OMN,"5,000,000"
Asia,160,Pakistan,Southern Asia,PAK,"331,000,000"
Asia,162,"Palestine, State of",Western Asia,PSE,"5,100,000"
Asia,167,Philippines,South-Eastern Asia,PHL,"13,100,000"
Asia,172,Qatar,Western Asia,QAT,"3,500,000"
Asia,187,Saudi Arabia,Western Asia,SAU,"6,600,000"
Asia,192,Singapore,South-Eastern Asia,SGP,"5,900,000"
Asia,201,Sri Lanka,Southern Asia,LKA,"33,000,000"
Asia,208,Syrian Arab Republic,Western Asia,SYR,"2,800,000"
Asia,209,"Taiwan, Province of China",Eastern Asia,TWN,"34,000,000"
Asia,210,Tajikistan,Central Asia,TJK,"9,500,000"
Asia,212,Thailand,South-Eastern Asia,THA,"69,800,000"
Asia,213,Timor-Leste,South-Eastern Asia,TLS,"1,300,000"
Asia,219,Turkey,Western Asia,TUR,"84,000,000"
Asia,220,Turkmenistan,Central Asia,TKM,"6,000,000"
Asia,225,United Arab Emirates,Western Asia,ARE,"9,900,000"
Asia,229,Uzbekistan,Central Asia,UZB,"6,000,000"
Asia,232,Viet Nam,South-Eastern Asia,VNM,"97,000,000"
Asia,237,Yemen,Western Asia,YEM,"5,500,000"

In [38]:
df.iloc[0]

index                     0
country         Afghanistan
sub_region    Southern Asia
code_3                  AFG
Unnamed: 4       6,900,000
Name: Asia, dtype: object

In [40]:
df.reset_index(inplace = True)

In [41]:
df_continent = df.set_index(['continent', 'sub_region'])

In [42]:
df_continent

                                     index  \
continent sub_region
Asia      Southern Asia                  0
Europe    Northern Europe                1
          Southern Europe                2
Africa    Northern Africa                3
Oceania   Polynesia                      4
Europe    Southern Europe                5
Africa    Middle Africa                  6
Americas  Caribbean                      7
          Caribbean                      8
          South America                  9
Asia      Western Asia                  10
Americas  Caribbean                     11
Oceania   Australia and New Zealand     12
Europe    Western Europe                13
Asia      Western Asia                  14
Americas  Caribbean                     15
Asia      Western Asia                  16
          Southern Asia                 17
Americas  Caribbean                     18
Europe    Eastern Europe                19
          Western Europe                20
Americas  Central America               21
Africa    Western Africa                22
Americas  Northern America              23
Asia      Southern Asia                 24
Americas  South America                 25
          Caribbean                     26
Europe    Southern Europe               27
Africa    Southern Africa               28
Americas  South America                 29
Asia      South-Eastern Asia            30
Europe    Eastern Europe                31
Africa    Western Africa                32
          Eastern Africa                33
          Western Africa                34
Asia      South-Eastern Asia            35
Africa    Middle Africa                 36
Americas  Northern America              37
          Caribbean                     38
Africa    Middle Africa                 39
          Middle Africa                 40
Americas  South America                 41
Asia      Eastern Asia                  42
Americas  South America                 43
Africa    Eastern Africa                44
          Middle Africa                 45
          Middle Africa                 46
Oceania   Polynesia                     47
Americas  Central America               48
Africa    Western Africa                49
Europe    Southern Europe               50
Americas  Caribbean                     51
          Caribbean                     52
Asia      Western Asia                  53
Europe    Eastern Europe                54
          Northern Europe               55
Africa    Eastern Africa                56
Americas  Caribbean                     57
          Caribbean                     58
          South America                 59
Africa    Northern Africa               60
Americas  Central America               61
Africa    Middle Africa                 62
          Eastern Africa                63
Europe    Northern Europe               64
Africa    Eastern Africa                65
Americas  South America                 66
Europe    Northern Europe               67
Oceania   Melanesia                     68
Europe    Northern Europe               69
          Western Europe                70
Americas  South America                 71
Oceania   Polynesia                     72
Africa    Middle Africa                 73
          Western Africa                74
Asia      Western Asia                  75
Europe    Western Europe                76
Africa    Western Africa                77
Europe    Southern Europe               78
          Southern Europe               79
Americas  Northern America              80
          Caribbean                     81
          Caribbean                     82
Oceania   Micronesia                    83
Americas  Central America               84
Europe    Northern Europe               85
Africa    Western Africa                86
          Western Africa                87
Americas  South America                 88
          Caribbean                     89
Europe    Southern Europe               90
Americas  Central America               91
Asia      Eastern Asia                  92
Europe    Eastern Europe                93
          Northern Europe               94
Asia      Southern Asia                 95
          South-Eastern Asia            96
          Southern Asia                 97
          Western Asia                  98
Europe    Northern Europe               99
          Northern Europe              100
Asia      Western Asia                 101
Europe    Southern Europe              102
Americas  Caribbean                    103
Asia      Eastern Asia                 104
Europe    Northern Europe              105
Asia      Western Asia                 106
          Central Asia                 107
Africa    Eastern Africa               108
Oceania   Micronesia                   109
Asia      Eastern Asia                 110
          Eastern Asia                 111
          Western Asia                 112
          Central Asia                 113
          South-Eastern Asia           114
Europe    Northern Europe              115
Asia      Western Asia                 116
Africa    Southern Africa              117
          Western Africa               118
          Northern Africa              119
Europe    Western Europe               120
          Northern Europe              121
          Western Europe               122
Asia      Eastern Asia                 123
Europe    Southern Europe              124
Africa    Eastern Africa               125
          Eastern Africa               126
Asia      South-Eastern Asia           127
          Southern Asia                128
Africa    Western Africa               129
Europe    Southern Europe              130
Oceania   Micronesia                   131
Americas  Caribbean                    132
Africa    Western Africa               133
          Eastern Africa               134
          Eastern Africa               135
Americas  Central America              136
Oceania   Micronesia                   137
Europe    Eastern Europe               138
          Western Europe               139
Asia      Eastern Asia                 140
Europe    Southern Europe              141
Americas  Caribbean                    142
Africa    Northern Africa              143
          Eastern Africa               144
Asia      South-Eastern Asia           145
Africa    Southern Africa              146
Oceania   Micronesia                   147
Asia      Southern Asia                148
Europe    Western Europe               149
Oceania   Melanesia                    150
          Australia and New Zealand    151
Americas  Central America              152
Africa    Western Africa               153
          Western Africa               154
Oceania   Polynesia                    155
          Australia and New Zealand    156
          Micronesia                   157
Europe    Northern Europe              158
Asia      Western Asia                 159
          Southern Asia                160
Oceania   Micronesia                   161
Asia      Western Asia                 162
Americas  Central America              163
Oceania   Melanesia                    164
Americas  South America                165
          South America                166
Asia      South-Eastern Asia           167
Oceania   Polynesia                    168
Europe    Eastern Europe               169
          Southern Europe              170
Americas  Caribbean                    171
Asia      Western Asia                 172
Africa    Eastern Africa               173
Europe    Eastern Europe               174
          Eastern Europe               175
Africa    Eastern Africa               176
Americas  Caribbean                    177
Africa    Western Africa               178
Americas  Caribbean                    179
          Caribbean                    180
          Caribbean                    181
          Northern America             182
          Caribbean                    183
Oceania   Polynesia                    184
Europe    Southern Europe              185
Africa    Middle Africa                186
Asia      Western Asia                 187
Africa    Western Africa               188
Europe    Southern Europe              189
Africa    Eastern Africa               190
          Western Africa               191
Asia      South-Eastern Asia           192
Americas  Caribbean                    193
Europe    Eastern Europe               194
          Southern Europe              195
Oceania   Melanesia                    196
Africa    Eastern Africa               197
          Southern Africa              198
          Eastern Africa               199
Europe    Southern Europe              200
Asia      Southern Asia                201
Africa    Northern Africa              202
Americas  South America                203
Europe    Northern Europe              204
Africa    Southern Africa              205
Europe    Northern Europe              206
          Western Europe               207
Asia      Western Asia                 208
          Eastern Asia                 209
          Central Asia                 210
Africa    Eastern Africa               211
Asia      South-Eastern Asia           212
          South-Eastern Asia           213
Africa    Western Africa               214
Oceania   Polynesia                    215
          Polynesia                    216
Americas  Caribbean                    217
Africa    Northern Africa              218
Asia      Western Asia                 219
          Central Asia                 220
Americas  Caribbean                    221
Oceania   Polynesia                    222
Africa    Eastern Africa               223
Europe    Eastern Europe               224
Asia      Western Asia                 225
Europe    Northern Europe              226
Americas  Northern America             227
          South America                228
Asia      Central Asia                 229
Oceania   Melanesia                    230
Americas  South America                231
Asia      South-Eastern Asia           232
Americas  Caribbean                    233
          Caribbean                    234
Oceania   Polynesia                    235
Africa    Northern Africa              236
Asia      Western Asia                 237
Africa    Eastern Africa               238
          Eastern Africa               239

                                                                               country  \
continent sub_region
Asia      Southern Asia                                                    Afghanistan
Europe    Northern Europe                                                Åland Islands
          Southern Europe                                                      Albania
Africa    Northern Africa                                                      Algeria
Oceania   Polynesia                                                     American Samoa
Europe    Southern Europe                                                      Andorra
Africa    Middle Africa                                                         Angola
Americas  Caribbean                                                           Anguilla
          Caribbean                                                Antigua and Barbuda
          South America                                                      Argentina
Asia      Western Asia                                                         Armenia
Americas  Caribbean                                                              Aruba
Oceania   Australia and New Zealand                                          Australia
Europe    Western Europe                                                       Austria
Asia      Western Asia                                                      Azerbaijan
Americas  Caribbean                                                            Bahamas
Asia      Western Asia                                                         Bahrain
          Southern Asia                                                     Bangladesh
Americas  Caribbean                                                           Barbados
Europe    Eastern Europe                                                       Belarus
          Western Europe                                                       Belgium
Americas  Central America                                                       Belize
Africa    Western Africa                                                         Benin
Americas  Northern America                                                     Bermuda
Asia      Southern Asia                                                         Bhutan
Americas  South America                               Bolivia (Plurinational State of)
          Caribbean                                   Bonaire, Sint Eustatius and Saba
Europe    Southern Europe                                       Bosnia and Herzegovina
Africa    Southern Africa                                                     Botswana
Americas  South America                                                         Brazil
Asia      South-Eastern Asia                                         Brunei Darussalam
Europe    Eastern Europe                                                      Bulgaria
Africa    Western Africa                                                  Burkina Faso
          Eastern Africa                                                       Burundi
          Western Africa                                                    Cabo Verde
Asia      South-Eastern Asia                                                  Cambodia
Africa    Middle Africa                                                       Cameroon
Americas  Northern America                                                      Canada
          Caribbean                                                     Cayman Islands
Africa    Middle Africa                                       Central African Republic
          Middle Africa                                                           Chad
Americas  South America                                                          Chile
Asia      Eastern Asia                                                           China
Americas  South America                                                       Colombia
Africa    Eastern Africa                                                       Comoros
          Middle Africa                                                          Congo
          Middle Africa                             Congo (Democratic Republic of the)
Oceania   Polynesia                                                       Cook Islands
Americas  Central America                                                   Costa Rica
Africa    Western Africa                                                 Côte d'Ivoire
Europe    Southern Europe                                                      Croatia
Americas  Caribbean                                                               Cuba
          Caribbean                                                            Curaçao
Asia      Western Asia                                                          Cyprus
Europe    Eastern Europe                                                Czech Republic
          Northern Europe                                                      Denmark
Africa    Eastern Africa                                                      Djibouti
Americas  Caribbean                                                           Dominica
          Caribbean                                                 Dominican Republic
          South America                                                        Ecuador
Africa    Northern Africa                                                        Egypt
Americas  Central America                                                  El Salvador
Africa    Middle Africa                                              Equatorial Guinea
          Eastern Africa                                                       Eritrea
Europe    Northern Europe                                                      Estonia
Africa    Eastern Africa                                                      Ethiopia
Americas  South America                                    Falkland Islands (Malvinas)
Europe    Northern Europe                                                Faroe Islands
Oceania   Melanesia                                                               Fiji
Europe    Northern Europe                                                      Finland
          Western Europe                                                        France
Americas  South America                                                  French Guiana
Oceania   Polynesia                                                   French Polynesia
Africa    Middle Africa                                                          Gabon
          Western Africa                                                        Gambia
Asia      Western Asia                                                         Georgia
Europe    Western Europe                                                       Germany
Africa    Western Africa                                                         Ghana
Europe    Southern Europe                                                    Gibraltar
          Southern Europe                                                       Greece
Americas  Northern America                                                   Greenland
          Caribbean                                                            Grenada
          Caribbean                                                         Guadeloupe
Oceania   Micronesia                                                              Guam
Americas  Central America                                                    Guatemala
Europe    Northern Europe                                                     Guernsey
Africa    Western Africa                                                        Guinea
          Western Africa                                                 Guinea-Bissau
Americas  South America                                                         Guyana
          Caribbean                                                              Haiti
Europe    Southern Europe                                                     Holy See
Americas  Central America                                                     Honduras
Asia      Eastern Asia                                                       Hong Kong
Europe    Eastern Europe                                                       Hungary
          Northern Europe                                                      Iceland
Asia      Southern Asia                                                          India
          South-Eastern Asia                                                 Indonesia
          Southern Asia                                     Iran (Islamic Republic of)
          Western Asia                                                            Iraq
Europe    Northern Europe                                                      Ireland
          Northern Europe                                                  Isle of Man
Asia      Western Asia                                                          Israel
Europe    Southern Europe                                                        Italy
Americas  Caribbean                                                            Jamaica
Asia      Eastern Asia                                                           Japan
Europe    Northern Europe                                                       Jersey
Asia      Western Asia                                                          Jordan
          Central Asia                                                      Kazakhstan
Africa    Eastern Africa                                                         Kenya

In [43]:
df_continent.loc['Asia', 'Southern Asia']

C:\Users\khairil.akub\AppData\Local\Temp\ipykernel_24488\249281347.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_continent.loc['Asia', 'Southern Asia']

                         index                     country code_3  \
continent sub_region
Asia      Southern Asia      0                 Afghanistan    AFG
          Southern Asia     17                  Bangladesh    BGD
          Southern Asia     24                      Bhutan    BTN
          Southern Asia     95                       India    IND
          Southern Asia     97  Iran (Islamic Republic of)    IRN
          Southern Asia    128                    Maldives    MDV
          Southern Asia    148                       Nepal    NPL
          Southern Asia    160                    Pakistan    PAK
          Southern Asia    201                   Sri Lanka    LKA

                              Unnamed: 4
continent sub_region
Asia      Southern Asia       6,900,000
          Southern Asia       2,500,000
          Southern Asia         771,000
          Southern Asia   1,400,000,000
          Southern Asia      84,000,000
          Southern Asia         540,000
          Southern Asia      44,000,000
          Southern Asia     331,000,000
          Southern Asia      33,000,000

In [44]:
df_continent.iloc[0]

index                   0
country       Afghanistan
code_3                AFG
Unnamed: 4     6,900,000
Name: (Asia, Southern Asia), dtype: object

In [46]:
df_continent.iloc[0,1]

'Afghanistan'

Reordering and Sorting Indexes

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Indexing\Creating an Index\WorldContinents.csv',
                encoding = 'ISO-8859-1')

pd.set_option('display.max.rows', 1359)
pd.set_option('display.max.columns', 15)

In [49]:
df

,continent,sub_region,country,code_3,Unnamed: 4
0,Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
1,Europe,Northern Europe,Åland Islands,ALA,"5,500,000"
2,Europe,Southern Europe,Albania,ALB,"3,300,000"
3,Africa,Northern Africa,Algeria,DZA,"9,500,000"
4,Oceania,Polynesia,American Samoa,ASM,"55,000"
5,Europe,Southern Europe,Andorra,AND,"77,000"
6,Africa,Middle Africa,Angola,AGO,"54,000,000"
7,Americas,Caribbean,Anguilla,AIA,"2,100,000"
8,Americas,Caribbean,Antigua and Barbuda,ATG,"98,000"
9,Americas,South America,Argentina,ARG,"45,000,000"
10,Asia,Western Asia,Armenia,ARM,"45,700,000"
11,Americas,Caribbean,Aruba,ABW,"11,600,000"
12,Oceania,Australia and New Zealand,Australia,AUS,"36,000,000"
13,Europe,Western Europe,Austria,AUT,"9,000,000"
14,Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
15,Americas,Caribbean,Bahamas,BHS,"7,500,000"
16,Asia,Western Asia,Bahrain,BHR,"1,900,000"
17,Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
18,Americas,Caribbean,Barbados,BRB,"44,000,000"
19,Europe,Eastern Europe,Belarus,BLR,"9,400,000"
20,Europe,Western Europe,Belgium,BEL,"12,000,000"
21,Americas,Central America,Belize,BLZ,"9,000,000"
22,Africa,Western Africa,Benin,BEN,"17,400,000"
23,Americas,Northern America,Bermuda,BMU,"64,000"
24,Asia,Southern Asia,Bhutan,BTN,"771,000"
25,Americas,South America,Bolivia (Plurinational State of),BOL,"12,900,000"
26,Americas,Caribbean,"Bonaire, Sint Eustatius and Saba",BES,"4,300,000"
27,Europe,Southern Europe,Bosnia and Herzegovina,BIH,"5,000,000"
28,Africa,Southern Africa,Botswana,BWA,"29,000,000"
29,Americas,South America,Brazil,BRA,"32,700,000"
30,Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
31,Europe,Eastern Europe,Bulgaria,BGR,"6,900,000"
32,Africa,Western Africa,Burkina Faso,BFA,"31,000,000"
33,Africa,Eastern Africa,Burundi,BDI,"128,000,000"
34,Africa,Western Africa,Cabo Verde,CPV,"556,000"
35,Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
36,Africa,Middle Africa,Cameroon,CMR,"38,000,000"
37,Americas,Northern America,Canada,CAN,"60,000,000"
38,Americas,Caribbean,Cayman Islands,CYM,"66,000"
39,Africa,Middle Africa,Central African Republic,CAF,"84,000,000"
40,Africa,Middle Africa,Chad,TCD,"2,100,000"
41,Americas,South America,Chile,CHL,"25,000,000"
42,Asia,Eastern Asia,China,CHN,"1,412,000,000"
43,Americas,South America,Colombia,COL,"51,000,000"
44,Africa,Eastern Africa,Comoros,COM,"870,000"
45,Africa,Middle Africa,Congo,COG,"5,500,000"
46,Africa,Middle Africa,Congo (Democratic Republic of the),COD,"89,000,000"
47,Oceania,Polynesia,Cook Islands,COK,"206,000,000"
48,Americas,Central America,Costa Rica,CRI,"5,100,000"
49,Africa,Western Africa,Côte d'Ivoire,CIV,"38,000,000"
50,Europe,Southern Europe,Croatia,HRV,"7,900,000"
51,Americas,Caribbean,Cuba,CUB,"110,000,000"
52,Americas,Caribbean,Curaçao,CUW,"2,600,000"
53,Asia,Western Asia,Cyprus,CYP,"1,200,000"
54,Europe,Eastern Europe,Czech Republic,CZE,"102,000,000"
55,Europe,Northern Europe,Denmark,DNK,"5,800,000"
56,Africa,Eastern Africa,Djibouti,DJI,"988,000"
57,Americas,Caribbean,Dominica,DMA,"72,000"
58,Americas,Caribbean,Dominican Republic,DOM,"11,200,000"
59,Americas,South America,Ecuador,ECU,"2,900,000"
60,Africa,Northern Africa,Egypt,EGY,"11,300,000"
61,Americas,Central America,El Salvador,SLV,"6,500,000"
62,Africa,Middle Africa,Equatorial Guinea,GNQ,"1,700,000"
63,Africa,Eastern Africa,Eritrea,ERI,"5,100,000"
64,Europe,Northern Europe,Estonia,EST,"1,300,000"
65,Africa,Eastern Africa,Ethiopia,ETH,"16,700,000"
66,Americas,South America,Falkland Islands (Malvinas),FLK,"5,500,000"
67,Europe,Northern Europe,Faroe Islands,FRO,"49,000"
68,Oceania,Melanesia,Fiji,FJI,"896,000"
69,Europe,Northern Europe,Finland,FIN,"5,500,000"
70,Europe,Western Europe,France,FRA,"67,000,000"
71,Americas,South America,French Guiana,GUF,"45,000,000"
72,Oceania,Polynesia,French Polynesia,PYF,"40,000,000"
73,Africa,Middle Africa,Gabon,GAB,"28,000,000"
74,Africa,Western Africa,Gambia,GMB,"3,000,000"
75,Asia,Western Asia,Georgia,GEO,"5,400,000"
76,Europe,Western Europe,Germany,DEU,"83,200,000"
77,Africa,Western Africa,Ghana,GHA,"51,000,000"
78,Europe,Southern Europe,Gibraltar,GIB,"6,500,000"
79,Europe,Southern Europe,Greece,GRC,"10,800,000"
80,Americas,Northern America,Greenland,GRL,"56,000"
81,Americas,Caribbean,Grenada,GRD,"16,700,000"
82,Americas,Caribbean,Guadeloupe,GLP,"9,000,000"
83,Oceania,Micronesia,Guam,GUM,"2,800,000"
84,Americas,Central America,Guatemala,GTM,"21,000,000"
85,Europe,Northern Europe,Guernsey,GGY,"63,000"
86,Africa,Western Africa,Guinea,GIN,"18,700,000"
87,Africa,Western Africa,Guinea-Bissau,GNB,"10,000,000"
88,Americas,South America,Guyana,GUY,"787,000"
89,Americas,Caribbean,Haiti,HTI,"114,000,000"
90,Europe,Southern Europe,Holy See,VAT,800
91,Americas,Central America,Honduras,HND,"10,000,000"
92,Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
93,Europe,Eastern Europe,Hungary,HUN,"9,600,000"
94,Europe,Northern Europe,Iceland,ISL,"6,900,000"
95,Asia,Southern Asia,India,IND,"1,400,000,000"
96,Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
97,Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
98,Asia,Western Asia,Iraq,IRQ,"89,000,000"
99,Europe,Northern Europe,Ireland,IRL,"5,000,000"
100,Europe,Northern Europe,Isle of Man,IMN,"85,000"
101,Asia,Western Asia,Israel,ISR,"9,300,000"
102,Europe,Southern Europe,Italy,ITA,"60,000,000"
103,Americas,Caribbean,Jamaica,JAM,"3,700,000"
104,Asia,Eastern Asia,Japan,JPN,"18,000,000"
105,Europe,Northern Europe,Jersey,JEY,"11,800,000"
106,Asia,Western Asia,Jordan,JOR,"10,300,000"
107,Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
108,Africa,Eastern Africa,Kenya,KEN,"53,800,000"
109,Oceania,Micronesia,Kiribati,KIR,"17,600,000"
110,Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
111,Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
112,Asia,Western Asia,Kuwait,KWT,"8,300,000"
113,Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
114,Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
115,Europe,Northern Europe,Latvia,LVA,"10,000,000"
116,Asia,Western Asia,Lebanon,LBN,"6,800,000"
117,Africa,Southern Africa,Lesotho,LSO,"27,700,000"
118,Africa,Western Africa,Liberia,LBR,"5,000,000"
119,Africa,Northern Africa,Libya,LBY,"6,900,000"
120,Europe,Western Europe,Liechtenstein,LIE,"68,000,000"
121,Europe,Northern Europe,Lithuania,LTU,"3,500,000"
122,Europe,Western Europe,Luxembourg,LUX,"633,000"
123,Asia,Eastern Asia,Macao,MAC,"650,000"
124,Europe,Southern Europe,Macedonia (the former Yugoslav Republic of),MKD,"26,000,000"
125,Africa,Eastern Africa,Madagascar,MDG,"4,300,000"
126,Africa,Eastern Africa,Malawi,MWI,"25,800,000"
127,Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
128,Asia,Southern Asia,Maldives,MDV,"540,000"
129,Africa,Western Africa,Mali,MLI,"30,000,000"
130,Europe,Southern Europe,Malta,MLT,"97,000,000"
131,Oceania,Micronesia,Marshall Islands,MHL,"59,000"
132,Americas,Caribbean,Martinique,MTQ,"6,900,000"
133,Africa,Western Africa,Mauritania,MRT,"83,200,000"
134,Africa,Eastern Africa,Mauritius,MUS,"1,300,000"
135,Africa,Eastern Africa,Mayotte,MYT,"4,800,000"
136,Americas,Central America,Mexico,MEX,"18,400,000"
137,Oceania,Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
138,Europe,Eastern Europe,Moldova (Republic of),MDA,"3,300,000"
139,Europe,Western Europe,Monaco,MCO,"7,100,000"
140,Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
141,Europe,Southern Europe,Montenegro,MNE,"622,000"
142,Americas,Caribbean,Montserrat,MSR,"5,000"
143,Africa,Northern Africa,Morocco,MAR,"6,800,000"
144,Africa,Eastern Africa,Mozambique,MOZ,"51,600,000"
145,Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
146,Africa,Southern Africa,Namibia,NAM,"3,200,000"
147,Oceania,Micronesia,Nauru,NRU,"144,000,000"
148,Asia,Southern Asia,Nepal,NPL,"44,000,000"
149,Europe,Western Europe,Netherlands,NLD,"2,800,000"
150,Oceania,Melanesia,New Caledonia,NCL,"44,000,000"
151,Oceania,Australia and New Zealand,New Zealand,NZL,"84,000,000"
152,Americas,Central America,Nicaragua,NIC,"6,600,000"
153,Africa,Western Africa,Niger,NER,"35,000,000"
154,Africa,Western Africa,Nigeria,NGA,"31,000,000"
155,Oceania,Polynesia,Niue,NIU,"2,400,000"
156,Oceania,Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
157,Oceania,Micronesia,Northern Mariana Islands,MNP,"58,000"
158,Europe,Northern Europe,Norway,NOR,"5,400,000"
159,Asia,Western Asia,Oman,OMN,"5,000,000"
160,Asia,Southern Asia,Pakistan,PAK,"331,000,000"
161,Oceania,Micronesia,Palau,PLW,"220,000,000"
162,Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
163,Americas,Central America,Panama,PAN,"8,700,000"
164,Oceania,Melanesia,Papua New Guinea,PNG,"9,000,000"
165,Americas,South America,Paraguay,PRY,"7,100,000"
166,Americas,South America,Peru,PER,"59,000,000"
167,Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
168,Oceania,Polynesia,Pitcairn,PCN,"50,000,000"
169,Europe,Eastern Europe,Poland,POL,"67,000,000"
170,Europe,Southern Europe,Portugal,PRT,"10,400,000"
171,Americas,Caribbean,Puerto Rico,PRI,"47,000,000"
172,Asia,Western Asia,Qatar,QAT,"3,500,000"
173,Africa,Eastern Africa,Réunion,REU,"859,000"
174,Europe,Eastern Europe,Romania,ROU,"24,000,000"
175,Europe,Eastern Europe,Russian Federation,RUS,"19,000,000"
176,Africa,Eastern Africa,Rwanda,RWA,"17,500,000"
177,Americas,Caribbean,Saint Barthélemy,BLM,"9,900"
178,Africa,Western Africa,"Saint Helena, Ascension and Tristan da Cunha",SHN,"6,000"
179,Americas,Caribbean,Saint Kitts and Nevis,KNA,"53,000"
180,Americas,Caribbean,Saint Lucia,LCA,"23,800,000"
181,Americas,Caribbean,Saint Martin (French part),MAF,"7,300,000"
182,Americas,Northern America,Saint Pierre and Miquelon,SPM,"5,700"
183,Americas,Caribbean,Saint Vincent and the Grenadines,VCT,"16,400,000"
184,Oceania,Polynesia,Samoa,WSM,"26,000,000"
185,Europe,Southern Europe,San Marino,SMR,"6,600,000"
186,Africa,Middle Africa,Sao Tome and Principe,STP,"33,000,000"
187,Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
188,Africa,Western Africa,Senegal,SEN,"2,300,000"
189,Europe,Southern Europe,Serbia,SRB,"6,900,000"
190,Africa,Eastern Africa,Seychelles,SYC,"98,000"
191,Africa,Western Africa,Sierra Leone,SLE,"7,900,000"
192,Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
193,Americas,Caribbean,Sint Maarten (Dutch part),SXM,"9,300,000"
194,Europe,Eastern Europe,Slovakia,SVK,"5,500,000"
195,Europe,Southern Europe,Slovenia,SVN,"276,000,000"
196,Oceania,Melanesia,Solomon Islands,SLB,"686,000"
197,Africa,Eastern Africa,Somalia,SOM,"19,100,000"
198,Africa,Southern Africa,South Africa,ZAF,"59,000,000"
199,Africa,Eastern Africa,South Sudan,SSD,"11,900,000"
200,Europe,Southern Europe,Spain,ESP,"47,000,000"
201,Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
202,Africa,Northern Africa,Sudan,SDN,"9,600,000"
203,Americas,South America,Suriname,SUR,"591,000"
204,Europe,Northern Europe,Svalbard and Jan Mayen,SJM,"4,000,000"
205,Africa,Southern Africa,Swaziland,SWZ,"1,200,000"
206,Europe,Northern Europe,Sweden,SWE,"10,700,000"
207,Europe,Western Europe,Switzerland,CHE,"8,700,000"
208,Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
209,Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
210,Asia,Central Asia,Tajikistan,TJK,"9,500,000"
211,Africa,Eastern Africa,"Tanzania, United Republic of",TZA,"59,700,000"
212,Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
213,Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
214,Africa,Western Africa,Togo,TGO,"8,300,000"
215,Oceania,Polynesia,Tokelau,TKL,"2,000,000"
216,Oceania,Polynesia,Tonga,TON,"11,500,000"
217,Americas,Caribbean,Trinidad and Tobago,TTO,"1,900,000"
218,Africa,Northern Africa,Tunisia,TUN,"125,000,000"
219,Asia,Western Asia,Turkey,TUR,"84,000,000"
220,Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
221,Americas,Caribbean,Turks and Caicos Islands,TCA,"69,800,000"
222,Oceania,Polynesia,Tuvalu,TUV,"15,000,000"
223,Africa,Eastern Africa,Uganda,UGA,"45,700,000"
224,Europe,Eastern Europe,Ukraine,UKR,"9,900,000"
225,Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
226,Europe,Northern Europe,United Kingdom of Great Britain and Northern I...,GBR,"68,000,000"
227,Americas,Northern America,United States of America,USA,"59,700,000"
228,Americas,South America,Uruguay,URY,"5,100,000"
229,Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
230,Oceania,Melanesia,Vanuatu,VUT,"5,900,000"
231,Americas,South America,Venezuela (Bolivarian Republic of),VEN,"4,900,000"
232,Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
233,Americas,Caribbean,Virgin Islands (British),VGB,"5,800,000"
234,Americas,Caribbean,Virgin Islands (U.S.),VIR,"11,400,000"
235,Oceania,Polynesia,Wallis and Futuna,WLF,"15,900,000"
236,Africa,Northern Africa,Western Sahara,ESH,"597,000"
237,Asia,Western Asia,Yemen,YEM,"5,500,000"
238,Africa,Eastern Africa,Zambia,ZMB,"213,000,000"
239,Africa,Eastern Africa,Zimbabwe,ZWE,"19,100,000"

In [58]:
df.set_index(['continent', 'sub_region']).sort_index(ascending = (False, True))

                                                                               country  \
continent sub_region
Oceania   Australia and New Zealand                                          Australia
          Australia and New Zealand                                        New Zealand
          Australia and New Zealand                                     Norfolk Island
          Melanesia                                                               Fiji
          Melanesia                                                      New Caledonia
          Melanesia                                                   Papua New Guinea
          Melanesia                                                    Solomon Islands
          Melanesia                                                            Vanuatu
          Micronesia                                                              Guam
          Micronesia                                                          Kiribati
          Micronesia                                                  Marshall Islands
          Micronesia                                  Micronesia (Federated States of)
          Micronesia                                                             Nauru
          Micronesia                                          Northern Mariana Islands
          Micronesia                                                             Palau
          Polynesia                                                     American Samoa
          Polynesia                                                       Cook Islands
          Polynesia                                                   French Polynesia
          Polynesia                                                               Niue
          Polynesia                                                           Pitcairn
          Polynesia                                                              Samoa
          Polynesia                                                            Tokelau
          Polynesia                                                              Tonga
          Polynesia                                                             Tuvalu
          Polynesia                                                  Wallis and Futuna
Europe    Eastern Europe                                                       Belarus
          Eastern Europe                                                      Bulgaria
          Eastern Europe                                                Czech Republic
          Eastern Europe                                                       Hungary
          Eastern Europe                                         Moldova (Republic of)
          Eastern Europe                                                        Poland
          Eastern Europe                                                       Romania
          Eastern Europe                                            Russian Federation
          Eastern Europe                                                      Slovakia
          Eastern Europe                                                       Ukraine
          Northern Europe                                                Åland Islands
          Northern Europe                                                      Denmark
          Northern Europe                                                      Estonia
          Northern Europe                                                Faroe Islands
          Northern Europe                                                      Finland
          Northern Europe                                                     Guernsey
          Northern Europe                                                      Iceland
          Northern Europe                                                      Ireland
          Northern Europe                                                  Isle of Man
          Northern Europe                                                       Jersey
          Northern Europe                                                       Latvia
          Northern Europe                                                    Lithuania
          Northern Europe                                                       Norway
          Northern Europe                                       Svalbard and Jan Mayen
          Northern Europe                                                       Sweden
          Northern Europe            United Kingdom of Great Britain and Northern I...
          Southern Europe                                                      Albania
          Southern Europe                                                      Andorra
          Southern Europe                                       Bosnia and Herzegovina
          Southern Europe                                                      Croatia
          Southern Europe                                                    Gibraltar
          Southern Europe                                                       Greece
          Southern Europe                                                     Holy See
          Southern Europe                                                        Italy
          Southern Europe                  Macedonia (the former Yugoslav Republic of)
          Southern Europe                                                        Malta
          Southern Europe                                                   Montenegro
          Southern Europe                                                     Portugal
          Southern Europe                                                   San Marino
          Southern Europe                                                       Serbia
          Southern Europe                                                     Slovenia
          Southern Europe                                                        Spain
          Western Europe                                                       Austria
          Western Europe                                                       Belgium
          Western Europe                                                        France
          Western Europe                                                       Germany
          Western Europe                                                 Liechtenstein
          Western Europe                                                    Luxembourg
          Western Europe                                                        Monaco
          Western Europe                                                   Netherlands
          Western Europe                                                   Switzerland
Asia      Central Asia                                                      Kazakhstan
          Central Asia                                                      Kyrgyzstan
          Central Asia                                                      Tajikistan
          Central Asia                                                    Turkmenistan
          Central Asia                                                      Uzbekistan
          Eastern Asia                                                           China
          Eastern Asia                                                       Hong Kong
          Eastern Asia                                                           Japan
          Eastern Asia                         Korea (Democratic People's Republic of)
          Eastern Asia                                             Korea (Republic of)
          Eastern Asia                                                           Macao
          Eastern Asia                                                        Mongolia
          Eastern Asia                                       Taiwan, Province of China
          South-Eastern Asia                                         Brunei Darussalam
          South-Eastern Asia                                                  Cambodia
          South-Eastern Asia                                                 Indonesia
          South-Eastern Asia                          Lao People's Democratic Republic
          South-Eastern Asia                                                  Malaysia
          South-Eastern Asia                                                   Myanmar
          South-Eastern Asia                                               Philippines
          South-Eastern Asia                                                 Singapore
          South-Eastern Asia                                                  Thailand
          South-Eastern Asia                                               Timor-Leste
          South-Eastern Asia                                                  Viet Nam
          Southern Asia                                                    Afghanistan
          Southern Asia                                                     Bangladesh
          Southern Asia                                                         Bhutan
          Southern Asia                                                          India
          Southern Asia                                     Iran (Islamic Republic of)
          Southern Asia                                                       Maldives
          Southern Asia                                                          Nepal
          Southern Asia                                                       Pakistan
          Southern Asia                                                      Sri Lanka
          Western Asia                                                         Armenia
          Western Asia                                                      Azerbaijan
          Western Asia                                                         Bahrain
          Western Asia                                                          Cyprus
          Western Asia                                                         Georgia
          Western Asia                                                            Iraq
          Western Asia                                                          Israel
          Western Asia                                                          Jordan
          Western Asia                                                          Kuwait
          Western Asia                                                         Lebanon
          Western Asia                                                            Oman
          Western Asia                                             Palestine, State of
          Western Asia                                                           Qatar
          Western Asia                                                    Saudi Arabia
          Western Asia                                            Syrian Arab Republic
          Western Asia                                                          Turkey
          Western Asia                                            United Arab Emirates
          Western Asia                                                           Yemen
Americas  Caribbean                                                           Anguilla
          Caribbean                                                Antigua and Barbuda
          Caribbean                                                              Aruba
          Caribbean                                                            Bahamas
          Caribbean                                                           Barbados
          Caribbean                                   Bonaire, Sint Eustatius and Saba
          Caribbean                                                     Cayman Islands
          Caribbean                                                               Cuba
          Caribbean                                                            Curaçao
          Caribbean                                                           Dominica
          Caribbean                                                 Dominican Republic
          Caribbean                                                            Grenada
          Caribbean                                                         Guadeloupe
          Caribbean                                                              Haiti
          Caribbean                                                            Jamaica
          Caribbean                                                         Martinique
          Caribbean                                                         Montserrat
          Caribbean                                                        Puerto Rico
          Caribbean                                                   Saint Barthélemy
          Caribbean                                              Saint Kitts and Nevis
          Caribbean                                                        Saint Lucia
          Caribbean                                         Saint Martin (French part)
          Caribbean                                   Saint Vincent and the Grenadines
          Caribbean                                          Sint Maarten (Dutch part)
          Caribbean                                                Trinidad and Tobago
          Caribbean                                           Turks and Caicos Islands
          Caribbean                                           Virgin Islands (British)
          Caribbean                                              Virgin Islands (U.S.)
          Central America                                                       Belize
          Central America                                                   Costa Rica
          Central America                                                  El Salvador
          Central America                                                    Guatemala
          Central America                                                     Honduras
          Central America                                                       Mexico
          Central America                                                    Nicaragua
          Central America                                                       Panama
          Northern America                                                     Bermuda
          Northern America                                                      Canada
          Northern America                                                   Greenland
          Northern America                                   Saint Pierre and Miquelon
          Northern America                                    United States of America
          South America                                                      Argentina
          South America                               Bolivia (Plurinational State of)
          South America                                                         Brazil
          South America                                                          Chile
          South America                                                       Colombia
          South America                                                        Ecuador
          South America                                    Falkland Islands (Malvinas)
          South America                                                  French Guiana
          South America                                                         Guyana
          South America                                                       Paraguay
          South America                                                           Peru
          South America                                                       Suriname
          South America                                                        Uruguay
          South America                             Venezuela (Bolivarian Republic of)
Africa    Eastern Africa                                                       Burundi
          Eastern Africa                                                       Comoros
          Eastern Africa                                                      Djibouti
          Eastern Africa                                                       Eritrea
          Eastern Africa                                                      Ethiopia
          Eastern Africa                                                         Kenya
          Eastern Africa                                                    Madagascar
          Eastern Africa                                                        Malawi
          Eastern Africa                                                     Mauritius
          Eastern Africa                                                       Mayotte
          Eastern Africa                                                    Mozambique
          Eastern Africa                                                       Réunion
          Eastern Africa                                                        Rwanda
          Eastern Africa                                                    Seychelles
          Eastern Africa                                                       Somalia
          Eastern Africa                                                   South Sudan
          Eastern Africa                                  Tanzania, United Republic of
          Eastern Africa                                                        Uganda
          Eastern Africa                                                        Zambia
          Eastern Africa                                                      Zimbabwe
          Middle Africa                                                         Angola
          Middle Africa                                                       Cameroon
          Middle Africa                                       Central African Republic
          Middle Africa                                                           Chad
          Middle Africa                                                          Congo
          Middle Africa                             Congo (Democratic Republic of the)
          Middle Africa                                              Equatorial Guinea
          Middle Africa                                                          Gabon
          Middle Africa                                          Sao Tome and Principe
          Northern Africa                                                      Algeria
          Northern Africa                                                        Egypt
          Northern Africa                                                        Libya
          Northern Africa                                                      Morocco
          Northern Africa                                                        Sudan
          Northern Africa                                                      Tunisia
          Northern Africa                                               Western Sahara
          Southern Africa                                                     Botswana
          Southern Africa                                                      Lesotho
          Southern Africa                                                      Namibia
          Southern Africa                                                 South Africa
          Southern Africa                                                    Swaziland
          Western Africa                                                         Benin
          Western Africa                                                  Burkina Faso
          Western Africa                                                    Cabo Verde
          Western Africa                                                 Côte d'Ivoire
          Western Africa                                                        Gambia

In [59]:
df.set_index(['continent', 'sub_region'], inplace = True)

In [60]:
df

                                                                               country  \
continent sub_region
Asia      Southern Asia                                                    Afghanistan
Europe    Northern Europe                                                Åland Islands
          Southern Europe                                                      Albania
Africa    Northern Africa                                                      Algeria
Oceania   Polynesia                                                     American Samoa
Europe    Southern Europe                                                      Andorra
Africa    Middle Africa                                                         Angola
Americas  Caribbean                                                           Anguilla
          Caribbean                                                Antigua and Barbuda
          South America                                                      Argentina
Asia      Western Asia                                                         Armenia
Americas  Caribbean                                                              Aruba
Oceania   Australia and New Zealand                                          Australia
Europe    Western Europe                                                       Austria
Asia      Western Asia                                                      Azerbaijan
Americas  Caribbean                                                            Bahamas
Asia      Western Asia                                                         Bahrain
          Southern Asia                                                     Bangladesh
Americas  Caribbean                                                           Barbados
Europe    Eastern Europe                                                       Belarus
          Western Europe                                                       Belgium
Americas  Central America                                                       Belize
Africa    Western Africa                                                         Benin
Americas  Northern America                                                     Bermuda
Asia      Southern Asia                                                         Bhutan
Americas  South America                               Bolivia (Plurinational State of)
          Caribbean                                   Bonaire, Sint Eustatius and Saba
Europe    Southern Europe                                       Bosnia and Herzegovina
Africa    Southern Africa                                                     Botswana
Americas  South America                                                         Brazil
Asia      South-Eastern Asia                                         Brunei Darussalam
Europe    Eastern Europe                                                      Bulgaria
Africa    Western Africa                                                  Burkina Faso
          Eastern Africa                                                       Burundi
          Western Africa                                                    Cabo Verde
Asia      South-Eastern Asia                                                  Cambodia
Africa    Middle Africa                                                       Cameroon
Americas  Northern America                                                      Canada
          Caribbean                                                     Cayman Islands
Africa    Middle Africa                                       Central African Republic
          Middle Africa                                                           Chad
Americas  South America                                                          Chile
Asia      Eastern Asia                                                           China
Americas  South America                                                       Colombia
Africa    Eastern Africa                                                       Comoros
          Middle Africa                                                          Congo
          Middle Africa                             Congo (Democratic Republic of the)
Oceania   Polynesia                                                       Cook Islands
Americas  Central America                                                   Costa Rica
Africa    Western Africa                                                 Côte d'Ivoire
Europe    Southern Europe                                                      Croatia
Americas  Caribbean                                                               Cuba
          Caribbean                                                            Curaçao
Asia      Western Asia                                                          Cyprus
Europe    Eastern Europe                                                Czech Republic
          Northern Europe                                                      Denmark
Africa    Eastern Africa                                                      Djibouti
Americas  Caribbean                                                           Dominica
          Caribbean                                                 Dominican Republic
          South America                                                        Ecuador
Africa    Northern Africa                                                        Egypt
Americas  Central America                                                  El Salvador
Africa    Middle Africa                                              Equatorial Guinea
          Eastern Africa                                                       Eritrea
Europe    Northern Europe                                                      Estonia
Africa    Eastern Africa                                                      Ethiopia
Americas  South America                                    Falkland Islands (Malvinas)
Europe    Northern Europe                                                Faroe Islands
Oceania   Melanesia                                                               Fiji
Europe    Northern Europe                                                      Finland
          Western Europe                                                        France
Americas  South America                                                  French Guiana
Oceania   Polynesia                                                   French Polynesia
Africa    Middle Africa                                                          Gabon
          Western Africa                                                        Gambia
Asia      Western Asia                                                         Georgia
Europe    Western Europe                                                       Germany
Africa    Western Africa                                                         Ghana
Europe    Southern Europe                                                    Gibraltar
          Southern Europe                                                       Greece
Americas  Northern America                                                   Greenland
          Caribbean                                                            Grenada
          Caribbean                                                         Guadeloupe
Oceania   Micronesia                                                              Guam
Americas  Central America                                                    Guatemala
Europe    Northern Europe                                                     Guernsey
Africa    Western Africa                                                        Guinea
          Western Africa                                                 Guinea-Bissau
Americas  South America                                                         Guyana
          Caribbean                                                              Haiti
Europe    Southern Europe                                                     Holy See
Americas  Central America                                                     Honduras
Asia      Eastern Asia                                                       Hong Kong
Europe    Eastern Europe                                                       Hungary
          Northern Europe                                                      Iceland
Asia      Southern Asia                                                          India
          South-Eastern Asia                                                 Indonesia
          Southern Asia                                     Iran (Islamic Republic of)
          Western Asia                                                            Iraq
Europe    Northern Europe                                                      Ireland
          Northern Europe                                                  Isle of Man
Asia      Western Asia                                                          Israel
Europe    Southern Europe                                                        Italy
Americas  Caribbean                                                            Jamaica
Asia      Eastern Asia                                                           Japan
Europe    Northern Europe                                                       Jersey
Asia      Western Asia                                                          Jordan
          Central Asia                                                      Kazakhstan
Africa    Eastern Africa                                                         Kenya
Oceania   Micronesia                                                          Kiribati
Asia      Eastern Asia                         Korea (Democratic People's Republic of)
          Eastern Asia                                             Korea (Republic of)
          Western Asia                                                          Kuwait
          Central Asia                                                      Kyrgyzstan
          South-Eastern Asia                          Lao People's Democratic Republic
Europe    Northern Europe                                                       Latvia
Asia      Western Asia                                                         Lebanon
Africa    Southern Africa                                                      Lesotho
          Western Africa                                                       Liberia
          Northern Africa                                                        Libya
Europe    Western Europe                                                 Liechtenstein
          Northern Europe                                                    Lithuania
          Western Europe                                                    Luxembourg
Asia      Eastern Asia                                                           Macao
Europe    Southern Europe                  Macedonia (the former Yugoslav Republic of)
Africa    Eastern Africa                                                    Madagascar
          Eastern Africa                                                        Malawi
Asia      South-Eastern Asia                                                  Malaysia
          Southern Asia                                                       Maldives
Africa    Western Africa                                                          Mali
Europe    Southern Europe                                                        Malta
Oceania   Micronesia                                                  Marshall Islands
Americas  Caribbean                                                         Martinique
Africa    Western Africa                                                    Mauritania
          Eastern Africa                                                     Mauritius
          Eastern Africa                                                       Mayotte
Americas  Central America                                                       Mexico
Oceania   Micronesia                                  Micronesia (Federated States of)
Europe    Eastern Europe                                         Moldova (Republic of)
          Western Europe                                                        Monaco
Asia      Eastern Asia                                                        Mongolia
Europe    Southern Europe                                                   Montenegro
Americas  Caribbean                                                         Montserrat
Africa    Northern Africa                                                      Morocco
          Eastern Africa                                                    Mozambique
Asia      South-Eastern Asia                                                   Myanmar
Africa    Southern Africa                                                      Namibia
Oceania   Micronesia                                                             Nauru
Asia      Southern Asia                                                          Nepal
Europe    Western Europe                                                   Netherlands
Oceania   Melanesia                                                      New Caledonia
          Australia and New Zealand                                        New Zealand
Americas  Central America                                                    Nicaragua
Africa    Western Africa                                                         Niger
          Western Africa                                                       Nigeria
Oceania   Polynesia                                                               Niue
          Australia and New Zealand                                     Norfolk Island
          Micronesia                                          Northern Mariana Islands
Europe    Northern Europe                                                       Norway
Asia      Western Asia                                                            Oman
          Southern Asia                                                       Pakistan
Oceania   Micronesia                                                             Palau
Asia      Western Asia                                             Palestine, State of
Americas  Central America                                                       Panama
Oceania   Melanesia                                                   Papua New Guinea
Americas  South America                                                       Paraguay
          South America                                                           Peru
Asia      South-Eastern Asia                                               Philippines
Oceania   Polynesia                                                           Pitcairn
Europe    Eastern Europe                                                        Poland
          Southern Europe                                                     Portugal
Americas  Caribbean                                                        Puerto Rico
Asia      Western Asia                                                           Qatar
Africa    Eastern Africa                                                       Réunion
Europe    Eastern Europe                                                       Romania
          Eastern Europe                                            Russian Federation
Africa    Eastern Africa                                                        Rwanda
Americas  Caribbean                                                   Saint Barthélemy
Africa    Western Africa                  Saint Helena, Ascension and Tristan da Cunha
Americas  Caribbean                                              Saint Kitts and Nevis
          Caribbean                                                        Saint Lucia
          Caribbean                                         Saint Martin (French part)
          Northern America                                   Saint Pierre and Miquelon
          Caribbean                                   Saint Vincent and the Grenadines
Oceania   Polynesia                                                              Samoa
Europe    Southern Europe                                                   San Marino
Africa    Middle Africa                                          Sao Tome and Principe
Asia      Western Asia                                                    Saudi Arabia
Africa    Western Africa                                                       Senegal
Europe    Southern Europe                                                       Serbia
Africa    Eastern Africa                                                    Seychelles
          Western Africa                                                  Sierra Leone
Asia      South-Eastern Asia                                                 Singapore
Americas  Caribbean                                          Sint Maarten (Dutch part)
Europe    Eastern Europe                                                      Slovakia
          Southern Europe                                                     Slovenia
Oceania   Melanesia                                                    Solomon Islands
Africa    Eastern Africa                                                       Somalia
          Southern Africa                                                 South Africa
          Eastern Africa                                                   South Sudan
Europe    Southern Europe                                                        Spain
Asia      Southern Asia                                                      Sri Lanka
Africa    Northern Africa                                                        Sudan
Americas  South America                                                       Suriname
Europe    Northern Europe                                       Svalbard and Jan Mayen
Africa    Southern Africa                                                    Swaziland
Europe    Northern Europe                                                       Sweden
          Western Europe                                                   Switzerland
Asia      Western Asia                                            Syrian Arab Republic
          Eastern Asia                                       Taiwan, Province of China
          Central Asia                                                      Tajikistan
Africa    Eastern Africa                                  Tanzania, United Republic of
Asia      South-Eastern Asia                                                  Thailand
          South-Eastern Asia                                               Timor-Leste
Africa    Western Africa                                                          Togo
Oceania   Polynesia                                                            Tokelau
          Polynesia                                                              Tonga
Americas  Caribbean                                                Trinidad and Tobago
Africa    Northern Africa                                                      Tunisia
Asia      Western Asia                                                          Turkey
          Central Asia                                                    Turkmenistan
Americas  Caribbean                                           Turks and Caicos Islands
Oceania   Polynesia                                                             Tuvalu
Africa    Eastern Africa                                                        Uganda
Europe    Eastern Europe                                                       Ukraine
Asia      Western Asia                                            United Arab Emirates
Europe    Northern Europe            United Kingdom of Great Britain and Northern I...
Americas  Northern America                                    United States of America

In [61]:
df.swaplevel('continent','sub_region')

                                                                               country  \
sub_region                continent
Southern Asia             Asia                                             Afghanistan
Northern Europe           Europe                                         Åland Islands
Southern Europe           Europe                                               Albania
Northern Africa           Africa                                               Algeria
Polynesia                 Oceania                                       American Samoa
Southern Europe           Europe                                               Andorra
Middle Africa             Africa                                                Angola
Caribbean                 Americas                                            Anguilla
                          Americas                                 Antigua and Barbuda
South America             Americas                                           Argentina
Western Asia              Asia                                                 Armenia
Caribbean                 Americas                                               Aruba
Australia and New Zealand Oceania                                            Australia
Western Europe            Europe                                               Austria
Western Asia              Asia                                              Azerbaijan
Caribbean                 Americas                                             Bahamas
Western Asia              Asia                                                 Bahrain
Southern Asia             Asia                                              Bangladesh
Caribbean                 Americas                                            Barbados
Eastern Europe            Europe                                               Belarus
Western Europe            Europe                                               Belgium
Central America           Americas                                              Belize
Western Africa            Africa                                                 Benin
Northern America          Americas                                             Bermuda
Southern Asia             Asia                                                  Bhutan
South America             Americas                    Bolivia (Plurinational State of)
Caribbean                 Americas                    Bonaire, Sint Eustatius and Saba
Southern Europe           Europe                                Bosnia and Herzegovina
Southern Africa           Africa                                              Botswana
South America             Americas                                              Brazil
South-Eastern Asia        Asia                                       Brunei Darussalam
Eastern Europe            Europe                                              Bulgaria
Western Africa            Africa                                          Burkina Faso
Eastern Africa            Africa                                               Burundi
Western Africa            Africa                                            Cabo Verde
South-Eastern Asia        Asia                                                Cambodia
Middle Africa             Africa                                              Cameroon
Northern America          Americas                                              Canada
Caribbean                 Americas                                      Cayman Islands
Middle Africa             Africa                              Central African Republic
                          Africa                                                  Chad
South America             Americas                                               Chile
Eastern Asia              Asia                                                   China
South America             Americas                                            Colombia
Eastern Africa            Africa                                               Comoros
Middle Africa             Africa                                                 Congo
                          Africa                    Congo (Democratic Republic of the)
Polynesia                 Oceania                                         Cook Islands
Central America           Americas                                          Costa Rica
Western Africa            Africa                                         Côte d'Ivoire
Southern Europe           Europe                                               Croatia
Caribbean                 Americas                                                Cuba
                          Americas                                             Curaçao
Western Asia              Asia                                                  Cyprus
Eastern Europe            Europe                                        Czech Republic
Northern Europe           Europe                                               Denmark
Eastern Africa            Africa                                              Djibouti
Caribbean                 Americas                                            Dominica
                          Americas                                  Dominican Republic
South America             Americas                                             Ecuador
Northern Africa           Africa                                                 Egypt
Central America           Americas                                         El Salvador
Middle Africa             Africa                                     Equatorial Guinea
Eastern Africa            Africa                                               Eritrea
Northern Europe           Europe                                               Estonia
Eastern Africa            Africa                                              Ethiopia
South America             Americas                         Falkland Islands (Malvinas)
Northern Europe           Europe                                         Faroe Islands
Melanesia                 Oceania                                                 Fiji
Northern Europe           Europe                                               Finland
Western Europe            Europe                                                France
South America             Americas                                       French Guiana
Polynesia                 Oceania                                     French Polynesia
Middle Africa             Africa                                                 Gabon
Western Africa            Africa                                                Gambia
Western Asia              Asia                                                 Georgia
Western Europe            Europe                                               Germany
Western Africa            Africa                                                 Ghana
Southern Europe           Europe                                             Gibraltar
                          Europe                                                Greece
Northern America          Americas                                           Greenland
Caribbean                 Americas                                             Grenada
                          Americas                                          Guadeloupe
Micronesia                Oceania                                                 Guam
Central America           Americas                                           Guatemala
Northern Europe           Europe                                              Guernsey
Western Africa            Africa                                                Guinea
                          Africa                                         Guinea-Bissau
South America             Americas                                              Guyana
Caribbean                 Americas                                               Haiti
Southern Europe           Europe                                              Holy See
Central America           Americas                                            Honduras
Eastern Asia              Asia                                               Hong Kong
Eastern Europe            Europe                                               Hungary
Northern Europe           Europe                                               Iceland
Southern Asia             Asia                                                   India
South-Eastern Asia        Asia                                               Indonesia
Southern Asia             Asia                              Iran (Islamic Republic of)
Western Asia              Asia                                                    Iraq
Northern Europe           Europe                                               Ireland
                          Europe                                           Isle of Man
Western Asia              Asia                                                  Israel
Southern Europe           Europe                                                 Italy
Caribbean                 Americas                                             Jamaica
Eastern Asia              Asia                                                   Japan
Northern Europe           Europe                                                Jersey
Western Asia              Asia                                                  Jordan
Central Asia              Asia                                              Kazakhstan
Eastern Africa            Africa                                                 Kenya
Micronesia                Oceania                                             Kiribati
Eastern Asia              Asia                 Korea (Democratic People's Republic of)
                          Asia                                     Korea (Republic of)
Western Asia              Asia                                                  Kuwait
Central Asia              Asia                                              Kyrgyzstan
South-Eastern Asia        Asia                        Lao People's Democratic Republic
Northern Europe           Europe                                                Latvia
Western Asia              Asia                                                 Lebanon
Southern Africa           Africa                                               Lesotho
Western Africa            Africa                                               Liberia
Northern Africa           Africa                                                 Libya
Western Europe            Europe                                         Liechtenstein
Northern Europe           Europe                                             Lithuania
Western Europe            Europe                                            Luxembourg
Eastern Asia              Asia                                                   Macao
Southern Europe           Europe           Macedonia (the former Yugoslav Republic of)
Eastern Africa            Africa                                            Madagascar
                          Africa                                                Malawi
South-Eastern Asia        Asia                                                Malaysia
Southern Asia             Asia                                                Maldives
Western Africa            Africa                                                  Mali
Southern Europe           Europe                                                 Malta
Micronesia                Oceania                                     Marshall Islands
Caribbean                 Americas                                          Martinique
Western Africa            Africa                                            Mauritania
Eastern Africa            Africa                                             Mauritius
                          Africa                                               Mayotte
Central America           Americas                                              Mexico
Micronesia                Oceania                     Micronesia (Federated States of)
Eastern Europe            Europe                                 Moldova (Republic of)
Western Europe            Europe                                                Monaco
Eastern Asia              Asia                                                Mongolia
Southern Europe           Europe                                            Montenegro
Caribbean                 Americas                                          Montserrat
Northern Africa           Africa                                               Morocco
Eastern Africa            Africa                                            Mozambique
South-Eastern Asia        Asia                                                 Myanmar
Southern Africa           Africa                                               Namibia
Micronesia                Oceania                                                Nauru
Southern Asia             Asia                                                   Nepal
Western Europe            Europe                                           Netherlands
Melanesia                 Oceania                                        New Caledonia
Australia and New Zealand Oceania                                          New Zealand
Central America           Americas                                           Nicaragua
Western Africa            Africa                                                 Niger
                          Africa                                               Nigeria
Polynesia                 Oceania                                                 Niue
Australia and New Zealand Oceania                                       Norfolk Island
Micronesia                Oceania                             Northern Mariana Islands
Northern Europe           Europe                                                Norway
Western Asia              Asia                                                    Oman
Southern Asia             Asia                                                Pakistan
Micronesia                Oceania                                                Palau
Western Asia              Asia                                     Palestine, State of
Central America           Americas                                              Panama
Melanesia                 Oceania                                     Papua New Guinea
South America             Americas                                            Paraguay
                          Americas                                                Peru
South-Eastern Asia        Asia                                             Philippines
Polynesia                 Oceania                                             Pitcairn
Eastern Europe            Europe                                                Poland
Southern Europe           Europe                                              Portugal
Caribbean                 Americas                                         Puerto Rico
Western Asia              Asia                                                   Qatar
Eastern Africa            Africa                                               Réunion
Eastern Europe            Europe                                               Romania
                          Europe                                    Russian Federation
Eastern Africa            Africa                                                Rwanda
Caribbean                 Americas                                    Saint Barthélemy
Western Africa            Africa          Saint Helena, Ascension and Tristan da Cunha
Caribbean                 Americas                               Saint Kitts and Nevis
                          Americas                                         Saint Lucia
                          Americas                          Saint Martin (French part)
Northern America          Americas                           Saint Pierre and Miquelon
Caribbean                 Americas                    Saint Vincent and the Grenadines
Polynesia                 Oceania                                                Samoa
Southern Europe           Europe                                            San Marino
Middle Africa             Africa                                 Sao Tome and Principe
Western Asia              Asia                                            Saudi Arabia
Western Africa            Africa                                               Senegal
Southern Europe           Europe                                                Serbia
Eastern Africa            Africa                                            Seychelles
Western Africa            Africa                                          Sierra Leone
South-Eastern Asia        Asia                                               Singapore
Caribbean                 Americas                           Sint Maarten (Dutch part)
Eastern Europe            Europe                                              Slovakia
Southern Europe           Europe                                              Slovenia
Melanesia                 Oceania                                      Solomon Islands
Eastern Africa            Africa                                               Somalia
Southern Africa           Africa                                          South Africa
Eastern Africa            Africa                                           South Sudan
Southern Europe           Europe                                                 Spain
Southern Asia             Asia                                               Sri Lanka
Northern Africa           Africa                                                 Sudan
South America             Americas                                            Suriname
Northern Europe           Europe                                Svalbard and Jan Mayen
Southern Africa           Africa                                             Swaziland
Northern Europe           Europe                                                Sweden
Western Europe            Europe                                           Switzerland
Western Asia              Asia                                    Syrian Arab Republic
Eastern Asia              Asia                               Taiwan, Province of China
Central Asia              Asia                                              Tajikistan
Eastern Africa            Africa                          Tanzania, United Republic of
South-Eastern Asia        Asia                                                Thailand
                          Asia                                             Timor-Leste
Western Africa            Africa                                                  Togo
Polynesia                 Oceania                                              Tokelau
                          Oceania                                                Tonga
Caribbean                 Americas                                 Trinidad and Tobago
Northern Africa           Africa                                               Tunisia
Western Asia              Asia                                                  Turkey
Central Asia              Asia                                            Turkmenistan
Caribbean                 Americas                            Turks and Caicos Islands
Polynesia                 Oceania                                               Tuvalu
Eastern Africa            Africa                                                Uganda
Eastern Europe            Europe                                               Ukraine
Western Asia              Asia                                    United Arab Emirates
Northern Europe           Europe     United Kingdom of Great Britain and Northern I...
Northern America          Americas                            United States of America

Reshaping and Pivoting Indexes

In [62]:
import pandas as pd

In [67]:
df = pd.read_excel(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Indexing\Reshaping and Pivoting Indexes\tech_price.xlsx'
                  , header = [0,1], index_col = [0,1])

pd.set_option('display.max.rows', 1350)
pd.set_option('display.max.columns', 15)

In [68]:
df

                   USD                 EUR
company           open high low close open high low close
2023-01-01 Apple    89   26  68    69   37   56  11    25
           Google   66   71  26    83   96   68  91    11
           Amazon   12   43  97    75   25   25  90    43
2023-01-02 Apple    54   49  77    49   68   44  85    68
           Google   84   92  55    90   51   50  59    68
           Amazon   41   86  13    19   41   36  50    26
2023-01-03 Apple    67   47  46    70   41   62  72    49
           Google   60   70  54    71   78   47  12    57
           Amazon   71   15  47    53   86   44  68    33
2023-01-04 Apple    56   50  54    83   59   36  45    19
           Google   36   77  27    94   62   13  66    90
           Amazon   64   97  64    56   48   57  45    50
2023-01-05 Apple    34   45  60    84   24   49  63    54
           Google   69   92  14    63   21   85  80    87
           Amazon   63   75  27    43   91   63  95    30

In [71]:
df2 = df.stack()
df2

C:\Users\khairil.akub\AppData\Local\Temp\ipykernel_24488\2801194021.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df2 = df.stack()

                           USD  EUR
                  company
2023-01-01 Apple  close     69   25
                  high      26   56
                  low       68   11
                  open      89   37
           Google close     83   11
                  high      71   68
                  low       26   91
                  open      66   96
           Amazon close     75   43
                  high      43   25
                  low       97   90
                  open      12   25
2023-01-02 Apple  close     49   68
                  high      49   44
                  low       77   85
                  open      54   68
           Google close     90   68
                  high      92   50
                  low       55   59
                  open      84   51
           Amazon close     19   26
                  high      86   36
                  low       13   50
                  open      41   41
2023-01-03 Apple  close     70   49
                  high      47   62
                  low       46   72
                  open      67   41
           Google close     71   57
                  high      70   47
                  low       54   12
                  open      60   78
           Amazon close     53   33
                  high      15   44
                  low       47   68
                  open      71   86
2023-01-04 Apple  close     83   19
                  high      50   36
                  low       54   45
                  open      56   59
           Google close     94   90
                  high      77   13
                  low       27   66
                  open      36   62
           Amazon close     56   50
                  high      97   57
                  low       64   45
                  open      64   48
2023-01-05 Apple  close     84   54
                  high      45   49
                  low       60   63
                  open      34   24
           Google close     63   87
                  high      92   85
                  low       14   80
                  open      69   21
           Amazon close     43   30
                  high      75   63
                  low       27   95
                  open      63   91

In [72]:
df2.unstack()

                    USD                 EUR
company           close high low open close high low open
2023-01-01 Amazon    75   43  97   12    43   25  90   25
           Apple     69   26  68   89    25   56  11   37
           Google    83   71  26   66    11   68  91   96
2023-01-02 Amazon    19   86  13   41    26   36  50   41
           Apple     49   49  77   54    68   44  85   68
           Google    90   92  55   84    68   50  59   51
2023-01-03 Amazon    53   15  47   71    33   44  68   86
           Apple     70   47  46   67    49   62  72   41
           Google    71   70  54   60    57   47  12   78
2023-01-04 Amazon    56   97  64   64    50   57  45   48
           Apple     83   50  54   56    19   36  45   59
           Google    94   77  27   36    90   13  66   62
2023-01-05 Amazon    43   75  27   63    30   63  95   91
           Apple     84   45  60   34    54   49  63   24
           Google    63   92  14   69    87   85  80   21

In [74]:
df_world = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Indexing\Creating an Index\WorldContinents.csv',
                encoding = 'ISO-8859-1')

pd.set_option('display.max.rows', 1359)
pd.set_option('display.max.columns', 15)

In [75]:
df_world

,continent,sub_region,country,code_3,Unnamed: 4
0,Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
1,Europe,Northern Europe,Åland Islands,ALA,"5,500,000"
2,Europe,Southern Europe,Albania,ALB,"3,300,000"
3,Africa,Northern Africa,Algeria,DZA,"9,500,000"
4,Oceania,Polynesia,American Samoa,ASM,"55,000"
5,Europe,Southern Europe,Andorra,AND,"77,000"
6,Africa,Middle Africa,Angola,AGO,"54,000,000"
7,Americas,Caribbean,Anguilla,AIA,"2,100,000"
8,Americas,Caribbean,Antigua and Barbuda,ATG,"98,000"
9,Americas,South America,Argentina,ARG,"45,000,000"
10,Asia,Western Asia,Armenia,ARM,"45,700,000"
11,Americas,Caribbean,Aruba,ABW,"11,600,000"
12,Oceania,Australia and New Zealand,Australia,AUS,"36,000,000"
13,Europe,Western Europe,Austria,AUT,"9,000,000"
14,Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
15,Americas,Caribbean,Bahamas,BHS,"7,500,000"
16,Asia,Western Asia,Bahrain,BHR,"1,900,000"
17,Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
18,Americas,Caribbean,Barbados,BRB,"44,000,000"
19,Europe,Eastern Europe,Belarus,BLR,"9,400,000"
20,Europe,Western Europe,Belgium,BEL,"12,000,000"
21,Americas,Central America,Belize,BLZ,"9,000,000"
22,Africa,Western Africa,Benin,BEN,"17,400,000"
23,Americas,Northern America,Bermuda,BMU,"64,000"
24,Asia,Southern Asia,Bhutan,BTN,"771,000"
25,Americas,South America,Bolivia (Plurinational State of),BOL,"12,900,000"
26,Americas,Caribbean,"Bonaire, Sint Eustatius and Saba",BES,"4,300,000"
27,Europe,Southern Europe,Bosnia and Herzegovina,BIH,"5,000,000"
28,Africa,Southern Africa,Botswana,BWA,"29,000,000"
29,Americas,South America,Brazil,BRA,"32,700,000"
30,Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
31,Europe,Eastern Europe,Bulgaria,BGR,"6,900,000"
32,Africa,Western Africa,Burkina Faso,BFA,"31,000,000"
33,Africa,Eastern Africa,Burundi,BDI,"128,000,000"
34,Africa,Western Africa,Cabo Verde,CPV,"556,000"
35,Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
36,Africa,Middle Africa,Cameroon,CMR,"38,000,000"
37,Americas,Northern America,Canada,CAN,"60,000,000"
38,Americas,Caribbean,Cayman Islands,CYM,"66,000"
39,Africa,Middle Africa,Central African Republic,CAF,"84,000,000"
40,Africa,Middle Africa,Chad,TCD,"2,100,000"
41,Americas,South America,Chile,CHL,"25,000,000"
42,Asia,Eastern Asia,China,CHN,"1,412,000,000"
43,Americas,South America,Colombia,COL,"51,000,000"
44,Africa,Eastern Africa,Comoros,COM,"870,000"
45,Africa,Middle Africa,Congo,COG,"5,500,000"
46,Africa,Middle Africa,Congo (Democratic Republic of the),COD,"89,000,000"
47,Oceania,Polynesia,Cook Islands,COK,"206,000,000"
48,Americas,Central America,Costa Rica,CRI,"5,100,000"
49,Africa,Western Africa,Côte d'Ivoire,CIV,"38,000,000"
50,Europe,Southern Europe,Croatia,HRV,"7,900,000"
51,Americas,Caribbean,Cuba,CUB,"110,000,000"
52,Americas,Caribbean,Curaçao,CUW,"2,600,000"
53,Asia,Western Asia,Cyprus,CYP,"1,200,000"
54,Europe,Eastern Europe,Czech Republic,CZE,"102,000,000"
55,Europe,Northern Europe,Denmark,DNK,"5,800,000"
56,Africa,Eastern Africa,Djibouti,DJI,"988,000"
57,Americas,Caribbean,Dominica,DMA,"72,000"
58,Americas,Caribbean,Dominican Republic,DOM,"11,200,000"
59,Americas,South America,Ecuador,ECU,"2,900,000"
60,Africa,Northern Africa,Egypt,EGY,"11,300,000"
61,Americas,Central America,El Salvador,SLV,"6,500,000"
62,Africa,Middle Africa,Equatorial Guinea,GNQ,"1,700,000"
63,Africa,Eastern Africa,Eritrea,ERI,"5,100,000"
64,Europe,Northern Europe,Estonia,EST,"1,300,000"
65,Africa,Eastern Africa,Ethiopia,ETH,"16,700,000"
66,Americas,South America,Falkland Islands (Malvinas),FLK,"5,500,000"
67,Europe,Northern Europe,Faroe Islands,FRO,"49,000"
68,Oceania,Melanesia,Fiji,FJI,"896,000"
69,Europe,Northern Europe,Finland,FIN,"5,500,000"
70,Europe,Western Europe,France,FRA,"67,000,000"
71,Americas,South America,French Guiana,GUF,"45,000,000"
72,Oceania,Polynesia,French Polynesia,PYF,"40,000,000"
73,Africa,Middle Africa,Gabon,GAB,"28,000,000"
74,Africa,Western Africa,Gambia,GMB,"3,000,000"
75,Asia,Western Asia,Georgia,GEO,"5,400,000"
76,Europe,Western Europe,Germany,DEU,"83,200,000"
77,Africa,Western Africa,Ghana,GHA,"51,000,000"
78,Europe,Southern Europe,Gibraltar,GIB,"6,500,000"
79,Europe,Southern Europe,Greece,GRC,"10,800,000"
80,Americas,Northern America,Greenland,GRL,"56,000"
81,Americas,Caribbean,Grenada,GRD,"16,700,000"
82,Americas,Caribbean,Guadeloupe,GLP,"9,000,000"
83,Oceania,Micronesia,Guam,GUM,"2,800,000"
84,Americas,Central America,Guatemala,GTM,"21,000,000"
85,Europe,Northern Europe,Guernsey,GGY,"63,000"
86,Africa,Western Africa,Guinea,GIN,"18,700,000"
87,Africa,Western Africa,Guinea-Bissau,GNB,"10,000,000"
88,Americas,South America,Guyana,GUY,"787,000"
89,Americas,Caribbean,Haiti,HTI,"114,000,000"
90,Europe,Southern Europe,Holy See,VAT,800
91,Americas,Central America,Honduras,HND,"10,000,000"
92,Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
93,Europe,Eastern Europe,Hungary,HUN,"9,600,000"
94,Europe,Northern Europe,Iceland,ISL,"6,900,000"
95,Asia,Southern Asia,India,IND,"1,400,000,000"
96,Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
97,Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
98,Asia,Western Asia,Iraq,IRQ,"89,000,000"
99,Europe,Northern Europe,Ireland,IRL,"5,000,000"
100,Europe,Northern Europe,Isle of Man,IMN,"85,000"
101,Asia,Western Asia,Israel,ISR,"9,300,000"
102,Europe,Southern Europe,Italy,ITA,"60,000,000"
103,Americas,Caribbean,Jamaica,JAM,"3,700,000"
104,Asia,Eastern Asia,Japan,JPN,"18,000,000"
105,Europe,Northern Europe,Jersey,JEY,"11,800,000"
106,Asia,Western Asia,Jordan,JOR,"10,300,000"
107,Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
108,Africa,Eastern Africa,Kenya,KEN,"53,800,000"
109,Oceania,Micronesia,Kiribati,KIR,"17,600,000"
110,Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
111,Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
112,Asia,Western Asia,Kuwait,KWT,"8,300,000"
113,Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
114,Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
115,Europe,Northern Europe,Latvia,LVA,"10,000,000"
116,Asia,Western Asia,Lebanon,LBN,"6,800,000"
117,Africa,Southern Africa,Lesotho,LSO,"27,700,000"
118,Africa,Western Africa,Liberia,LBR,"5,000,000"
119,Africa,Northern Africa,Libya,LBY,"6,900,000"
120,Europe,Western Europe,Liechtenstein,LIE,"68,000,000"
121,Europe,Northern Europe,Lithuania,LTU,"3,500,000"
122,Europe,Western Europe,Luxembourg,LUX,"633,000"
123,Asia,Eastern Asia,Macao,MAC,"650,000"
124,Europe,Southern Europe,Macedonia (the former Yugoslav Republic of),MKD,"26,000,000"
125,Africa,Eastern Africa,Madagascar,MDG,"4,300,000"
126,Africa,Eastern Africa,Malawi,MWI,"25,800,000"
127,Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
128,Asia,Southern Asia,Maldives,MDV,"540,000"
129,Africa,Western Africa,Mali,MLI,"30,000,000"
130,Europe,Southern Europe,Malta,MLT,"97,000,000"
131,Oceania,Micronesia,Marshall Islands,MHL,"59,000"
132,Americas,Caribbean,Martinique,MTQ,"6,900,000"
133,Africa,Western Africa,Mauritania,MRT,"83,200,000"
134,Africa,Eastern Africa,Mauritius,MUS,"1,300,000"
135,Africa,Eastern Africa,Mayotte,MYT,"4,800,000"
136,Americas,Central America,Mexico,MEX,"18,400,000"
137,Oceania,Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
138,Europe,Eastern Europe,Moldova (Republic of),MDA,"3,300,000"
139,Europe,Western Europe,Monaco,MCO,"7,100,000"
140,Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
141,Europe,Southern Europe,Montenegro,MNE,"622,000"
142,Americas,Caribbean,Montserrat,MSR,"5,000"
143,Africa,Northern Africa,Morocco,MAR,"6,800,000"
144,Africa,Eastern Africa,Mozambique,MOZ,"51,600,000"
145,Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
146,Africa,Southern Africa,Namibia,NAM,"3,200,000"
147,Oceania,Micronesia,Nauru,NRU,"144,000,000"
148,Asia,Southern Asia,Nepal,NPL,"44,000,000"
149,Europe,Western Europe,Netherlands,NLD,"2,800,000"
150,Oceania,Melanesia,New Caledonia,NCL,"44,000,000"
151,Oceania,Australia and New Zealand,New Zealand,NZL,"84,000,000"
152,Americas,Central America,Nicaragua,NIC,"6,600,000"
153,Africa,Western Africa,Niger,NER,"35,000,000"
154,Africa,Western Africa,Nigeria,NGA,"31,000,000"
155,Oceania,Polynesia,Niue,NIU,"2,400,000"
156,Oceania,Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
157,Oceania,Micronesia,Northern Mariana Islands,MNP,"58,000"
158,Europe,Northern Europe,Norway,NOR,"5,400,000"
159,Asia,Western Asia,Oman,OMN,"5,000,000"
160,Asia,Southern Asia,Pakistan,PAK,"331,000,000"
161,Oceania,Micronesia,Palau,PLW,"220,000,000"
162,Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
163,Americas,Central America,Panama,PAN,"8,700,000"
164,Oceania,Melanesia,Papua New Guinea,PNG,"9,000,000"
165,Americas,South America,Paraguay,PRY,"7,100,000"
166,Americas,South America,Peru,PER,"59,000,000"
167,Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
168,Oceania,Polynesia,Pitcairn,PCN,"50,000,000"
169,Europe,Eastern Europe,Poland,POL,"67,000,000"
170,Europe,Southern Europe,Portugal,PRT,"10,400,000"
171,Americas,Caribbean,Puerto Rico,PRI,"47,000,000"
172,Asia,Western Asia,Qatar,QAT,"3,500,000"
173,Africa,Eastern Africa,Réunion,REU,"859,000"
174,Europe,Eastern Europe,Romania,ROU,"24,000,000"
175,Europe,Eastern Europe,Russian Federation,RUS,"19,000,000"
176,Africa,Eastern Africa,Rwanda,RWA,"17,500,000"
177,Americas,Caribbean,Saint Barthélemy,BLM,"9,900"
178,Africa,Western Africa,"Saint Helena, Ascension and Tristan da Cunha",SHN,"6,000"
179,Americas,Caribbean,Saint Kitts and Nevis,KNA,"53,000"
180,Americas,Caribbean,Saint Lucia,LCA,"23,800,000"
181,Americas,Caribbean,Saint Martin (French part),MAF,"7,300,000"
182,Americas,Northern America,Saint Pierre and Miquelon,SPM,"5,700"
183,Americas,Caribbean,Saint Vincent and the Grenadines,VCT,"16,400,000"
184,Oceania,Polynesia,Samoa,WSM,"26,000,000"
185,Europe,Southern Europe,San Marino,SMR,"6,600,000"
186,Africa,Middle Africa,Sao Tome and Principe,STP,"33,000,000"
187,Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
188,Africa,Western Africa,Senegal,SEN,"2,300,000"
189,Europe,Southern Europe,Serbia,SRB,"6,900,000"
190,Africa,Eastern Africa,Seychelles,SYC,"98,000"
191,Africa,Western Africa,Sierra Leone,SLE,"7,900,000"
192,Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
193,Americas,Caribbean,Sint Maarten (Dutch part),SXM,"9,300,000"
194,Europe,Eastern Europe,Slovakia,SVK,"5,500,000"
195,Europe,Southern Europe,Slovenia,SVN,"276,000,000"
196,Oceania,Melanesia,Solomon Islands,SLB,"686,000"
197,Africa,Eastern Africa,Somalia,SOM,"19,100,000"
198,Africa,Southern Africa,South Africa,ZAF,"59,000,000"
199,Africa,Eastern Africa,South Sudan,SSD,"11,900,000"
200,Europe,Southern Europe,Spain,ESP,"47,000,000"
201,Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
202,Africa,Northern Africa,Sudan,SDN,"9,600,000"
203,Americas,South America,Suriname,SUR,"591,000"
204,Europe,Northern Europe,Svalbard and Jan Mayen,SJM,"4,000,000"
205,Africa,Southern Africa,Swaziland,SWZ,"1,200,000"
206,Europe,Northern Europe,Sweden,SWE,"10,700,000"
207,Europe,Western Europe,Switzerland,CHE,"8,700,000"
208,Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
209,Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
210,Asia,Central Asia,Tajikistan,TJK,"9,500,000"
211,Africa,Eastern Africa,"Tanzania, United Republic of",TZA,"59,700,000"
212,Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
213,Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
214,Africa,Western Africa,Togo,TGO,"8,300,000"
215,Oceania,Polynesia,Tokelau,TKL,"2,000,000"
216,Oceania,Polynesia,Tonga,TON,"11,500,000"
217,Americas,Caribbean,Trinidad and Tobago,TTO,"1,900,000"
218,Africa,Northern Africa,Tunisia,TUN,"125,000,000"
219,Asia,Western Asia,Turkey,TUR,"84,000,000"
220,Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
221,Americas,Caribbean,Turks and Caicos Islands,TCA,"69,800,000"
222,Oceania,Polynesia,Tuvalu,TUV,"15,000,000"
223,Africa,Eastern Africa,Uganda,UGA,"45,700,000"
224,Europe,Eastern Europe,Ukraine,UKR,"9,900,000"
225,Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
226,Europe,Northern Europe,United Kingdom of Great Britain and Northern I...,GBR,"68,000,000"
227,Americas,Northern America,United States of America,USA,"59,700,000"
228,Americas,South America,Uruguay,URY,"5,100,000"
229,Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
230,Oceania,Melanesia,Vanuatu,VUT,"5,900,000"
231,Americas,South America,Venezuela (Bolivarian Republic of),VEN,"4,900,000"
232,Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
233,Americas,Caribbean,Virgin Islands (British),VGB,"5,800,000"
234,Americas,Caribbean,Virgin Islands (U.S.),VIR,"11,400,000"
235,Oceania,Polynesia,Wallis and Futuna,WLF,"15,900,000"
236,Africa,Northern Africa,Western Sahara,ESH,"597,000"
237,Asia,Western Asia,Yemen,YEM,"5,500,000"
238,Africa,Eastern Africa,Zambia,ZMB,"213,000,000"
239,Africa,Eastern Africa,Zimbabwe,ZWE,"19,100,000"

In [76]:
df_world.pivot(index = 'country', columns = 'continent' , values = 'sub_region')

continent,Africa,Americas,Asia,Europe,Oceania
country,,,,,
Afghanistan,NaN,NaN,Southern Asia,NaN,NaN
Albania,NaN,NaN,NaN,Southern Europe,NaN
Algeria,Northern Africa,NaN,NaN,NaN,NaN
American Samoa,NaN,NaN,NaN,NaN,Polynesia
Andorra,NaN,NaN,NaN,Southern Europe,NaN
Angola,Middle Africa,NaN,NaN,NaN,NaN
Anguilla,NaN,Caribbean,NaN,NaN,NaN
Antigua and Barbuda,NaN,Caribbean,NaN,NaN,NaN
Argentina,NaN,South America,NaN,NaN,NaN
Armenia,NaN,NaN,Western Asia,NaN,NaN
Aruba,NaN,Caribbean,NaN,NaN,NaN
Australia,NaN,NaN,NaN,NaN,Australia and New Zealand
Austria,NaN,NaN,NaN,Western Europe,NaN
Azerbaijan,NaN,NaN,Western Asia,NaN,NaN
Bahamas,NaN,Caribbean,NaN,NaN,NaN
Bahrain,NaN,NaN,Western Asia,NaN,NaN
Bangladesh,NaN,NaN,Southern Asia,NaN,NaN
Barbados,NaN,Caribbean,NaN,NaN,NaN
Belarus,NaN,NaN,NaN,Eastern Europe,NaN
Belgium,NaN,NaN,NaN,Western Europe,NaN
Belize,NaN,Central America,NaN,NaN,NaN
Benin,Western Africa,NaN,NaN,NaN,NaN
Bermuda,NaN,Northern America,NaN,NaN,NaN
Bhutan,NaN,NaN,Southern Asia,NaN,NaN
Bolivia (Plurinational State of),NaN,South America,NaN,NaN,NaN
"Bonaire, Sint Eustatius and Saba",NaN,Caribbean,NaN,NaN,NaN
Bosnia and Herzegovina,NaN,NaN,NaN,Southern Europe,NaN
Botswana,Southern Africa,NaN,NaN,NaN,NaN
Brazil,NaN,South America,NaN,NaN,NaN
Brunei Darussalam,NaN,NaN,South-Eastern Asia,NaN,NaN
Bulgaria,NaN,NaN,NaN,Eastern Europe,NaN
Burkina Faso,Western Africa,NaN,NaN,NaN,NaN
Burundi,Eastern Africa,NaN,NaN,NaN,NaN
Cabo Verde,Western Africa,NaN,NaN,NaN,NaN
Cambodia,NaN,NaN,South-Eastern Asia,NaN,NaN
Cameroon,Middle Africa,NaN,NaN,NaN,NaN
Canada,NaN,Northern America,NaN,NaN,NaN
Cayman Islands,NaN,Caribbean,NaN,NaN,NaN
Central African Republic,Middle Africa,NaN,NaN,NaN,NaN
Chad,Middle Africa,NaN,NaN,NaN,NaN
Chile,NaN,South America,NaN,NaN,NaN
China,NaN,NaN,Eastern Asia,NaN,NaN
Colombia,NaN,South America,NaN,NaN,NaN
Comoros,Eastern Africa,NaN,NaN,NaN,NaN
Congo,Middle Africa,NaN,NaN,NaN,NaN
Congo (Democratic Republic of the),Middle Africa,NaN,NaN,NaN,NaN
Cook Islands,NaN,NaN,NaN,NaN,Polynesia
Costa Rica,NaN,Central America,NaN,NaN,NaN
Croatia,NaN,NaN,NaN,Southern Europe,NaN
Cuba,NaN,Caribbean,NaN,NaN,NaN
Curaçao,NaN,Caribbean,NaN,NaN,NaN
Cyprus,NaN,NaN,Western Asia,NaN,NaN
Czech Republic,NaN,NaN,NaN,Eastern Europe,NaN
Côte d'Ivoire,Western Africa,NaN,NaN,NaN,NaN
Denmark,NaN,NaN,NaN,Northern Europe,NaN
Djibouti,Eastern Africa,NaN,NaN,NaN,NaN
Dominica,NaN,Caribbean,NaN,NaN,NaN
Dominican Republic,NaN,Caribbean,NaN,NaN,NaN
Ecuador,NaN,South America,NaN,NaN,NaN
Egypt,Northern Africa,NaN,NaN,NaN,NaN
El Salvador,NaN,Central America,NaN,NaN,NaN
Equatorial Guinea,Middle Africa,NaN,NaN,NaN,NaN
Eritrea,Eastern Africa,NaN,NaN,NaN,NaN
Estonia,NaN,NaN,NaN,Northern Europe,NaN
Ethiopia,Eastern Africa,NaN,NaN,NaN,NaN
Falkland Islands (Malvinas),NaN,South America,NaN,NaN,NaN
Faroe Islands,NaN,NaN,NaN,Northern Europe,NaN
Fiji,NaN,NaN,NaN,NaN,Melanesia
Finland,NaN,NaN,NaN,Northern Europe,NaN
France,NaN,NaN,NaN,Western Europe,NaN
French Guiana,NaN,South America,NaN,NaN,NaN
French Polynesia,NaN,NaN,NaN,NaN,Polynesia
Gabon,Middle Africa,NaN,NaN,NaN,NaN
Gambia,Western Africa,NaN,NaN,NaN,NaN
Georgia,NaN,NaN,Western Asia,NaN,NaN
Germany,NaN,NaN,NaN,Western Europe,NaN
Ghana,Western Africa,NaN,NaN,NaN,NaN
Gibraltar,NaN,NaN,NaN,Southern Europe,NaN
Greece,NaN,NaN,NaN,Southern Europe,NaN
Greenland,NaN,Northern America,NaN,NaN,NaN
Grenada,NaN,Caribbean,NaN,NaN,NaN
Guadeloupe,NaN,Caribbean,NaN,NaN,NaN
Guam,NaN,NaN,NaN,NaN,Micronesia
Guatemala,NaN,Central America,NaN,NaN,NaN
Guernsey,NaN,NaN,NaN,Northern Europe,NaN
Guinea,Western Africa,NaN,NaN,NaN,NaN
Guinea-Bissau,Western Africa,NaN,NaN,NaN,NaN
Guyana,NaN,South America,NaN,NaN,NaN
Haiti,NaN,Caribbean,NaN,NaN,NaN
Holy See,NaN,NaN,NaN,Southern Europe,NaN
Honduras,NaN,Central America,NaN,NaN,NaN
Hong Kong,NaN,NaN,Eastern Asia,NaN,NaN
Hungary,NaN,NaN,NaN,Eastern Europe,NaN
Iceland,NaN,NaN,NaN,Northern Europe,NaN
India,NaN,NaN,Southern Asia,NaN,NaN
Indonesia,NaN,NaN,South-Eastern Asia,NaN,NaN
Iran (Islamic Republic of),NaN,NaN,Southern Asia,NaN,NaN
Iraq,NaN,NaN,Western Asia,NaN,NaN
Ireland,NaN,NaN,NaN,Northern Europe,NaN
Isle of Man,NaN,NaN,NaN,Northern Europe,NaN
Israel,NaN,NaN,Western Asia,NaN,NaN
Italy,NaN,NaN,NaN,Southern Europe,NaN
Jamaica,NaN,Caribbean,NaN,NaN,NaN
Japan,NaN,NaN,Eastern Asia,NaN,NaN
Jersey,NaN,NaN,NaN,Northern Europe,NaN
Jordan,NaN,NaN,Western Asia,NaN,NaN
Kazakhstan,NaN,NaN,Central Asia,NaN,NaN
Kenya,Eastern Africa,NaN,NaN,NaN,NaN
Kiribati,NaN,NaN,NaN,NaN,Micronesia
Korea (Democratic People's Republic of),NaN,NaN,Eastern Asia,NaN,NaN
Korea (Republic of),NaN,NaN,Eastern Asia,NaN,NaN
Kuwait,NaN,NaN,Western Asia,NaN,NaN
Kyrgyzstan,NaN,NaN,Central Asia,NaN,NaN
Lao People's Democratic Republic,NaN,NaN,South-Eastern Asia,NaN,NaN
Latvia,NaN,NaN,NaN,Northern Europe,NaN
Lebanon,NaN,NaN,Western Asia,NaN,NaN
Lesotho,Southern Africa,NaN,NaN,NaN,NaN
Liberia,Western Africa,NaN,NaN,NaN,NaN
Libya,Northern Africa,NaN,NaN,NaN,NaN
Liechtenstein,NaN,NaN,NaN,Western Europe,NaN
Lithuania,NaN,NaN,NaN,Northern Europe,NaN
Luxembourg,NaN,NaN,NaN,Western Europe,NaN
Macao,NaN,NaN,Eastern Asia,NaN,NaN
Macedonia (the former Yugoslav Republic of),NaN,NaN,NaN,Southern Europe,NaN
Madagascar,Eastern Africa,NaN,NaN,NaN,NaN
Malawi,Eastern Africa,NaN,NaN,NaN,NaN
Malaysia,NaN,NaN,South-Eastern Asia,NaN,NaN
Maldives,NaN,NaN,Southern Asia,NaN,NaN
Mali,Western Africa,NaN,NaN,NaN,NaN
Malta,NaN,NaN,NaN,Southern Europe,NaN
Marshall Islands,NaN,NaN,NaN,NaN,Micronesia
Martinique,NaN,Caribbean,NaN,NaN,NaN
Mauritania,Western Africa,NaN,NaN,NaN,NaN
Mauritius,Eastern Africa,NaN,NaN,NaN,NaN
Mayotte,Eastern Africa,NaN,NaN,NaN,NaN
Mexico,NaN,Central America,NaN,NaN,NaN
Micronesia (Federated States of),NaN,NaN,NaN,NaN,Micronesia
Moldova (Republic of),NaN,NaN,NaN,Eastern Europe,NaN
Monaco,NaN,NaN,NaN,Western Europe,NaN
Mongolia,NaN,NaN,Eastern Asia,NaN,NaN
Montenegro,NaN,NaN,NaN,Southern Europe,NaN
Montserrat,NaN,Caribbean,NaN,NaN,NaN
Morocco,Northern Africa,NaN,NaN,NaN,NaN
Mozambique,Eastern Africa,NaN,NaN,NaN,NaN
Myanmar,NaN,NaN,South-Eastern Asia,NaN,NaN
Namibia,Southern Africa,NaN,NaN,NaN,NaN
Nauru,NaN,NaN,NaN,NaN,Micronesia
Nepal,NaN,NaN,Southern Asia,NaN,NaN
Netherlands,NaN,NaN,NaN,Western Europe,NaN
New Caledonia,NaN,NaN,NaN,NaN,Melanesia
New Zealand,NaN,NaN,NaN,NaN,Australia and New Zealand
Nicaragua,NaN,Central America,NaN,NaN,NaN
Niger,Western Africa,NaN,NaN,NaN,NaN
Nigeria,Western Africa,NaN,NaN,NaN,NaN
Niue,NaN,NaN,NaN,NaN,Polynesia
Norfolk Island,NaN,NaN,NaN,NaN,Australia and New Zealand
Northern Mariana Islands,NaN,NaN,NaN,NaN,Micronesia
Norway,NaN,NaN,NaN,Northern Europe,NaN
Oman,NaN,NaN,Western Asia,NaN,NaN
Pakistan,NaN,NaN,Southern Asia,NaN,NaN
Palau,NaN,NaN,NaN,NaN,Micronesia
"Palestine, State of",NaN,NaN,Western Asia,NaN,NaN
Panama,NaN,Central America,NaN,NaN,NaN
Papua New Guinea,NaN,NaN,NaN,NaN,Melanesia
Paraguay,NaN,South America,NaN,NaN,NaN
Peru,NaN,South America,NaN,NaN,NaN
Philippines,NaN,NaN,South-Eastern Asia,NaN,NaN
Pitcairn,NaN,NaN,NaN,NaN,Polynesia
Poland,NaN,NaN,NaN,Eastern Europe,NaN
Portugal,NaN,NaN,NaN,Southern Europe,NaN
Puerto Rico,NaN,Caribbean,NaN,NaN,NaN
Qatar,NaN,NaN,Western Asia,NaN,NaN
Romania,NaN,NaN,NaN,Eastern Europe,NaN
Russian Federation,NaN,NaN,NaN,Eastern Europe,NaN
Rwanda,Eastern Africa,NaN,NaN,NaN,NaN
Réunion,Eastern Africa,NaN,NaN,NaN,NaN
Saint Barthélemy,NaN,Caribbean,NaN,NaN,NaN
"Saint Helena, Ascension and Tristan da Cunha",Western Africa,NaN,NaN,NaN,NaN
Saint Kitts and Nevis,NaN,Caribbean,NaN,NaN,NaN
Saint Lucia,NaN,Caribbean,NaN,NaN,NaN
Saint Martin (French part),NaN,Caribbean,NaN,NaN,NaN
Saint Pierre and Miquelon,NaN,Northern America,NaN,NaN,NaN
Saint Vincent and the Grenadines,NaN,Caribbean,NaN,NaN,NaN
Samoa,NaN,NaN,NaN,NaN,Polynesia
San Marino,NaN,NaN,NaN,Southern Europe,NaN
Sao Tome and Principe,Middle Africa,NaN,NaN,NaN,NaN
Saudi Arabia,NaN,NaN,Western Asia,NaN,NaN
Senegal,Western Africa,NaN,NaN,NaN,NaN
Serbia,NaN,NaN,NaN,Southern Europe,NaN
Seychelles,Eastern Africa,NaN,NaN,NaN,NaN
Sierra Leone,Western Africa,NaN,NaN,NaN,NaN
Singapore,NaN,NaN,South-Eastern Asia,NaN,NaN
Sint Maarten (Dutch part),NaN,Caribbean,NaN,NaN,NaN
Slovakia,NaN,NaN,NaN,Eastern Europe,NaN
Slovenia,NaN,NaN,NaN,Southern Europe,NaN
Solomon Islands,NaN,NaN,NaN,NaN,Melanesia
Somalia,Eastern Africa,NaN,NaN,NaN,NaN
South Africa,Southern Africa,NaN,NaN,NaN,NaN
South Sudan,Eastern Africa,NaN,NaN,NaN,NaN
Spain,NaN,NaN,NaN,Southern Europe,NaN
Sri Lanka,NaN,NaN,Southern Asia,NaN,NaN
Sudan,Northern Africa,NaN,NaN,NaN,NaN
Suriname,NaN,South America,NaN,NaN,NaN
Svalbard and Jan Mayen,NaN,NaN,NaN,Northern Europe,NaN
Swaziland,Southern Africa,NaN,NaN,NaN,NaN
Sweden,NaN,NaN,NaN,Northern Europe,NaN
Switzerland,NaN,NaN,NaN,Western Europe,NaN
Syrian Arab Republic,NaN,NaN,Western Asia,NaN,NaN
"Taiwan, Province of China",NaN,NaN,Eastern Asia,NaN,NaN
Tajikistan,NaN,NaN,Central Asia,NaN,NaN
"Tanzania, United Republic of",Eastern Africa,NaN,NaN,NaN,NaN
Thailand,NaN,NaN,South-Eastern Asia,NaN,NaN
Timor-Leste,NaN,NaN,South-Eastern Asia,NaN,NaN
Togo,Western Africa,NaN,NaN,NaN,NaN
Tokelau,NaN,NaN,NaN,NaN,Polynesia
Tonga,NaN,NaN,NaN,NaN,Polynesia
Trinidad and Tobago,NaN,Caribbean,NaN,NaN,NaN
Tunisia,Northern Africa,NaN,NaN,NaN,NaN
Turkey,NaN,NaN,Western Asia,NaN,NaN
Turkmenistan,NaN,NaN,Central Asia,NaN,NaN
Turks and Caicos Islands,NaN,Caribbean,NaN,NaN,NaN
Tuvalu,NaN,NaN,NaN,NaN,Polynesia
Uganda,Eastern Africa,NaN,NaN,NaN,NaN
Ukraine,NaN,NaN,NaN,Eastern Europe,NaN
United Arab Emirates,NaN,NaN,Western Asia,NaN,NaN
United Kingdom of Great Britain and Northern Ireland,NaN,NaN,NaN,Northern Europe,NaN
United States of America,NaN,Northern America,NaN,NaN,NaN
Uruguay,NaN,South America,NaN,NaN,NaN
Uzbekistan,NaN,NaN,Central Asia,NaN,NaN
Vanuatu,NaN,NaN,NaN,NaN,Melanesia
Venezuela (Bolivarian Republic of),NaN,South America,NaN,NaN,NaN
Viet Nam,NaN,NaN,South-Eastern Asia,NaN,NaN
Virgin Islands (British),NaN,Caribbean,NaN,NaN,NaN
Virgin Islands (U.S.),NaN,Caribbean,NaN,NaN,NaN
Wallis and Futuna,NaN,NaN,NaN,NaN,Polynesia
Western Sahara,Northern Africa,NaN,NaN,NaN,NaN
Yemen,NaN,NaN,Western Asia,NaN,NaN
Zambia,Eastern Africa,NaN,NaN,NaN,NaN
Zimbabwe,Eastern Africa,NaN,NaN,NaN,NaN
Åland Islands,NaN,NaN,NaN,Northern Europe,NaN

In [77]:
df_world.pivot(index = 'country', columns = 'continent' , values = 'Unnamed: 4')

continent,Africa,Americas,Asia,Europe,Oceania
country,,,,,
Afghanistan,NaN,NaN,"6,900,000",NaN,NaN
Albania,NaN,NaN,NaN,"3,300,000",NaN
Algeria,"9,500,000",NaN,NaN,NaN,NaN
American Samoa,NaN,NaN,NaN,NaN,"55,000"
Andorra,NaN,NaN,NaN,"77,000",NaN
Angola,"54,000,000",NaN,NaN,NaN,NaN
Anguilla,NaN,"2,100,000",NaN,NaN,NaN
Antigua and Barbuda,NaN,"98,000",NaN,NaN,NaN
Argentina,NaN,"45,000,000",NaN,NaN,NaN
Armenia,NaN,NaN,"45,700,000",NaN,NaN
Aruba,NaN,"11,600,000",NaN,NaN,NaN
Australia,NaN,NaN,NaN,NaN,"36,000,000"
Austria,NaN,NaN,NaN,"9,000,000",NaN
Azerbaijan,NaN,NaN,"10,000,000",NaN,NaN
Bahamas,NaN,"7,500,000",NaN,NaN,NaN
Bahrain,NaN,NaN,"1,900,000",NaN,NaN
Bangladesh,NaN,NaN,"2,500,000",NaN,NaN
Barbados,NaN,"44,000,000",NaN,NaN,NaN
Belarus,NaN,NaN,NaN,"9,400,000",NaN
Belgium,NaN,NaN,NaN,"12,000,000",NaN
Belize,NaN,"9,000,000",NaN,NaN,NaN
Benin,"17,400,000",NaN,NaN,NaN,NaN
Bermuda,NaN,"64,000",NaN,NaN,NaN
Bhutan,NaN,NaN,"771,000",NaN,NaN
Bolivia (Plurinational State of),NaN,"12,900,000",NaN,NaN,NaN
"Bonaire, Sint Eustatius and Saba",NaN,"4,300,000",NaN,NaN,NaN
Bosnia and Herzegovina,NaN,NaN,NaN,"5,000,000",NaN
Botswana,"29,000,000",NaN,NaN,NaN,NaN
Brazil,NaN,"32,700,000",NaN,NaN,NaN
Brunei Darussalam,NaN,NaN,"9,400,000",NaN,NaN
Bulgaria,NaN,NaN,NaN,"6,900,000",NaN
Burkina Faso,"31,000,000",NaN,NaN,NaN,NaN
Burundi,"128,000,000",NaN,NaN,NaN,NaN
Cabo Verde,"556,000",NaN,NaN,NaN,NaN
Cambodia,NaN,NaN,"2,200,000",NaN,NaN
Cameroon,"38,000,000",NaN,NaN,NaN,NaN
Canada,NaN,"60,000,000",NaN,NaN,NaN
Cayman Islands,NaN,"66,000",NaN,NaN,NaN
Central African Republic,"84,000,000",NaN,NaN,NaN,NaN
Chad,"2,100,000",NaN,NaN,NaN,NaN
Chile,NaN,"25,000,000",NaN,NaN,NaN
China,NaN,NaN,"1,412,000,000",NaN,NaN
Colombia,NaN,"51,000,000",NaN,NaN,NaN
Comoros,"870,000",NaN,NaN,NaN,NaN
Congo,"5,500,000",NaN,NaN,NaN,NaN
Congo (Democratic Republic of the),"89,000,000",NaN,NaN,NaN,NaN
Cook Islands,NaN,NaN,NaN,NaN,"206,000,000"
Costa Rica,NaN,"5,100,000",NaN,NaN,NaN
Croatia,NaN,NaN,NaN,"7,900,000",NaN
Cuba,NaN,"110,000,000",NaN,NaN,NaN
Curaçao,NaN,"2,600,000",NaN,NaN,NaN
Cyprus,NaN,NaN,"1,200,000",NaN,NaN
Czech Republic,NaN,NaN,NaN,"102,000,000",NaN
Côte d'Ivoire,"38,000,000",NaN,NaN,NaN,NaN
Denmark,NaN,NaN,NaN,"5,800,000",NaN
Djibouti,"988,000",NaN,NaN,NaN,NaN
Dominica,NaN,"72,000",NaN,NaN,NaN
Dominican Republic,NaN,"11,200,000",NaN,NaN,NaN
Ecuador,NaN,"2,900,000",NaN,NaN,NaN
Egypt,"11,300,000",NaN,NaN,NaN,NaN
El Salvador,NaN,"6,500,000",NaN,NaN,NaN
Equatorial Guinea,"1,700,000",NaN,NaN,NaN,NaN
Eritrea,"5,100,000",NaN,NaN,NaN,NaN
Estonia,NaN,NaN,NaN,"1,300,000",NaN
Ethiopia,"16,700,000",NaN,NaN,NaN,NaN
Falkland Islands (Malvinas),NaN,"5,500,000",NaN,NaN,NaN
Faroe Islands,NaN,NaN,NaN,"49,000",NaN
Fiji,NaN,NaN,NaN,NaN,"896,000"
Finland,NaN,NaN,NaN,"5,500,000",NaN
France,NaN,NaN,NaN,"67,000,000",NaN
French Guiana,NaN,"45,000,000",NaN,NaN,NaN
French Polynesia,NaN,NaN,NaN,NaN,"40,000,000"
Gabon,"28,000,000",NaN,NaN,NaN,NaN
Gambia,"3,000,000",NaN,NaN,NaN,NaN
Georgia,NaN,NaN,"5,400,000",NaN,NaN
Germany,NaN,NaN,NaN,"83,200,000",NaN
Ghana,"51,000,000",NaN,NaN,NaN,NaN
Gibraltar,NaN,NaN,NaN,"6,500,000",NaN
Greece,NaN,NaN,NaN,"10,800,000",NaN
Greenland,NaN,"56,000",NaN,NaN,NaN
Grenada,NaN,"16,700,000",NaN,NaN,NaN
Guadeloupe,NaN,"9,000,000",NaN,NaN,NaN
Guam,NaN,NaN,NaN,NaN,"2,800,000"
Guatemala,NaN,"21,000,000",NaN,NaN,NaN
Guernsey,NaN,NaN,NaN,"63,000",NaN
Guinea,"18,700,000",NaN,NaN,NaN,NaN
Guinea-Bissau,"10,000,000",NaN,NaN,NaN,NaN
Guyana,NaN,"787,000",NaN,NaN,NaN
Haiti,NaN,"114,000,000",NaN,NaN,NaN
Holy See,NaN,NaN,NaN,800,NaN
Honduras,NaN,"10,000,000",NaN,NaN,NaN
Hong Kong,NaN,NaN,"7,500,000",NaN,NaN
Hungary,NaN,NaN,NaN,"9,600,000",NaN
Iceland,NaN,NaN,NaN,"6,900,000",NaN
India,NaN,NaN,"1,400,000,000",NaN,NaN
Indonesia,NaN,NaN,"4,600,000",NaN,NaN
Iran (Islamic Republic of),NaN,NaN,"84,000,000",NaN,NaN
Iraq,NaN,NaN,"89,000,000",NaN,NaN
Ireland,NaN,NaN,NaN,"5,000,000",NaN
Isle of Man,NaN,NaN,NaN,"85,000",NaN
Israel,NaN,NaN,"9,300,000",NaN,NaN
Italy,NaN,NaN,NaN,"60,000,000",NaN
Jamaica,NaN,"3,700,000",NaN,NaN,NaN
Japan,NaN,NaN,"18,000,000",NaN,NaN
Jersey,NaN,NaN,NaN,"11,800,000",NaN
Jordan,NaN,NaN,"10,300,000",NaN,NaN
Kazakhstan,NaN,NaN,"22,000,000",NaN,NaN
Kenya,"53,800,000",NaN,NaN,NaN,NaN
Kiribati,NaN,NaN,NaN,NaN,"17,600,000"
Korea (Democratic People's Republic of),NaN,NaN,"38,000,000",NaN,NaN
Korea (Republic of),NaN,NaN,"51,600,000",NaN,NaN
Kuwait,NaN,NaN,"8,300,000",NaN,NaN
Kyrgyzstan,NaN,NaN,"6,600,000",NaN,NaN
Lao People's Democratic Republic,NaN,NaN,"7,300,000",NaN,NaN
Latvia,NaN,NaN,NaN,"10,000,000",NaN
Lebanon,NaN,NaN,"6,800,000",NaN,NaN
Lesotho,"27,700,000",NaN,NaN,NaN,NaN
Liberia,"5,000,000",NaN,NaN,NaN,NaN
Libya,"6,900,000",NaN,NaN,NaN,NaN
Liechtenstein,NaN,NaN,NaN,"68,000,000",NaN
Lithuania,NaN,NaN,NaN,"3,500,000",NaN
Luxembourg,NaN,NaN,NaN,"633,000",NaN
Macao,NaN,NaN,"650,000",NaN,NaN
Macedonia (the former Yugoslav Republic of),NaN,NaN,NaN,"26,000,000",NaN
Madagascar,"4,300,000",NaN,NaN,NaN,NaN
Malawi,"25,800,000",NaN,NaN,NaN,NaN
Malaysia,NaN,NaN,"53,800,000",NaN,NaN
Maldives,NaN,NaN,"540,000",NaN,NaN
Mali,"30,000,000",NaN,NaN,NaN,NaN
Malta,NaN,NaN,NaN,"97,000,000",NaN
Marshall Islands,NaN,NaN,NaN,NaN,"59,000"
Martinique,NaN,"6,900,000",NaN,NaN,NaN
Mauritania,"83,200,000",NaN,NaN,NaN,NaN
Mauritius,"1,300,000",NaN,NaN,NaN,NaN
Mayotte,"4,800,000",NaN,NaN,NaN,NaN
Mexico,NaN,"18,400,000",NaN,NaN,NaN
Micronesia (Federated States of),NaN,NaN,NaN,NaN,"164,000,000"
Moldova (Republic of),NaN,NaN,NaN,"3,300,000",NaN
Monaco,NaN,NaN,NaN,"7,100,000",NaN
Mongolia,NaN,NaN,"5,000,000",NaN,NaN
Montenegro,NaN,NaN,NaN,"622,000",NaN
Montserrat,NaN,"5,000",NaN,NaN,NaN
Morocco,"6,800,000",NaN,NaN,NaN,NaN
Mozambique,"51,600,000",NaN,NaN,NaN,NaN
Myanmar,NaN,NaN,"54,000,000",NaN,NaN
Namibia,"3,200,000",NaN,NaN,NaN,NaN
Nauru,NaN,NaN,NaN,NaN,"144,000,000"
Nepal,NaN,NaN,"44,000,000",NaN,NaN
Netherlands,NaN,NaN,NaN,"2,800,000",NaN
New Caledonia,NaN,NaN,NaN,NaN,"44,000,000"
New Zealand,NaN,NaN,NaN,NaN,"84,000,000"
Nicaragua,NaN,"6,600,000",NaN,NaN,NaN
Niger,"35,000,000",NaN,NaN,NaN,NaN
Nigeria,"31,000,000",NaN,NaN,NaN,NaN
Niue,NaN,NaN,NaN,NaN,"2,400,000"
Norfolk Island,NaN,NaN,NaN,NaN,"20,300,000"
Northern Mariana Islands,NaN,NaN,NaN,NaN,"58,000"
Norway,NaN,NaN,NaN,"5,400,000",NaN
Oman,NaN,NaN,"5,000,000",NaN,NaN
Pakistan,NaN,NaN,"331,000,000",NaN,NaN
Palau,NaN,NaN,NaN,NaN,"220,000,000"
"Palestine, State of",NaN,NaN,"5,100,000",NaN,NaN
Panama,NaN,"8,700,000",NaN,NaN,NaN
Papua New Guinea,NaN,NaN,NaN,NaN,"9,000,000"
Paraguay,NaN,"7,100,000",NaN,NaN,NaN
Peru,NaN,"59,000,000",NaN,NaN,NaN
Philippines,NaN,NaN,"13,100,000",NaN,NaN
Pitcairn,NaN,NaN,NaN,NaN,"50,000,000"
Poland,NaN,NaN,NaN,"67,000,000",NaN
Portugal,NaN,NaN,NaN,"10,400,000",NaN
Puerto Rico,NaN,"47,000,000",NaN,NaN,NaN
Qatar,NaN,NaN,"3,500,000",NaN,NaN
Romania,NaN,NaN,NaN,"24,000,000",NaN
Russian Federation,NaN,NaN,NaN,"19,000,000",NaN
Rwanda,"17,500,000",NaN,NaN,NaN,NaN
Réunion,"859,000",NaN,NaN,NaN,NaN
Saint Barthélemy,NaN,"9,900",NaN,NaN,NaN
"Saint Helena, Ascension and Tristan da Cunha","6,000",NaN,NaN,NaN,NaN
Saint Kitts and Nevis,NaN,"53,000",NaN,NaN,NaN
Saint Lucia,NaN,"23,800,000",NaN,NaN,NaN
Saint Martin (French part),NaN,"7,300,000",NaN,NaN,NaN
Saint Pierre and Miquelon,NaN,"5,700",NaN,NaN,NaN
Saint Vincent and the Grenadines,NaN,"16,400,000",NaN,NaN,NaN
Samoa,NaN,NaN,NaN,NaN,"26,000,000"
San Marino,NaN,NaN,NaN,"6,600,000",NaN
Sao Tome and Principe,"33,000,000",NaN,NaN,NaN,NaN
Saudi Arabia,NaN,NaN,"6,600,000",NaN,NaN
Senegal,"2,300,000",NaN,NaN,NaN,NaN
Serbia,NaN,NaN,NaN,"6,900,000",NaN
Seychelles,"98,000",NaN,NaN,NaN,NaN
Sierra Leone,"7,900,000",NaN,NaN,NaN,NaN
Singapore,NaN,NaN,"5,900,000",NaN,NaN
Sint Maarten (Dutch part),NaN,"9,300,000",NaN,NaN,NaN
Slovakia,NaN,NaN,NaN,"5,500,000",NaN
Slovenia,NaN,NaN,NaN,"276,000,000",NaN
Solomon Islands,NaN,NaN,NaN,NaN,"686,000"
Somalia,"19,100,000",NaN,NaN,NaN,NaN
South Africa,"59,000,000",NaN,NaN,NaN,NaN
South Sudan,"11,900,000",NaN,NaN,NaN,NaN
Spain,NaN,NaN,NaN,"47,000,000",NaN
Sri Lanka,NaN,NaN,"33,000,000",NaN,NaN
Sudan,"9,600,000",NaN,NaN,NaN,NaN
Suriname,NaN,"591,000",NaN,NaN,NaN
Svalbard and Jan Mayen,NaN,NaN,NaN,"4,000,000",NaN
Swaziland,"1,200,000",NaN,NaN,NaN,NaN
Sweden,NaN,NaN,NaN,"10,700,000",NaN
Switzerland,NaN,NaN,NaN,"8,700,000",NaN
Syrian Arab Republic,NaN,NaN,"2,800,000",NaN,NaN
"Taiwan, Province of China",NaN,NaN,"34,000,000",NaN,NaN
Tajikistan,NaN,NaN,"9,500,000",NaN,NaN
"Tanzania, United Republic of","59,700,000",NaN,NaN,NaN,NaN
Thailand,NaN,NaN,"69,800,000",NaN,NaN
Timor-Leste,NaN,NaN,"1,300,000",NaN,NaN
Togo,"8,300,000",NaN,NaN,NaN,NaN
Tokelau,NaN,NaN,NaN,NaN,"2,000,000"
Tonga,NaN,NaN,NaN,NaN,"11,500,000"
Trinidad and Tobago,NaN,"1,900,000",NaN,NaN,NaN
Tunisia,"125,000,000",NaN,NaN,NaN,NaN
Turkey,NaN,NaN,"84,000,000",NaN,NaN
Turkmenistan,NaN,NaN,"6,000,000",NaN,NaN
Turks and Caicos Islands,NaN,"69,800,000",NaN,NaN,NaN
Tuvalu,NaN,NaN,NaN,NaN,"15,000,000"
Uganda,"45,700,000",NaN,NaN,NaN,NaN
Ukraine,NaN,NaN,NaN,"9,900,000",NaN
United Arab Emirates,NaN,NaN,"9,900,000",NaN,NaN
United Kingdom of Great Britain and Northern Ireland,NaN,NaN,NaN,"68,000,000",NaN
United States of America,NaN,"59,700,000",NaN,NaN,NaN
Uruguay,NaN,"5,100,000",NaN,NaN,NaN
Uzbekistan,NaN,NaN,"6,000,000",NaN,NaN
Vanuatu,NaN,NaN,NaN,NaN,"5,900,000"
Venezuela (Bolivarian Republic of),NaN,"4,900,000",NaN,NaN,NaN
Viet Nam,NaN,NaN,"97,000,000",NaN,NaN
Virgin Islands (British),NaN,"5,800,000",NaN,NaN,NaN
Virgin Islands (U.S.),NaN,"11,400,000",NaN,NaN,NaN
Wallis and Futuna,NaN,NaN,NaN,NaN,"15,900,000"
Western Sahara,"597,000",NaN,NaN,NaN,NaN
Yemen,NaN,NaN,"5,500,000",NaN,NaN
Zambia,"213,000,000",NaN,NaN,NaN,NaN
Zimbabwe,"19,100,000",NaN,NaN,NaN,NaN
Åland Islands,NaN,NaN,NaN,"5,500,000",NaN

In [79]:
df_world.pivot(index = 'country', columns = ['continent', 'sub_region'] , values = 'Unnamed: 4')

continent                                                      Asia  \
sub_region                                            Southern Asia
country
Afghanistan                                              6,900,000
Albania                                                         NaN
Algeria                                                         NaN
American Samoa                                                  NaN
Andorra                                                         NaN
Angola                                                          NaN
Anguilla                                                        NaN
Antigua and Barbuda                                             NaN
Argentina                                                       NaN
Armenia                                                         NaN
Aruba                                                           NaN
Australia                                                       NaN
Austria                                                         NaN
Azerbaijan                                                      NaN
Bahamas                                                         NaN
Bahrain                                                         NaN
Bangladesh                                               2,500,000
Barbados                                                        NaN
Belarus                                                         NaN
Belgium                                                         NaN
Belize                                                          NaN
Benin                                                           NaN
Bermuda                                                         NaN
Bhutan                                                     771,000
Bolivia (Plurinational State of)                                NaN
Bonaire, Sint Eustatius and Saba                                NaN
Bosnia and Herzegovina                                          NaN
Botswana                                                        NaN
Brazil                                                          NaN
Brunei Darussalam                                               NaN
Bulgaria                                                        NaN
Burkina Faso                                                    NaN
Burundi                                                         NaN
Cabo Verde                                                      NaN
Cambodia                                                        NaN
Cameroon                                                        NaN
Canada                                                          NaN
Cayman Islands                                                  NaN
Central African Republic                                        NaN
Chad                                                            NaN
Chile                                                           NaN
China                                                           NaN
Colombia                                                        NaN
Comoros                                                         NaN
Congo                                                           NaN
Congo (Democratic Republic of the)                              NaN
Cook Islands                                                    NaN
Costa Rica                                                      NaN
Croatia                                                         NaN
Cuba                                                            NaN
Curaçao                                                         NaN
Cyprus                                                          NaN
Czech Republic                                                  NaN
Côte d'Ivoire                                                   NaN
Denmark                                                         NaN
Djibouti                                                        NaN
Dominica                                                        NaN
Dominican Republic                                              NaN
Ecuador                                                         NaN
Egypt                                                           NaN
El Salvador                                                     NaN
Equatorial Guinea                                               NaN
Eritrea                                                         NaN
Estonia                                                         NaN
Ethiopia                                                        NaN
Falkland Islands (Malvinas)                                     NaN
Faroe Islands                                                   NaN
Fiji                                                            NaN
Finland                                                         NaN
France                                                          NaN
French Guiana                                                   NaN
French Polynesia                                                NaN
Gabon                                                           NaN
Gambia                                                          NaN
Georgia                                                         NaN
Germany                                                         NaN
Ghana                                                           NaN
Gibraltar                                                       NaN
Greece                                                          NaN
Greenland                                                       NaN
Grenada                                                         NaN
Guadeloupe                                                      NaN
Guam                                                            NaN
Guatemala                                                       NaN
Guernsey                                                        NaN
Guinea                                                          NaN
Guinea-Bissau                                                   NaN
Guyana                                                          NaN
Haiti                                                           NaN
Holy See                                                        NaN
Honduras                                                        NaN
Hong Kong                                                       NaN
Hungary                                                         NaN
Iceland                                                         NaN
India                                                1,400,000,000
Indonesia                                                       NaN
Iran (Islamic Republic of)                              84,000,000
Iraq                                                            NaN
Ireland                                                         NaN
Isle of Man                                                     NaN
Israel                                                          NaN
Italy                                                           NaN
Jamaica                                                         NaN
Japan                                                           NaN
Jersey                                                          NaN
Jordan                                                          NaN
Kazakhstan                                                      NaN
Kenya                                                           NaN
Kiribati                                                        NaN
Korea (Democratic People's Republic of)                         NaN
Korea (Republic of)                                             NaN
Kuwait                                                          NaN
Kyrgyzstan                                                      NaN
Lao People's Democratic Republic                                NaN
Latvia                                                          NaN
Lebanon                                                         NaN
Lesotho                                                         NaN
Liberia                                                         NaN
Libya                                                           NaN
Liechtenstein                                                   NaN
Lithuania                                                       NaN
Luxembourg                                                      NaN
Macao                                                           NaN
Macedonia (the former Yugoslav Republic of)                     NaN
Madagascar                                                      NaN
Malawi                                                          NaN
Malaysia                                                        NaN
Maldives                                                   540,000
Mali                                                            NaN
Malta                                                           NaN
Marshall Islands                                                NaN
Martinique                                                      NaN
Mauritania                                                      NaN
Mauritius                                                       NaN
Mayotte                                                         NaN
Mexico                                                          NaN
Micronesia (Federated States of)                                NaN
Moldova (Republic of)                                           NaN
Monaco                                                          NaN
Mongolia                                                        NaN
Montenegro                                                      NaN
Montserrat                                                      NaN
Morocco                                                         NaN
Mozambique                                                      NaN
Myanmar                                                         NaN
Namibia                                                         NaN
Nauru                                                           NaN
Nepal                                                   44,000,000
Netherlands                                                     NaN
New Caledonia                                                   NaN
New Zealand                                                     NaN
Nicaragua                                                       NaN
Niger                                                           NaN
Nigeria                                                         NaN
Niue                                                            NaN
Norfolk Island                                                  NaN
Northern Mariana Islands                                        NaN
Norway                                                          NaN
Oman                                                            NaN
Pakistan                                               331,000,000
Palau                                                           NaN
Palestine, State of                                             NaN
Panama                                                          NaN
Papua New Guinea                                                NaN
Paraguay                                                        NaN
Peru                                                            NaN
Philippines                                                     NaN
Pitcairn                                                        NaN
Poland                                                          NaN
Portugal                                                        NaN
Puerto Rico                                                     NaN
Qatar                                                           NaN
Romania                                                         NaN
Russian Federation                                              NaN
Rwanda                                                          NaN
Réunion                                                         NaN
Saint Barthélemy                                                NaN
Saint Helena, Ascension and Tristan da Cunha                    NaN
Saint Kitts and Nevis                                           NaN
Saint Lucia                                                     NaN
Saint Martin (French part)                                      NaN
Saint Pierre and Miquelon                                       NaN
Saint Vincent and the Grenadines                                NaN
Samoa                                                           NaN
San Marino                                                      NaN
Sao Tome and Principe                                           NaN
Saudi Arabia                                                    NaN
Senegal                                                         NaN
Serbia                                                          NaN
Seychelles                                                      NaN
Sierra Leone                                                    NaN
Singapore                                                       NaN
Sint Maarten (Dutch part)                                       NaN
Slovakia                                                        NaN
Slovenia                                                        NaN
Solomon Islands                                                 NaN
Somalia                                                         NaN
South Africa                                                    NaN
South Sudan                                                     NaN
Spain                                                           NaN
Sri Lanka                                               33,000,000
Sudan                                                           NaN
Suriname                                                        NaN
Svalbard and Jan Mayen                                          NaN
Swaziland                                                       NaN
Sweden                                                          NaN
Switzerland                                                     NaN
Syrian Arab Republic                                            NaN
Taiwan, Province of China                                       NaN
Tajikistan                                                      NaN
Tanzania, United Republic of                                    NaN
Thailand                                                        NaN
Timor-Leste                                                     NaN
Togo                                                            NaN
Tokelau                                                         NaN
Tonga                                                           NaN
Trinidad and Tobago                                             NaN
Tunisia                                                         NaN
Turkey                                                          NaN
Turkmenistan                                                    NaN
Turks and Caicos Islands                                        NaN
Tuvalu                                                          NaN
Uganda                                                          NaN
Ukraine                                                         NaN
United Arab Emirates                                            NaN
United Kingdom of Great Britain and Northern Ir...              NaN
United States of America                                        NaN
Uruguay                                                         NaN
Uzbekistan                                                      NaN
Vanuatu                                                         NaN
Venezuela (Bolivarian Republic of)                              NaN
Viet Nam                                                        NaN
Virgin Islands (British)                                        NaN
Virgin Islands (U.S.)                                           NaN
Wallis and Futuna                                               NaN
Western Sahara                                                  NaN
Yemen                                                           NaN
Zambia                                                          NaN
Zimbabwe                                                        NaN
Åland Islands                                                   NaN

continent                                                   Europe  \
sub_region                                         Northern Europe
country
Afghanistan                                                    NaN
Albania                                                        NaN
Algeria                                                        NaN
American Samoa                                                 NaN
Andorra                                                        NaN
Angola                                                         NaN
Anguilla                                                       NaN
Antigua and Barbuda                                            NaN
Argentina                                                      NaN
Armenia                                                        NaN
Aruba                                                          NaN
Australia                                                      NaN
Austria                                                        NaN
Azerbaijan                                                     NaN
Bahamas                                                        NaN
Bahrain                                                        NaN
Bangladesh                                                     NaN
Barbados                                                       NaN
Belarus                                                        NaN
Belgium                                                        NaN
Belize                                                         NaN
Benin                                                          NaN
Bermuda                                                        NaN
Bhutan                                                         NaN
Bolivia (Plurinational State of)                               NaN
Bonaire, Sint Eustatius and Saba                               NaN
Bosnia and Herzegovina                                         NaN
Botswana                                                       NaN
Brazil                                                         NaN
Brunei Darussalam                                              NaN
Bulgaria                                                       NaN
Burkina Faso                                                   NaN
Burundi                                                        NaN
Cabo Verde                                                     NaN
Cambodia                                                       NaN
Cameroon                                                       NaN
Canada                                                         NaN
Cayman Islands                                                 NaN
Central African Republic                                       NaN
Chad                                                           NaN
Chile                                                          NaN
China                                                          NaN
Colombia                                                       NaN
Comoros                                                        NaN
Congo                                                          NaN
Congo (Democratic Republic of the)                             NaN
Cook Islands                                                   NaN
Costa Rica                                                     NaN
Croatia                                                        NaN
Cuba                                                           NaN