Numpy Arrays and Pandas Series

In [1]:
import numpy as np
import pandas as pd

In [2]:
my_list = [10,25,35]

In [3]:
x = np.array(my_list)

print(x)

[10 25 35]

In [4]:
x

array([10, 25, 35])

In [5]:
type(x)

numpy.ndarray

In [6]:
pd.Series(my_list)

0    10
1    25
2    35
dtype: int64

In [7]:
y = pd.Series(my_list)

In [8]:
type(y)

pandas.core.series.Series

In [9]:
index_value = ["Best", "Second Best", "Third Best"]
my_list = [10,25,35]

pd.Series(data = my_list, index = index_value)

Best           10
Second Best    25
Third Best     35
dtype: int64

In [10]:
one = pd.Series(data = my_list, index = index_value)

In [11]:
index_value2 = ["Best", "Second Best", "Forth Best"]
my_list2 = [10,25,40]

two = pd.Series(data = my_list2, index = index_value2)

In [12]:
two

Best           10
Second Best    25
Forth Best     40
dtype: int64

In [13]:
total = one + two
total

Best           20.0
Forth Best      NaN
Second Best    50.0
Third Best      NaN
dtype: float64

In [14]:
total['Best']

20.0

In [15]:
total[0]

C:\Users\khairil.akub\AppData\Local\Temp\ipykernel_24616\3900337425.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  total[0]

20.0

Pandas for Dataframe

In [16]:
import pandas as pd

index_value = ["Best", "Second Best", "Third Best"]
my_list = [10,25,35]

one = pd.Series(data = my_list, index = index_value)
one

Best           10
Second Best    25
Third Best     35
dtype: int64

In [17]:
index_value2 = ["Best", "Second Best", "Forth Best"]
my_list2 = [10,25,40]

two = pd.Series(data = my_list2, index = index_value2)
two

Best           10
Second Best    25
Forth Best     40
dtype: int64

In [18]:
dataframe = pd.DataFrame({'Series 1': one, 'Series 2': two})

In [19]:
print(dataframe)

             Series 1  Series 2
Best             10.0      10.0
Forth Best        NaN      40.0
Second Best      25.0      25.0
Third Best       35.0       NaN

In [20]:
dataframe

             Series 1  Series 2
Best             10.0      10.0
Forth Best        NaN      40.0
Second Best      25.0      25.0
Third Best       35.0       NaN

In [21]:
ice_cream = [['MCC', 1], ['Butterscoth', 2], ['Butter Pecan', 3]]

In [22]:
pd.DataFrame(ice_cream, index = ['Flavor 1', 'Flavor 2', 'Flavor 3'], columns = ('Flavor', 'Scoops'))

                Flavor  Scoops
Flavor 1           MCC       1
Flavor 2   Butterscoth       2
Flavor 3  Butter Pecan       3

In [23]:
pd.DataFrame(ice_cream,  columns = ('Flavor', 'Scoops'))

         Flavor  Scoops
0           MCC       1
1   Butterscoth       2
2  Butter Pecan       3

In [24]:
pd.DataFrame(ice_cream)

              0  1
0           MCC  1
1   Butterscoth  2
2  Butter Pecan  3

Importing CSV files

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing CSV Files\parks_and_recreation.csv')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [4]:
df = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing CSV Files\parks_and_recreation.tsv',
                sep = '\t')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [10]:
df = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing CSV Files\parks_and_recreation_strange_data.csv',
                 skiprows = [0,1,2], names = ['employee_id', 'first_name', 'last_name', 'age', 'gender', 'birth_date'])
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [11]:
df = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing CSV Files\parks_and_recreation_strange_data.csv',
                 skiprows = [0,1,2])
df

    1        Leslie         Knope    44  Female   9/25/1979
0   3           Tom     Haverford  36.0    Male    3/4/1987
1   4         April       Ludgate  29.0  Female   3/27/1994
2   6         Donna        Meagle  46.0  Female   7/30/1977
3   7           Ann       Perkins  35.0  Female   12/1/1988
4   8         Chris       Traeger  43.0    Male  11/11/1980
5   9           Ben         Wyatt  38.0    Male   7/26/1985
6  10          Andy         Dwyer  34.0    Male   3/25/1989
7  11          Mark  Brendanawicz  40.0    Male   6/14/1983
8  12         Craig  Middlebrooks  37.0    Male   7/27/1986
9  13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

Importing Different File Types

In [12]:
import pandas as pd

In [14]:
df = pd.read_json(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing Different File Types\parks_and_recreation.json')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN    None        None

In [15]:
df = pd.read_table(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing Different File Types\parks_and_recreation.txt')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [17]:
df = pd.read_table(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing Different File Types\parks_and_recreation.csv',
                  sep = ',')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [21]:
df = pd.read_excel(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing Different File Types\parks_and_recreation.xlsx'
                  , sheet_name = 'demographics')
df

    employee_id    first_name     last_name   age  gender birth_date
0             1        Leslie         Knope  44.0  Female 1979-09-25
1             3           Tom     Haverford  36.0    Male 1987-03-04
2             4         April       Ludgate  29.0  Female 1994-03-27
3             6         Donna        Meagle  46.0  Female 1977-07-30
4             7           Ann       Perkins  35.0  Female 1988-12-01
5             8         Chris       Traeger  43.0    Male 1980-11-11
6             9           Ben         Wyatt  38.0    Male 1985-07-26
7            10          Andy         Dwyer  34.0    Male 1989-03-25
8            11          Mark  Brendanawicz  40.0    Male 1983-06-14
9            12         Craig  Middlebrooks  37.0    Male 1986-07-27
10           13  Jean-Ralphio    Saperstein   NaN     NaN        NaT

Connecting to a Database (MySQL)

In [22]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\khairil.akub\appdata\local\anaconda3\lib\site-packages (9.5.0)

In [23]:
import pandas as pd
import mysql.connector

In [24]:
# skip

Exporting Data

In [25]:
import pandas as pd

In [26]:
df = pd.read_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing CSV Files\parks_and_recreation.csv')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [27]:
df.to_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing CSV Files\Exports\park_export.csv')

In [29]:
df.to_csv(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing CSV Files\Exports\park_export.csv'
         , index = False, columns = ['first_name', 'last_name'])

In [32]:
df.to_excel(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing CSV Files\Exports\park_export.xlsx'
           , index = False, sheet_name = 'Employees')

In [31]:
!pip install openpyxl xlwt

Requirement already satisfied: openpyxl in c:\users\khairil.akub\appdata\local\anaconda3\lib\site-packages (3.1.5)
Collecting xlwt
  Downloading xlwt-1.3.0-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: et-xmlfile in c:\users\khairil.akub\appdata\local\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Downloading xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
Installing collected packages: xlwt
Successfully installed xlwt-1.3.0

In [33]:
df.to_json(r'C:\Users\khairil.akub\Desktop\Mohd Khairil\Personal\Personal Development\Python\Pandas\Importing CSV Files\Exports\park_export.json')